<?php
namespace Database\Seeders;
use App\Models\{EventProject,Prospect,Offer,PresalePlan,CupPlan,Sponsorship,PlantingSession};
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class AdvantagesMobilizationSeeder extends Seeder {
 public function run(): void {DB::transaction(function(){
  $p=EventProject::where('slug','os-jogos-do-agricultor')->first();$scenario=$p?->launchScenario();if(!$scenario)return;
  $marker=Sponsorship::firstOrCreate(['event_project_id'=>$p->id,'template_key'=>'event-main-v1'],['name'=>'Sponsor principal de l’événement','scope'=>'main','target_profile'=>'Brasseur / distributeur boissons ou fournisseur agricole structurant','pitch'=>'Financement et apports précisément définis, visibilité web hiérarchisée. Mobilier et reprise de fûts seulement selon contrat. Aucun prix ou audience inventé.']);if(!$marker->wasRecentlyCreated)return;
  $municipalities=['Covilhã'=>['P01','P02','P10','P11','P19','P28'],'Belmonte'=>['P03','P04','P05','P06','P07','P08','P09','P22','P23','P24','P25','P26','P31'],'Guarda'=>['P16','P18','P27','P32'],'Fundão'=>['P12','P13','P14','P15','P17','P20','P21','P29','P30','maquidonas-donas'],'Castelo Branco'=>['P33'],'Matosinhos'=>['P34'],'Tondela'=>['P35']];
  foreach($municipalities as $name=>$keys)Prospect::where('event_project_id',$p->id)->whereIn('source_key',$keys)->where('municipality','À confirmer')->update(['municipality'=>$name]);
  foreach($p->offers as $o)if(blank($o->prospect_type))$o->save();
  $prospects=[
   ['sementes-vivas','Sementes Vivas / Living Seeds','Semencier biologique','Idanha-a-Nova','Ladoeiro','Herdade do Couto da Várzea, Estrada Nacional 354, Ladoeiro · code postal à confirmer','info@sementesvivas.bio',null,'https://sementesvivas.bio/faq/ ; https://www.idanha.pt/idanhapt/produtos-e-produtores/s-t-u/sementes-vivas/','O Tabuleiro das Sementes : graines, expertise et financement de l’épreuve.'],
   ['plancei','Viveiros Plancei','Pépiniériste','Lousã','Lousã','R. Dr. Manuel M. Mexia Nº57, 3200-077 Lousã','geral@plancei.pt','+351239995590','https://plancei.pt/','Greffe et plantation collective : conseil, arbres achetés, démonstration et suivi.'],
   ['viveiros-portugal','Viveiros Portugal','Pépiniériste','Macedo de Cavaleiros','Macedo de Cavaleiros','Zona Industrial, Lote 40-43, 5340-296 Macedo de Cavaleiros','geral@viveirosportugal.pt','+351278997275','https://www.viveirosportugal.pt/contactos.html ; https://www.viveirosportugal.pt/plantas/outras-fruteiras.html','Alternative pour la deuxième journée de plantation ; achat et livraison à négocier.'],
  ];foreach($prospects as [$key,$name,$category,$municipality,$sector,$address,$email,$phone,$source,$opportunity])Prospect::firstOrCreate(['event_project_id'=>$p->id,'source_key'=>$key],['entity_key'=>$key,'name'=>$name,'category'=>$category,'municipality'=>$municipality,'sector'=>$sector,'tour'=>'Hors tournée locale · téléphone avant déplacement','priority'=>2,'visit_order'=>100,'address'=>$address,'email'=>$email,'phone'=>$phone,'source'=>$source,'opportunity'=>$opportunity,'next_action'=>'Qualifier le bon interlocuteur par téléphone/email avant de planifier un trajet. Proposition, aucun partenariat acquis.','checked_at'=>'2026-09-30']);
  $pitches=[
   'Omelete Retro'=>['maquidonas-donas','Marque de mini-rétro + concessionnaire / loueur local','Précision du pelliste mise en scène. Solliciter transport, machine, assistance, contribution monétaire et droit aux images. Alternative M.T.A./marque confirmée avec le distributeur. Aucune relation de distribution de MaquiDonas présumée.','https://maquidonas.pt/ ; https://www.mta.pt/'],
   'A Torre do Reboque'=>['P17','Marque de tracteur + concessionnaire + remorque','Piste M.T.A./John Deere : adresse du conducteur, stabilité et démonstration commentée. Prêt/location, transport et conducteur qualifié à contractualiser ; aucun tracteur offert présumé.','https://www.mta.pt/'],
   'O Grande Restaurante'=>['P31','Fournisseur alimentaire / équipement de cuisine local','Associer un partenaire aux accessoires comiques et à l’histoire de la recette ; contribution à la production de l’épreuve et aux images, sans ouvrir un bar concurrent ni promettre du catering non prévu. Padaria Belmontense : première piste locale, équipementier à identifier.','Prospect P31 déjà sourcé ; adéquation commerciale à confirmer.'],
   'O Tabuleiro das Sementes'=>['sementes-vivas','Semencier biologique et fournisseur de substrat','Piste Sementes Vivas : variétés, semis commenté, prix de l’épreuve et contribution aux coûts. Préserver la nature ludique et les vrais conseils agronomiques.','https://sementesvivas.bio/faq/'],
   'Mestre das Mimosas'=>['plancei','Pépiniériste + outillage de greffe','Piste Plancei : pédagogie du greffage et support botanique approprié, matériel de démonstration sans danger puis scène comique. Ne pas promettre une greffe biologiquement impossible ; le dossier technique conserve ses adaptations.','https://plancei.pt/'],
   'O Pichecultor'=>['P11','Fabricant de raccords / irrigation + revendeur local','Approcher le revendeur Mimagro et qualifier un fabricant, par exemple PLIMAT. Kits et circuit à pression adaptée à éprouver, prêt ou apport et contribution aux coûts ; aucune relation Mimagro/PLIMAT présumée.','https://mimagro.pt/loja/ ; https://www.plimat.pt/'],
  ];foreach($p->activities()->where('track','official')->get() as $a){$v=$pitches[$a->name]??[null,'Partenaire technique adapté','Définir le financement et la mise en valeur de cette épreuve.',''];$prospect=Prospect::where('event_project_id',$p->id)->where('source_key',$v[0])->first();Sponsorship::firstOrCreate(['event_project_id'=>$p->id,'template_key'=>'activity-'.$a->template_key],['name'=>'Parrainer · '.$a->name,'scope'=>'activity','activity_id'=>$a->id,'prospect_id'=>$prospect?->id,'target_profile'=>$v[1],'pitch'=>$v[2],'source'=>$v[3].' · consultation 30/09/2026 ; piste non contactée.']);}
  for($slot=1;$slot<=3;$slot++)Sponsorship::firstOrCreate(['event_project_id'=>$p->id,'template_key'=>'event-secondary-'.$slot],['name'=>$slot===3?'Partenaire gobelets · slot secondaire 3':'Partenaire secondaire '.$slot,'scope'=>'secondary','purpose'=>$slot===3?'cups':'general','secondary_slot'=>$slot,'target_profile'=>$slot===3?'Sponsor du stock de gobelets':'Partenaire local ou sectoriel','pitch'=>$slot===3?'Accord sponsor = partenariat acquis ; paiement rapproché = préfinancement reçu. Visibilité web garantie dans le contrat ; marquage des gobelets et présence sur imprimés selon BAT, tirage et dates limites.':'Un des trois rangs secondaires sous le principal. Périmètre, contribution et visibilité web à contractualiser ; impression séparée par lot.'});
  $cups=CupPlan::where('scenario_id',$scenario->id)->first();$source='Tarif transmis par le porteur le 30/09/2026 : 1 000 gobelets, 967,31 € HT, TVA fournisseur 19 %, total arithmétique 1 151,10 €. Soit 0,96731 € HT/unité contre 1,42556 € pour le lot de 250 à 356,39 € HT. La production n’est pas linéaire : 458,25 € HT de moins que 4 lots de 250 (environ 32,15 %). Livraison Portugal, régime IVA, BAT et validité à confirmer. https://www.onlineprinters.org/p/festival-cups';
  if($cups&&$cups->reference_quantity===250&&$cups->reference_net_cents===35639)$cups->update(['reference_quantity'=>1000,'reference_net_cents'=>96731,'reference_gross_cents'=>115110,'reference_source'=>$source,'sponsor_deliverables'=>'Sponsor gobelets : l’un des 3 slots secondaires sous le principal. Accord documenté requis pour le dire acquis ; règlement rapproché séparément. Visibilité web garantie selon contrat, marquage et imprimés par BAT/lot. Ne jamais inclure rétroactivement une marque sur un tirage existant.']);
  $line=$scenario->budgetLines()->where('costing_key','cups-purchase')->first();if($line&&$line->unit_gross_cents===169640&&$line->forecast_quantity===1&&!$line->committed_quantity&&!$line->paid_quantity&&$line->pricing_status==='estimate')$line->update(['name'=>'Gobelets réutilisables : référence 1 000 pièces','unit_gross_cents'=>115110,'vat_basis_points'=>null,'pricing_status'=>'reference','price_source'=>$source,'price_checked_at'=>'2026-09-30']);
  $plan=PresalePlan::where('event_project_id',$p->id)->first();if($plan&&!$plan->tickets()->exists()&&!$plan->is_open&&$plan->terms_version==='draft-presales-2026-09-30'&&str_starts_with($plan->terms_fr??'','PROJET À VALIDER. Soutien facultatif')){
   $plan->update(['name'=>'Tickets-avantages · entrée commune visiteurs et candidats','kind'=>'admission','unified_benefits'=>true,'terms_version'=>'draft-advantages-2026-09-30','sales_strategy'=>'fixed','early_until'=>\Carbon\Carbon::parse('2026-10-30 23:59:59','Europe/Lisbon')->utc(),'benefits'=>[],'early_benefits'=>[],'terms_fr'=>'PROJET À VALIDER. Un ticket comprend l’entrée et une liste d’avantages garantis, identiques pour visiteurs et candidats. Le prix de départ reste à partir de 10 € TTC. Les avantages ordinaires et bonus de prévente doivent être nommés, quantifiés, chiffrés et réservés avant ouverture. Fin des préventes bonifiées proposée : 30 octobre 2026 à 23 h 59, Lisbonne. Choisir soit une remise puis un prix plein justifié, soit un prix fixe et une commission relais réduite à compter du 15 novembre ; aucune réduction de commission junta implicite. Par défaut, 10 % parking, 10 % relais, 10 % junta et 10 % stand/défi ; QAPAS 60 % avant IVA, frais et coût des droits promis. Candidature facultative soumise au scrutin local, sans seconde taxe ni contrepartie différente selon le résultat. Reçu espèces provisoire jusqu’à rapprochement QAPAS. Prix et avantages figés à la création ; paiement carte à engager dans les 30 minutes. Les achats historiques conservent leurs droits.','terms_pt'=>'PROPOSTA POR VALIDAR. Um bilhete inclui entrada e vantagens garantidas, iguais para visitantes e candidatos. Preço inicial a partir de 10 € com IVA. Definir, quantificar, financiar e garantir as vantagens normais e os bónus de pré-venda antes da abertura. Fim proposto dos bónus: 30 de outubro de 2026 às 23h59, Lisboa. Escolher desconto até essa data e preço normal depois, OU preço fixo e redução da comissão dos distribuidores a partir de 15 de novembro. A comissão da junta não baixa implicitamente. Hipótese: 10% estacionamento, 10% distribuidor, 10% junta, 10% stand/desafio; QAPAS 60% antes de IVA, custos e vantagens. Candidatura opcional, sujeita a voto, sem nova taxa nem benefícios diferentes conforme o resultado. Dinheiro entregue ao distribuidor só confirmado após receção pela QAPAS. Preço e vantagens fixados no recibo; iniciar pagamento por cartão em 30 minutos. Direitos históricos mantidos.']);
   if(str_contains($p->price??'','Entrée grand public prévue gratuite'))$p->update(['price'=>'Ticket commun comprenant entrée et avantages garantis, pour visiteurs et candidats. Préventes avec bonus / remise à définir ; fin proposée le 30 octobre. Commissions junta et relais affectées, coûts des avantages réservés. Vente fermée tant que prix, droits, capacités et conditions ne sont pas validés.']);
   $c=$p->registrationCampaign;if($c&&!$c->registrations()->exists()&&$c->terms_version==='draft-2026-09-30'&&!$c->is_open)$c->update(['unified_ticket_terms'=>true,'name'=>'Candidatures experts · même ticket-avantages que les visiteurs','terms_version'=>'draft-unified-v1','terms_fr'=>'PROJET À VALIDER. La candidature aux rôles experts se fait avec le ticket commun, au même prix et avec les mêmes avantages que pour un visiteur. Aucun supplément ni contrepartie conditionnée au résultat du vote. Les citoyens choisissent l’équipe selon le règlement local ; le ticket ne garantit aucune sélection. Les anciennes inscriptions conservent les crédits boissons acceptés dans leurs conditions.','terms_pt'=>'PROPOSTA POR VALIDAR. A candidatura aos papéis especializados usa o mesmo bilhete, preço e vantagens que um visitante. Sem taxa adicional nem contrapartida dependente do voto. A escolha da equipa segue o regulamento local; o bilhete não garante seleção. Inscrições antigas conservam os vales de bebidas previstos nos seus contratos.']);
  }
  $offer=$p->offers()->where('template_key','presale-support')->first();if($offer&&!$offer->is_public)$offer->update(['name'=>'Ticket-avantages · Bilhete com vantagens','prospect_type'=>'public','summary'=>'Entrée + avantages garantis identiques pour visiteurs et candidats. Bonus de prévente à définir et financer.','includes'=>'Entrée et liste contractuelle d’avantages garantis avant achat. Quantités, créneaux, disponibilité et coûts à valider. Reçu QR vérifiable après confirmation QAPAS.','excludes'=>'Aucune sélection automatique dans une équipe. Repas et boissons uniquement si explicitement inclus dans la liste des avantages. Aucune propriété d’arbre ou de terrain.','delivery'=>'Prévente bonifiée proposée jusqu’au 30 octobre 2026. Alternative : baisse de commission relais à compter du 15 novembre. Prix plein et bonus à définir avant vente.','benefits'=>[['label'=>'Même offre pour visiteurs et candidats / mesma oferta para todos','url'=>null],['label'=>'Avantages quantifiés avant paiement / vantagens antes do pagamento','url'=>null],['label'=>'QR de confirmation QAPAS / confirmação QAPAS por QR','url'=>null]]]);
  for($day=1;$day<=2;$day++){$cost=$scenario->budgetLines()->firstOrCreate(['costing_key'=>'planting-day-'.$day],['name'=>'Plantation collective J'.$day.' : arbre, tuteur, protection, eau, livraison, encadrement et entretien','kind'=>'cost','scope'=>'common','unit'=>'arbre complet','forecast_quantity'=>0,'unit_gross_cents'=>null,'vat_basis_points'=>null,'pricing_status'=>'estimate','price_source'=>'Option à dimensionner avec pépiniériste différent chaque jour. Passer la quantité au nombre de slots, coût complet sans double ligne de préparation terrain. Achat QAPAS ; sponsoring ou apport uniquement sur accord.']);PlantingSession::firstOrCreate(['event_project_id'=>$p->id,'day_number'=>$day],['name'=>'J'.$day.' · Une terre, une équipe, un arbre','budget_line_id'=>$cost->id,'instructions_fr'=>'Projet : briefing du pépiniériste, démonstration, petits groupes encadrés, plantation puis arrosage. Un slot = un arbre identifié. Remerciements facultatifs ; emplacement révélé après relevé et autorisation. Activité de clôture, sans score. Parcours accessible, outils, météo, sol, variétés et entretien à confirmer.','instructions_pt'=>'Proposta: instruções do viveirista, demonstração, pequenos grupos acompanhados, plantação e rega. Um slot = uma árvore identificada. Agradecimentos opcionais; localização após levantamento e autorização. Encerramento coletivo, sem pontuação. Confirmar acessibilidade, ferramentas, meteorologia, solo, variedades e manutenção.']);}
  foreach(['junta-confirm'=>['Participation d’une junta confirmée','Uma freguesia junta-se ao projeto'],'relay-meeting'=>['Réunion locale et réseau de points-relais','Vamos conhecer o projeto no café local'],'presales-open'=>['Ouverture des tickets-avantages','Bilhetes com vantagens em pré-venda']] as $key=>[$fr,$pt]){$step=$p->ideas()->where('template_key',$key)->first();if($step)$p->pressReleases()->firstOrCreate(['name'=>$fr],['title_pt'=>$pt,'phase'=>'before','kind'=>'mobilization','depends_on'=>[$step->id],'publication_version'=>'draft-1','channels'=>['website','email','facebook','x'],'body'=>'BROUILLON. Décrire seulement l’étape effectivement franchie, les interlocuteurs ayant accepté d’être cités, les partenaires convenus et l’action attendue. Dates, offre, bénéfices et liens réels à compléter. Valider le texte, les droits, les destinataires et autoriser la diffusion avant de franchir le jalon.','body_pt'=>'RASCUNHO. Descrever apenas a etapa concretizada, os interlocutores autorizados, os parceiros confirmados e o próximo passo. Completar datas, oferta, vantagens e ligações reais. Validar conteúdo, direitos e destinatários antes de autorizar a divulgação.','social_text_pt'=>$pt.'. Saiba mais no site oficial.']);}
  $step=$p->ideas()->where('template_key','presales-open')->first();if($step&&$step->status==='idea'&&blank($step->evidence))$step->update(['name'=>'Ouvrir les tickets-avantages : même offre visiteurs et candidats','experiment'=>'Garantir et chiffrer entrée, avantages communs et bonus prévente. Choisir remise jusqu’au 30/10 OU réduction de commission relais dès le 15/11, sans modifier les commissions junta implicitement. Revoir les conditions FR/PT, l’IVA et la réserve de livraison. Tester QR, espèces, carte, avantages et communications par phase.']);
  app(\App\Domain\Procurement\Consultations::class)->synchronize();
 });}
}
