<?php
namespace Database\Seeders;
use App\Models\{EventProject,FurniturePlan,CateringService,PressRelease,Prospect};
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class HospitalityOperationsSeeder extends Seeder {
 public function run(): void {DB::transaction(function(){
  $p=EventProject::where('slug','os-jogos-do-agricultor')->first();if(!$p)return;
  $s=$p->scenarios()->firstOrCreate(['template_key'=>'launch-hospitality-v1'],['name'=>'Socle actuel · 6 + 6 · abris, soupe et boissons','launch_model'=>true,'shelter_model'=>'distributed','team_target'=>6,'independent_target'=>6,'stand_target'=>12,'minimum_daily_activities'=>3,'guests_per_stand'=>24,'assumptions'=>'Version actuelle : 6 freguesias parrainées + 6 indépendants. Abri par stand : objectif 24 personnes, 12 assises, espaces debout et circulations préservés. Un ensemble table + deux bancs de SIX places inclus ; complément propre, prêté ou option chiffrée. Capacité plus petite ou agrandissement à étudier individuellement. QAPAS exploite boissons, vin chaud et une seule soupe au chou du chef Magalhães, sans snacking. Exposants : produits emballés / marché, pas de sandwiches, transformation, cuisson ni bar payant. Le scénario chapiteau/friterie est conservé comme historique, ses recettes ne sont pas additionnées ici. Investissements et avances décaissés avant la fête restent à financer ; la réutilisation ultérieure à la quinta ne les efface pas.']);
  if($s->wasRecentlyCreated){
   $stands=$p->stands()->whereIn('template_key',array_merge(array_map(fn($i)=>'village-'.$i,range(1,6)),array_map(fn($i)=>'independent-'.$i,range(1,6))))->get();$s->includedStands()->sync($stands->pluck('id')->all());
   foreach($stands as $stand){
    $stand->update(['shelter_target'=>24,'included_furniture_sets'=>1,'extra_furniture_sets'=>0]);
    foreach([['Coûts directs : abri, place, logistique, service mobilier','cost',1],[$stand->kind==='village'?'Parrain principal du stand':'Formule indépendante fondatrice TTC','revenue',1]] as [$name,$kind,$q])$s->budgetLines()->create(['stand_id'=>$stand->id,'scope'=>'stand','name'=>$stand->name.' / '.$name,'kind'=>$kind,'forecast_quantity'=>$q]);
    if($stand->kind==='village')$s->budgetLines()->create(['stand_id'=>$stand->id,'scope'=>'stand','name'=>$stand->name.' / Parrainage relais (jusqu’à trois)','kind'=>'revenue','forecast_quantity'=>0]);
    $s->budgetLines()->create(['stand_id'=>$stand->id,'scope'=>'stand','name'=>$stand->name.' / Options tente et mobilier, devis séparé','kind'=>'revenue','forecast_quantity'=>0]);
   }
   foreach(['Sanitaires, eau potable, déchets et nettoyage final','Énergie, raccordements et éclairage','Accueil, secours, assurances et autorisations','Communication, relais et presse','Régie, captation et écran commun','Fabrication des ensembles table-bancs : investissement payé avant événement','Transport et stockage communs non affectés aux stands'] as $name)$s->budgetLines()->create(['name'=>$name,'kind'=>'cost','scope'=>'common','forecast_quantity'=>1]);
   $s->budgetLines()->create(['name'=>'Nettoyage mimosas et nivellement préalable du terrain','kind'=>'cost','scope'=>'common','unit_gross_cents'=>100000,'forecast_quantity'=>1,'evidence'=>'Enveloppe de 1 000 € demandée par le porteur. Base TTC / HT, IVA, prestataire et devis à confirmer. Ne pas retrancher au motif du futur verger.']);
   $s->budgetLines()->create(['name'=>'Mise à disposition du terrain','kind'=>'cost','scope'=>'common','unit_gross_cents'=>0,'vat_basis_points'=>0,'forecast_quantity'=>1,'evidence'=>'Apport annoncé par le porteur. Frais engagés et rémunération restent à financer séparément.']);
   foreach(['bar'=>'Boissons et vin chaud QAPAS','soup'=>'Soupe au chou du chef Magalhães'] as $scope=>$name){$s->budgetLines()->create(['name'=>$name.' / Production, personnel, équipement et service','kind'=>'cost','scope'=>$scope,'forecast_quantity'=>1]);$s->budgetLines()->create(['name'=>$name.' / Ventes futures hors préfinancement','kind'=>'revenue','scope'=>$scope,'forecast_quantity'=>0]);}
   $official=$p->activities()->where('track','official')->whereNotNull('template_key')->get();$s->includedActivities()->sync($official->pluck('id')->all());
   foreach($official as $a)if($a->status==='idea')$a->update(['funding_scenario_id'=>$s->id,'relay_reveal'=>true]);
   // Existing commercial terms remain in history. New proposals contain no invented prices.
   $p->offers()->whereIn('template_key',['founder-stand','village-patron','relay-sponsor','structural-partner'])->update(['is_public'=>false]);
   foreach([
    ['hospitality-independent','Stand indépendant fondateur · accueil convivial','stand',6,true,'Emplacement et un ensemble table-bancs de six places. Abri et installation définis dans le devis. Objectif de référence : 24 personnes abritées / 12 assises ; mobilier complémentaire propre, prêté ou loué.','Tente plus grande et second ensemble : options chiffrées séparément. Marchandises, vente et personnel de l’exposant. Aucun bar payant, sandwich préparé, transformation ou cuisson sur place.'],
    ['hospitality-patron','Parrainer le stand de sa freguesia','village',6,false,'Participation du village rendue possible, spécialité locale valorisée, visibilité définie avec QAPAS. Un parrain principal par stand ; jusqu’à trois relais sponsors complémentaires.','Ni audience garantie, ni versement informel à l’équipe. Périmètre matériel et prix TTC à contractualiser.'],
    ['hospitality-relay','Café relais · accueillir et mobiliser son village','relay',18,false,'Parrainage local, affichage et orientation. Proposition d’accueillir la réunion d’information puis un atelier d’invention de l’épreuve. Les rendez-vous peuvent être répartis entre relais.','Pas de clientèle ni de consommation garantie. Coûts, invitations, supports et accueil à convenir. Au maximum trois relais par freguesia.'],
    ['hospitality-structural','Partenaire de l’organisation · apports utiles','sponsor',0,false,'Prestations publicitaires et équipements communs définis sur devis. Brasseur : négocier fûts non entamés repris, matériel, livraison et mobilier. Agriculture : démonstrations, semences, terreaux et matériel utiles.','Aucune reprise de stock ni mise à disposition présumée. Accords, valeur des apports, exclusivités, assurance et contreparties à documenter avant engagement.']
   ] as [$key,$name,$kind,$capacity,$founder,$includes,$excludes])$p->offers()->firstOrCreate(['template_key'=>$key],['name'=>$name,'kind'=>$kind,'capacity'=>$capacity,'is_founder'=>$founder,'includes'=>$includes,'excludes'=>$excludes,'delivery'=>'Proposition sans réservation. Prix total TTC, suppléments et calendrier présentés avant accord.','is_public'=>true]);
   $this->steps($p,$s);
  }
  FurniturePlan::firstOrCreate(['event_project_id'=>$p->id,'template_key'=>'douglas-six-seats'],['name'=>'Douglas · ensemble table + deux bancs · 6 places','quantity'=>12,'parts'=>FurniturePlan::illustrativeParts(),'evidence'=>'Débit indicatif à valider pour rigidité, assemblages, charges et finition adaptée au mobilier. Référence d’encombrement : table Leroy Merlin réf. 91233380, 177 × 153 × 76 cm, six places au total. Fabrication QAPAS, pas achat de ce produit. 25 € était une hypothèse de BOIS par banc, pas une quantité de 25 bancs. Protection : hypothèse utilisateur 40 € / 5 L ; rendement et couches à relever sur la fiche du produit retenu. Prix scierie, quincaillerie, travail et logistique inconnus. Comparer 30 / 50 € TTC, sans les annoncer comme tarifs fermes.']);
  CateringService::firstOrCreate(['event_project_id'=>$p->id,'template_key'=>'sopa-couve-magalhaes'],['name'=>'Sopa de couve · chef Magalhães','recipe'=>'Soupe au chou / sopa de couve · une seule recette','chef'=>'Chef Magalhães','service_plan'=>'Service QAPAS : confirmer la recette avec le chef, les ingrédients/allergènes, le lieu de préparation, le maintien au chaud, les portions, le personnel, les bols et le lavage. Famille et proches : préciser les rôles et coûts réels. Pas de snacking. Ne pas compter deux fois achats et production dans le budget.']);
  foreach(json_decode(file_get_contents(database_path('data/prospects-centro-2026.json')),true,512,JSON_THROW_ON_ERROR) as $row)Prospect::firstOrCreate(['event_project_id'=>$p->id,'source_key'=>$row['source_key']],$row);
  foreach([
   ['mobilization','before','mobilization',null,'start','Invitation à construire les jeux / Convite às freguesias','Présenter le concept en préparation, inviter juntas, cafés et volontaires. Réunion au café qui accepte de devenir relais. Ne pas annoncer une fête confirmée.'],
   ['reveal','before','revelation',null,'start','Six freguesias mobilisées : les défis se dévoilent','Après un relais actif documenté dans chacune des six freguesias, révéler les concepts officiels et inviter aux ateliers d’invention. Réalisation, sécurité et implantations restent à confirmer.'],
   ['official','before','official',-30,'start','Annonce officielle du format financé','Après validation du financement, de l’objectif QAPAS, des dates et du lieu : programme, équipes, accès, soupe, partenaires et modalités.'],
   ['reminder','before','reminder',-7,'start','Informations pratiques et rappel','Horaires validés, accès, stationnement, abris, spécialités, soupe du chef et conditions d’essai.'],
   ['live','during','update',0,'start','Échos du jour et images autorisées','Résultats validés, anecdotes, images autorisées et lien du direct. Ne pas diffuser les coordonnées des participants.'],
   ['results','after','results',1,'end','Résultats et remerciements','Résultats homologués et remerciements équilibrés aux équipes, juntas, relais, partenaires et volontaires.'],
   ['review','after','review',7,'end','Bilan vérifié et suite','Fréquentation mesurée, retours des participants et bilan vérifié ; pas de chiffres inventés ni de promesse non financée.']
  ] as [$key,$phase,$kind,$offset,$anchor,$name,$body])PressRelease::firstOrCreate(['event_project_id'=>$p->id,'template_key'=>$key],['name'=>$name,'phase'=>$phase,'kind'=>$kind,'day_offset'=>$offset,'date_anchor'=>$anchor,'scenario_id'=>in_array($kind,['mobilization','revelation'],true)?null:$s->id,'body'=>'BROUILLON DE TRAVAIL — '.$body,'status'=>'draft','is_public'=>false]);
 });}
 private function steps(EventProject $p,$scenario): void {
  $existing=$p->ideas()->get()->keyBy('template_key');$dependency=fn($key)=>isset($existing[$key])?[$existing[$key]->id]:[];
  $defs=[
   ['hospitality-quotes','Chiffrer abris, mobilier, soupe et accords fournisseurs','price','Le socle doit absorber les décaissements, le service et les charges.','Devis scierie, débit validé, tentes, protection, quincaillerie, chef, brasseur, terrain et logistique.',['frame']],
   ['relay-reveal','Révéler les défis après six freguesias avec relais actif','promotion','Un premier relais dans chacun des six villages suffit au déclencheur éditorial.','Vérifier les accords et missions ; annoncer les concepts, puis tenir les ateliers d’invention chez les cafés relais.',['relays']],
   ['independent-sales','Qualifier les six indépendants et leurs options','price','Les offres couvrent leurs coûts directs et contribuent aux frais communs.','Recueillir produits, public attendu, besoin d’abri et de mobilier ; établir devis TTC avec suppléments.',['hospitality-quotes']],
   ['press-official','Préparer l’annonce officielle du format financé','promotion','L’annonce confirme uniquement un format prêt et financé.','Faire valider dates, lieu, contrats, financement, programme et communiqué.',['funding']],
   ['site-install','Valider l’implantation et installer le site','place','Les emprises, abris et circulations sont compatibles.','Contrôler polygones et horaires, accès, séparation des engins, besoins, météo et secours.',['funding']],
   ['event-live','Piloter la fête et la communication pendant l’événement','product','Les responsables peuvent suivre programme, accueil et incidents.','Utiliser le conducteur ; valider résultats, portions et images avant communiqué.',['site-install']],
   ['post-event','Clôturer, remercier et mesurer le résultat réel','price','Le bilan réel permet de décider de la suite.','Rapprocher recettes et dépenses, rembourser avances, rémunérer, reprendre le mobilier, publier bilan validé.',['event-live']],
  ];
  foreach($defs as [$key,$name,$pillar,$hypothesis,$experiment,$deps]){$ids=[];foreach($deps as $d)if(isset($existing[$d]))$ids[]=$existing[$d]->id;$existing[$key]=$p->ideas()->firstOrCreate(['template_key'=>$key],['name'=>$name,'pillar'=>$pillar,'hypothesis'=>$hypothesis,'experiment'=>$experiment,'status'=>'idea','sort_order'=>100+count($existing),'depends_on'=>$ids]);}
  // Only normalize the untouched starter journey. A user's reordered or validated journey is preserved.
  $untouched=$p->ideas()->whereNotNull('owner')->doesntExist()&&$p->ideas()->whereIn('status',['testing','validated'])->doesntExist();
  if($untouched){$sequence=['frame','juntas','hospitality-quotes','team','patron','relays','relay-reveal','communication','independent-sales','funding','press-official','site-install','event-live','post-event','growth'];$n=10;foreach($sequence as $key)if(isset($existing[$key])){$existing[$key]->update(['sort_order'=>$n]);$n+=10;}}
 }
}
