<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\{EventProject,WelcomePackPlan,MerchandisingOption,CommercialPlan,Sponsorship,Prospect};
use App\Domain\Finance\CommercialPricing;
class MerchandisingCommercialSeeder extends Seeder {
 public function run(): void {DB::transaction(function(){
  $p=EventProject::where('slug','os-jogos-do-agricultor')->first();$s=$p?->launchScenario();$pack=$p?WelcomePackPlan::where('event_project_id',$p->id)->first():null;if(!$s||!$pack||$p->commercial_policy_version)return;
  $p->update(['commercial_policy_version'=>'merch-break-even-v1']);
  $s->update(['minimum_organizer_charges_cents'=>max(80000,$s->minimum_organizer_charges_cents??0),'organizer_cost_evidence'=>'Plancher de travail fourni par le porteur : 800 € de charges à couvrir pour cette édition même sans rémunération nette. Période, montant réel, autres charges et fiscalité à confirmer ; aucun calcul réglementaire de cotisation. L’objectif QAPAS existant est conservé.']);
  if($s->organizer_full_monthly_cents===null&&$s->organizer_net_monthly_cents===100000)$s->update(['organizer_net_monthly_cents'=>0]);
  foreach([
   ['merch-prototypes','Prospection : deux prototypes textiles réels',2,1000,'Deux prototypes en plus du lot de 130, hypothèse 10 € TTC pièce, essai photo et lavage. Ne pas les ajouter encore au lot événementiel.'],
   ['qapas-ai-hosting','Outils IA, application et hébergement affectés à l’événement',1,null,'Saisir dépenses réelles imputables à cette édition et période, conserver factures ; ne pas oublier abonnements engagés personnellement.'],
   ['actor-badges','Badges acteurs : impression QR, support et fixation',1,null,'Lot distinct des reçus de billets et des cartes de visite : un badge par acteur, remplacement et attaches. À deviser ; ne pas imprimer de QR sur le t-shirt commun.'],
  ] as [$key,$name,$quantity,$amount,$source])$s->budgetLines()->firstOrCreate(['costing_key'=>$key],['name'=>$name,'kind'=>'cost','scope'=>'common','forecast_quantity'=>$quantity,'unit_gross_cents'=>$amount,'pricing_status'=>'estimate','price_source'=>$source,'price_checked_at'=>'2026-09-30']);
  $methods=[
   'print'=>[[['name'=>'T-shirt avec impression devant/dos','unit_cents'=>1000,'per_piece'=>1]],0,0,0,7500,0,120],
   'patches'=>[[['name'=>'T-shirt préfabriqué','unit_cents'=>400,'per_piece'=>1],['name'=>'Écusson devant','unit_cents'=>200,'per_piece'=>1],['name'=>'Grand écusson dos','unit_cents'=>450,'per_piece'=>1]],60,6,0,10000,1200,180],
   'direct'=>[[['name'=>'T-shirt préfabriqué','unit_cents'=>400,'per_piece'=>1],['name'=>'Broderie sous-traitée devant/dos','unit_cents'=>650,'per_piece'=>1]],0,0,0,10000,0,120],
   'inhouse'=>[[['name'=>'T-shirt préfabriqué','unit_cents'=>400,'per_piece'=>1],['name'=>'Fils, renforts, aiguilles, énergie et pertes','unit_cents'=>150,'per_piece'=>1]],180,20,219432,15000,1200,360],
  ];foreach($methods as $method=>[$costs,$setup,$minutes,$machine,$fixed,$hourly,$qapas])MerchandisingOption::firstOrCreate(['welcome_pack_plan_id'=>$pack->id,'method'=>$method],['name'=>MerchandisingOption::METHODS[$method],'costs'=>$costs,'setup_minutes'=>$setup,'minutes_per_piece'=>$minutes,'machine_cost_cents'=>$machine,'other_fixed_cents'=>$fixed,'hourly_cost_cents'=>$hourly,'opportunity_hourly_cents'=>2500,'qapas_minutes'=>$qapas,'external_unit_cents'=>1050,'external_fixed_cents'=>10000,'source'=>'SIMULATION NON DEVISÉE : pièces, travail, pertes, création, essai et transport à consulter ; valorisation d’opportunité QAPAS à 25 €/h uniquement pour comparer le temps détourné de la prospection. Référence machine à revalider : Fabriprint Brother Innov-is F580 affichée 2 194,32 € et 1 784,00 €, https://www.fabriprint.pt/equipamentos/bordadoras-maquinas-de-costura/broinnovisf580.html, consulté 30/09/2026. Ni machine ni opératrice réservée. Écussons cousus proposés par https://www.asktoprint.pt/vestuario/bones-e-gorros/emblemas-bordados-personalizados/ ; devis nécessaire.','specification'=>'Visuel commun, tailles choisies avec la couche chaude portée dessous ; pas de XXL imposé. Marquage contrasté devant et dos, dimension à tester en photo à distance. Comparer broderie directe, écusson cousu et impression ; valider toucher, poids sur maille, lavage, délai et matrice de broderie. La machine doit accepter le motif voulu sans supposer qu’une machine familiale remplace un équipement professionnel. Accord logo + apport/financement + BAT/échantillon avant production. Variantes alternatives, jamais quatre achats cumulés.']);
  foreach([
   ['protrabalho-textile','PROTRABALHO · broderie et vêtements professionnels','Rua José Caetano Júnior, 73, 6200-126 Covilhã','275 327 591','https://www.protrabalho.eu/contactos/','Comparer vêtements neutres, broderie directe, écussons et impression. Adresse publiée par l’entreprise (73) ; annuaire tiers indiquant 81 non retenu. Appeler avant passage.'],
   ['atelier-tina-textile','Atelier de Costura Tina · couture et applications','Duarte Simões, Centro Comercial da Estação, Loja 22, 6200-481 Covilhã',null,'https://atelierdatina.com/','Demander devis pour coudre des écussons sur 132 pièces, temps de préparation, disponibilité et essai sur la maille retenue. Vérifier adresse complète et horaires avant visite.'],
  ] as [$key,$name,$address,$phone,$source,$pitch])Prospect::firstOrCreate(['event_project_id'=>$p->id,'source_key'=>$key],['entity_key'=>$key,'name'=>$name,'category'=>'Textile / merchandising','municipality'=>'Covilhã','sector'=>'Covilhã','tour'=>'Covilhã · textile, appeler avant visite','address'=>$address,'phone'=>$phone,'source'=>$source,'checked_at'=>'2026-09-30','priority'=>2,'visit_order'=>90,'opportunity'=>$pitch,'next_action'=>'Qualifier atelier, motif, tailles et calendrier ; demander deux prototypes et devis, sans commande.']);
  // Commercial proposals, never promises or receipts. Existing negotiated/paid amounts stay untouched.
  $round=function(int $net){return (int)(ceil(ceil($net*12300/10000)/5000)*5000);};
  foreach(Sponsorship::where('event_project_id',$p->id)->get() as $sp){
   $gross=match(true){$sp->scope==='main'=>250000,$sp->scope==='secondary'&&$sp->purpose==='general'=>125000,$sp->purpose==='cups'=>$round((int)$s->budgetLines()->where('costing_key','cups-purchase')->value('unit_gross_cents')),$sp->scope==='activity'=>$round(max(25000,$sp->activity->costReport()['gross_cents'])),$sp->purpose==='prize'=>61500,$sp->purpose==='shirts'=>$round($pack->report()['estimated_cost_cents']+2000),default=>null};if($gross===null)continue;
   $line=$sp->budgetLine;if(!$line){$line=$s->budgetLines()->firstOrCreate(['costing_key'=>'commercial-'.$sp->template_key],['name'=>'Parrainage proposé · '.$sp->name,'kind'=>'revenue','scope'=>'structural','forecast_quantity'=>1,'unit'=>'contrat','pricing_status'=>'estimate']);$sp->update(['budget_line_id'=>$line->id]);}
   if($line->scenario_id===$s->id&&!$line->committed_quantity&&!$line->paid_quantity&&$line->unit_gross_cents===null)$line->update(['unit_gross_cents'=>$gross,'vat_basis_points'=>2300,'pricing_status'=>'estimate','price_source'=>'TARIF DE PROSPECTION, aucun accord. IVA simulée 23 % à qualifier. Principal 2 500 € TTC ; deux secondaires généraux 1 250 € TTC chacun. Parrains affectés : financement du coût connu, arrondi, périmètre à confirmer. Ne pas additionner une ligne structurelle globale active.','price_checked_at'=>'2026-09-30']);
  }
  $plan=CommercialPlan::firstOrCreate(['scenario_id'=>$s->id],['name'=>'6 + 6 · couvrir les frais et préparer la suite','assumptions'=>'Hypothèse de prospection : six indépendants à 650 € TTC ; six parrains de village portent le solde calculé après les autres partenariats proposés. Réserve de simulation pour inconnus 2 000 €, à ventiler par devis, en plus des imprévus existants. Objectif QAPAS existant conservé (4 000 € par mois au seed), pas de réduction tacite. 800 € de charges par édition au minimum, montant réel à qualifier. Hors profits espérés du bar, soupe, préventes, revente des gobelets et crédit bancaire. Aucun sponsor acquis. Aucun revenu de machine ou commande future supposé.']);
  $standLines=app(CommercialPricing::class)->lines($plan);if($standLines->count()===12&&$standLines->every(fn($l)=>$l->unit_gross_cents===50000&&!$l->committed_quantity&&!$l->paid_quantity&&$l->pricing_status==='estimate'))app(CommercialPricing::class)->apply($plan,true);
  foreach(['sponsor-main'=>250000,'sponsor-secondary'=>125000] as $key=>$amount){$offer=$p->offers()->where('template_key',$key)->first();if($offer&&$offer->price_gross_cents===null&&!$offer->is_public)$offer->update(['price_gross_cents'=>$amount,'delivery'=>'Proposition à négocier, IVA et prestations à confirmer. Aucun accord ni encaissement. Visibilité web contractuelle ; autres supports selon BAT, calendrier et périmètre.']);}
  foreach([['merch-prototypes','Confectionner deux prototypes pour la prospection','promotion','Deux tailles représentatives à essayer sur vêtement chaud. Photographier devant/dos à distance, tester lavage et confort ; pas de logo sponsor utilisé sans accord. Comparer variantes dans Merchandising.'],['commercial-prices','Valider les prix du socle 6 + 6','price','Devis complets, charges réelles, IA et frais personnels, affectations de sponsors, éventuel emprunt et réserve pour la suite. Vendre seulement des prestations chiffrées. Prix calculés ne prouvent pas une demande solvable.'],['actor-badges','Délivrer et tester les badges QR des acteurs','place','Personnes élues / QAPAS / service inscrites au relevé privé. Code officiel sans nom public, période, révocation et contrôle humain des accès sensibles. Un QR copié ne prouve pas l’identité.']] as [$key,$name,$pillar,$experiment])$p->ideas()->firstOrCreate(['template_key'=>$key],['name'=>$name,'pillar'=>$pillar,'hypothesis'=>$name,'experiment'=>$experiment,'depends_on'=>[],'is_public'=>false]);
  app(\App\Domain\Procurement\Consultations::class)->synchronize();
 });}
}
