<?php
namespace Database\Seeders;

use App\Domain\Finance\{FinancialSources,TransportCost};
use App\Domain\Procurement\Consultations;
use App\Domain\Stands\ConstructionCosting;
use App\Models\{ActivityMaterial,BudgetLine,CabinProject,CateringService,CostConsultation,CupPlan,EventProject,FinancialPlan,Prospect,SiteInfrastructure,StandRequirement};
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OperationalCostsSeeder extends Seeder
{
 private array $review=[];
 private function safe($line): bool {
  return $line && in_array($line->pricing_status,['estimate','reference'],true) && !($line->committed_quantity??0) && !($line->paid_quantity??0) && blank($line->receipt_reference) && !CostConsultation::where('costable_type',$line::class)->where('costable_id',$line->id)->where(fn($q)=>$q->whereNotNull('sent_at')->orWhereHas('quotes'))->exists();
 }
 private function revise(BudgetLine|ActivityMaterial|null $line,array $expected,array $changes): bool {
  if(!$this->safe($line)){if($line)$this->review[]=$line->name;return false;}
  foreach($expected as $field=>$value)if($line->$field!==$value){$this->review[]=$line->name;return false;}
  $service=app(Consultations::class);$before=$service->definition($line);$draft=CostConsultation::where('costable_type',$line::class)->where('costable_id',$line->id)->first();
  $line->update($changes+['pricing_status'=>'estimate','price_checked_at'=>'2026-10-01']);
  if($draft&&!$draft->sent_at&&$draft->quotes()->doesntExist()&&$draft->body_fr===$before['body_fr']&&$draft->body_pt===$before['body_pt'])$draft->update($service->definition($line));
  return true;
 }
 private function consultation($line,string $fr='',string $pt=''): void {
  $c=app(Consultations::class)->ensure($line);
  // Preserve sent drafts and supplier replies. New specifications go in private notes.
  $note="Révision opérationnelle 01/10/2026 : ".$line->name.". Quantité : ".app(Consultations::class)->quantity($line).' '.$line->unit.".\n".$line->price_source;
  if(!str_contains($c->local_search_notes??'','Révision opérationnelle 01/10/2026'))$c->update(['local_search_notes'=>trim(($c->local_search_notes??'')."\n".$note)]);
  if($c->wasRecentlyCreated&&$fr)$c->update(['body_fr'=>$c->body_fr."\n\n".$fr,'body_pt'=>$c->body_pt."\n\n".$pt]);
 }
 public function run(): void {
  DB::transaction(function(){
   $p=EventProject::where('slug','os-jogos-do-agricultor')->lockForUpdate()->first();$s=$p?->launchScenario();if(!$s||$p->operational_costs_version)return;
   $this->review=[];
   $defaults=collect(json_decode(file_get_contents(database_path('data/costing-budget-2026.json')),true,512,JSON_THROW_ON_ERROR))->keyBy('costing_key');
   $update=function(string $key,array $changes)use($s,$defaults): bool {
    $d=$defaults[$key];return $this->revise($s->budgetLines()->where('costing_key',$key)->first(),collect($d)->only(['name','unit_gross_cents','forecast_quantity','price_source'])->all(),$changes);
   };
   $update('general-transport',['name'=>'Transport et stockage : autres matériels communs','price_source'=>'Provision TTC 180 € conservée pour les autres matériels communs. Hors trois rotations Dyna tubes, coupe/collecte/transport végétaux, retrait broyeur, livraisons fournisseurs, engins, sanitaires et mobilier déjà isolés. Ventiler les trajets réels avant confirmation ; ne pas réintroduire un forfait couvrant ces mêmes trajets.']);
   $this->revise($s->budgetLines()->where('costing_key','bar-consumables')->first(),['name'=>'Bar : autres consommables et lavage des gobelets','forecast_quantity'=>1,'unit_gross_cents'=>null,'price_source'=>'Remplace les jetables. Stock de gobelets sur cups-purchase uniquement ; ici, lavage, produits, collecte et petits consommables hors soupe, à détailler sans recopier le stock.'],['name'=>'Bar : lavage des gobelets réutilisables et entretien','price_source'=>'Lavage, produits, collecte et entretien du circuit réutilisable. Hors achats festival cups, filtres/café/sucre, gobelets café de secours, agitateurs et serviettes déjà détaillés. Ne pas recopier ces consommables dans ce forfait.']);
   $update('insurance',['unit_gross_cents'=>5000,'vat_basis_points'=>null,'price_source'=>'Indication du porteur : 50 € pour l’assurance événement. Hypothèse non confirmée : devis/police, taxes, engins et démonstrations, montage/démontage, bénévoles, plafonds et exclusions à vérifier. Pas d’IVA de 23 % appliquée automatiquement et aucune couverture acquise.']);
   $wc=$update('wc',['name'=>'Sanitaires : sept cabines autonomes standard','forecast_quantity'=>7,'vat_basis_points'=>null,'price_source'=>'Provision interne 150 € TTC/cabine pour le WEEK-END, non tarif fournisseur. Demande de devis : 500 personnes simultanées, 12 et 13/12/2026, 10–22 h, soupe et bar. Base de consultation 7 standard + 1 PMR ; nombre à confirmer par le loueur selon fréquentation cumulée, durée, mix public et rotations. WCLOC indique majoration avec restauration et durée >6 h : https://www.wcloc.com/pt-pt/numero-de-sanitarios-por-pessoa-em-eventos-ao-ar-livre. Ce n’est pas un minimum réglementaire certifié.']);
   $update('wc-pmr',['name'=>'Sanitaires : une cabine autonome accessible','vat_basis_points'=>null,'price_source'=>'Provision interne 250 € TTC pour le week-end, pas un devis. Une PMR incluse dans les huit cabines de travail ; confirmer effectif accessible avec le loueur. TOI PMR : accès camion, sol ferme et à niveau ; sans raccordement égout. https://www.toitoi.pt/produto/toi-pmr/']);
   $wcTransport=$update('wc-transport',['name'=>'Sanitaires : livraison, vidange finale et reprise','unit_gross_cents'=>30000,'vat_basis_points'=>null,'price_source'=>'Provision interne TTC 300 €, non devis. Livraison/reprise à Aldeia do Souto et vidange finale du parc de huit cabines. Entretien entre les deux journées séparé. Remplacer par devis groupé et annuler les postes inclus pour éviter les doublons.']);
   $water=$update('water',['name'=>'Eau potable : café, soupe et préparation — hors WC','vat_basis_points'=>null,'price_source'=>'Provision TTC 100 €, non devis : approvisionnement eau potable, contenants et raccords pour café/soupe/préparation. 500 cafés × 150 ml = 75 L servis (hypothèse), hors rinçage et pertes. Lavage des mains WC dans un poste distinct. Évacuation des eaux grises de préparation à organiser avec le prestataire ; pas de fosse provisoire créée.']);
   $electric=$update('electrical',['name'=>'Électricité : pose, contrôle, distribution principale et éclairage','vat_basis_points'=>null,'price_source'=>'Provision TTC 250 €, non devis, à revoir sur plan : pose/contrôle, distribution principale, terre/protections, éclairage et protection des passages de câbles. HORS rallonges individuelles et coffrets six sorties acquis dans leurs postes séparés. 6 A/stand à 230 V = 1 380 W ; 16 stands = 22,08 kW théoriques, hors bar/soupe. Groupe déclaré 6 kVA insuffisant seul ; puissance réseau et simultanéité à vérifier, aucune alimentation validée.']);
   $update('soup-ingredients',['forecast_quantity'=>400,'price_source'=>'200 soupes au chou/jour × 2 jours = 400 portions. Provision ingrédients 0,60 €/portion = 240 €, non recette ni devis du chef Magalhães. Composition, grammage, rendement, pertes/allergènes et détail IVA à obtenir. Cuillères, bols et sachets de service séparés.']);
   // Production is not a sale. Keep the independent sales forecast at 300 until demand is revised.
   $bowl=$s->budgetLines()->where('costing_key','soup-bowls')->first();
   $bowls=$this->revise($bowl,['name'=>'Soupe : location ou prêt de bols adaptés, cuillères et lavage','unit_gross_cents'=>null,'forecast_quantity'=>1,'price_source'=>'Devis à demander : bols pour soupe au chou chaude, cuillères, collecte et lavage. Quantités à dimensionner selon 300 portions de travail et rotation réelle. Aucun usage chaud des festival cups admis sans documentation.'],['name'=>'Soupe : 400 bols jetables PP 500 ml avec couvercle','forecast_quantity'=>8,'unit'=>'paquet 50 bols','unit_gross_cents'=>881,'vat_basis_points'=>2300,'pricing_status'=>'reference','price_source'=>'Higienify DELFI PRO SPP500, 7,16 € HT/50 ; hypothèse IVA 23 % = 8,81 € TTC/paquet arrondi. 8 paquets = 400 bols (70,48 €, écart de 2 centimes possible selon arrondi facture). https://www.higienify.pt/products/embalagem-redonda-sopa-500ml-take-away-c-tampa-pk50. Contact alimentaire et température autorisée à confirmer pour la référence exacte. Cuillères séparées. Port non compris.']);
   $septic=$s->budgetLines()->where('costing_key','palheira-septic')->first();
   $this->revise($septic,['unit_gross_cents'=>null,'forecast_quantity'=>1,'price_source'=>'Aucune fosse existante. Étude, autorisations, dimensionnement, travaux, raccordements et maintenance à chiffrer ; comparer location sanitaire temporaire. Dépense intégrale à financer, usage futur du verger sans déduction fictive.'],['forecast_quantity'=>0,'price_source'=>'HORS ÉDITION : ouvrage futur reporté. Location de cabines autonomes à réservoir, vidanges et eaux grises organisées ; pas de fosse temporaire construite. Palheira toujours indisponible comme bloc sanitaire.']);
   $purchase=$s->budgetLines()->where('costing_key','cabins-shredder-purchase')->first();
   $rental=$this->revise($purchase,['forecast_quantity'=>1,'unit_gross_cents'=>null,'price_source'=>'Achat QAPAS financé par l’initiative, non une location. Devis pour le broyage du mimosa et des cannes de diamètre maximal 60 mm : aptitude réelle aux deux matériaux à confirmer, débit, entraînement, livraison, mise en service et protection inclus. Décaissement intégral cette édition, sans amortissement diminuant le besoin de trésorerie. Aucun achat, financement ou paiement présumé acquis. Opérateur, carburant et entretien dans la logistique commune, sans doublon.'],['forecast_quantity'=>0,'price_source'=>'Option d’achat reportée ; location REMO une journée dans stands-shredder-rental. Aucun achat, engagement ou paiement créé. Historique conservé.']);
   $shared=$s->budgetLines()->where('costing_key','cabins-shared-logistics')->first();
   $split=$this->revise($shared,['forecast_quantity'=>1,'unit_gross_cents'=>null,'price_source'=>'Coûts supplémentaires aux travaux de terrain déjà provisionnés. Trajets, manutention, tri/retrait des métaux et ligatures, opérateur du broyeur QAPAS, carburant, entretien et pièces d’usure, traitement des lots à risque de propagation, stockage temporaire, épandage sur place et suivi à chiffrer une seule fois. L’achat du broyeur est dans son poste investissement commun unique. Les 1 000 € de nettoyage/nivellement restent provisionnés ; ne retirer une dépense que sur preuve de coût réellement évité.'],['forecast_quantity'=>0,'price_source'=>'Forfait remplacé par postes nommés : trois rotations tubes Dyna, coupe/collecte/transport végétaux, retrait broyeur, SP98, tri/opérateur/épandage. Inactif pour éviter tout double comptage.']);
   $data=json_decode(file_get_contents(database_path('data/operations-budget-2026.json')),true,512,JSON_THROW_ON_ERROR);
   $categories=[];
   foreach($data as $d){
    $key=$d['costing_key'];
    if((str_starts_with($key,'stands-shredder-')&&!$rental)||(in_array($key,['stands-dyna-tubes','stands-mimosa-logistics','stands-sort-chip','stands-shredder-sp98','stands-shredder-delivery'])&&!$split)||($key==='stands-electric-boxes'&&!$electric)||($key==='wc-mid-service'&&!$wcTransport)||($key==='wc-handwash'&&!$water)||(str_starts_with($key,'soup-')&&!$bowls))continue;
    $category=$d['category'];$phase=$d['phase'];unset($d['category'],$d['phase']);
    if($key==='stands-electric-boxes')$d['forecast_quantity']=(int)ceil($s->includedStands()->count()/6);
    if($key==='stands-dyna-tubes')$d['unit_gross_cents']=TransportCost::calculate(['round_trips'=>3,'one_way_km'=>35,'one_way_minutes'=>35,'handling_minutes_per_trip'=>60,'fuel_ml_per_100km'=>12000,'fuel_cents_per_litre'=>180])['fuel_cents'];
    $line=$s->budgetLines()->firstOrCreate(['costing_key'=>$key],$d+['kind'=>'cost','price_checked_at'=>'2026-10-01']);$categories[$line->id]=[$category,$phase];$this->consultation($line);
   }
   if($electric)$this->electrical($p,$s);
   if($wc)SiteInfrastructure::firstOrCreate(['event_project_id'=>$p->id,'template_key'=>'portable-wc-2026'],['name'=>'Sanitaires mobiles — 7 standard + 1 accessible à deviser','kind'=>'sanitation','status'=>'declared','budget_line_id'=>$s->budgetLines()->where('costing_key','wc')->value('id'),'description'=>'Location autonome 12–13 décembre, pic 500 personnes. Réservoirs et vidanges prestataire, sans fosse provisoire. Quantité, lave-mains, eau, nettoyage, accès camion/PMR et implantation à confirmer. Pas de disponibilité avant validation.']);
   if($bowls){$cups=CupPlan::where('scenario_id',$s->id)->first();if($cups&&in_array($cups->soup_bowl_owner,['undecided','chef_proposed'])&&($cups->soup_bowl_owner==='undecided'||str_starts_with($cups->soup_bowl_agreement??'','Proposition à adresser au chef Magalhães :')))$cups->update(['soup_bowl_owner'=>'qapas_disposable','soup_bowl_agreement'=>'Décision du porteur 01/10/2026 : 400 services jetables adaptés à la soupe chaude. Achat QAPAS, aucun investissement ni droit d’image demandé au chef. Référence/contact alimentaire à vérifier.']);}
   $cupCare=CupPlan::where('scenario_id',$s->id)->first();
   if($cupCare&&$bowls&&$cupCare->washing_plan==='À chiffrer : collecte séparée sale/propre, lavage adapté, séchage, contrôle et personnel. Pour la soupe au chou, demander des bols réutilisables adaptés au chaud, en location ou prêt, avec cuillères et lavage. Ne pas employer ce gobelet pour soupe ou vin chaud sans preuve pour la référence exacte.')$cupCare->update(['washing_plan'=>'Gobelets réutilisables boissons : collecte sale/propre, lavage adapté, séchage, contrôle et personnel à chiffrer. Soupe : bols et cuillères jetables adaptés au chaud, poste séparé. Café/vin chaud : festival cup seulement sur preuve fabricant ; option contenants café chauds séparée tant que non validée.']);
   foreach(CateringService::where('event_project_id',$p->id)->where('planned_portions',300)->whereNull('prepared_portions')->whereNull('sold_portions')->where('chef_confirmed',false)->get() as $service)$service->update(['planned_portions'=>400]);
   $this->materials($p,$s);
   if($electric)foreach($p->offers()->where('is_public',false)->whereIn('template_key',['rental-independent','rental-patron','sponsor-main','sponsor-secondary'])->get() as $offer){
    $benefits=$offer->benefits??[];if(collect($benefits)->contains(fn($b)=>str_starts_with($b['label']??'','Liaison de base prévue dans le prix du stand')))continue;$benefits[]=['label'=>'Liaison de base prévue dans le prix du stand : 6 A, 50 m maximum, après validation technique / Ligação base prevista no preço do stand: 6 A, até 50 m, após validação técnica.','url'=>null];$offer->update(['benefits'=>$benefits]);
   }

   $before=json_decode(file_get_contents(database_path('data/stand-construction-before-logistics.json')),true,512,JSON_THROW_ON_ERROR);
   foreach(CabinProject::where('event_project_id',$p->id)->get() as $c)if($c->construction_costs==$before)$c->update(['construction_costs'=>ConstructionCosting::defaults()]);
   foreach($s->budgetLines()->where('costing_key','like','sponsor-stand-services-%')->get() as $line)$this->revise($line,['unit_gross_cents'=>null,'forecast_quantity'=>1,'price_source'=>'À deviser : mobilier/accueil convenu, branchements, consommations et services propres à ce sponsor. Fabrication du stand et logistique mutualisée dans leurs postes existants ; ne pas les recompter ici. Le prix du partenariat inclut son stand ; aucune seconde recette de location.'],['name'=>'Stand sponsor : mobilier et services particuliers · '.$line->stand->name,'price_source'=>'Mobilier convenu, installation et services propres à ce sponsor à détailler. Hors construction du stand, rallonge 50 m/6 A incluse et transport mutualisé, déjà budgétés. Aucun supplément de recette pour l’électricité de base. Besoins supplémentaires dans la fiche du stand.']);
   $idea=$p->ideas()->where('template_key','cabin-followup')->first();if($idea&&$idea->status==='idea'&&str_contains($idea->experiment??'','Acheter le broyeur QAPAS sur financement de l’initiative'))$idea->update(['experiment'=>str_replace('Acheter le broyeur QAPAS sur financement de l’initiative ; capacité réelle pour mimosa/cannes de 6 cm maximum validée au devis.','Louer le broyeur REMO une journée (100 € indiqués par le porteur), maximum 20 L de SP98 si admis par la machine ; capacité réelle, débit journalier et aptitude mimosa/cannes de 6 cm maximum à confirmer.',$idea->experiment)]);
   foreach($s->budgetLines()->where('kind','cost')->where('forecast_quantity','>',0)->get() as $line)$this->consultation($line);
   $this->suppliers($p);
   $plan=FinancialPlan::where('scenario_id',$s->id)->first();if($plan){app(FinancialSources::class)->synchronize($plan);foreach($categories as $id=>[$category,$phase]){$profile=$plan->profiles()->where('source_type','budget')->where('source_id',$id)->first();if($profile&&$profile->vat_treatment==='pending'&&blank($profile->schedule_evidence)&&array_key_exists($phase,$plan->phaseOptions()))$profile->update(['category'=>$category,'invoice_phase'=>$phase,'cash_schedule'=>[['phase'=>$phase,'share_basis_points'=>10000]],'vat_schedule'=>[['phase'=>$phase,'share_basis_points'=>10000]]]);}}
   $note="\nRévision 01/10/2026 : broyeur loué, 3 rotations Dyna tubes, ≤2,50 m/60 mm végétaux, 3 bobines sisal/stand, liaison 50 m max/6 A incluse à valider, WC autonomes, 500 cafés/édition et 200 soupes/jour. Achats et devis non confirmés. Détails : docs/OPERATIONS-COSTING-2026.md. Production 400 soupes ≠ prévision de ventes (300 conservée).";
   if($this->review)$note.=" Postes conservés car personnalisés, consultés ou engagés : ".implode(' ; ',array_unique($this->review)).'. Vérifier leur périmètre avant cumul avec les nouveaux postes.';
   $s->update(['assumptions'=>($s->assumptions??'').$note,'costs_complete'=>false]);$p->update(['operational_costs_version'=>'rental-logistics-2026-v1']);
  });
 }
 private function electrical($p,$s): void {
  $pole=SiteInfrastructure::where('event_project_id',$p->id)->where('template_key','pole-stands')->first();
  if($pole&&$pole->status==='declared'&&$pole->description==='Plusieurs départs de 4 A envisagés, non confirmés. Dimensionner le nombre, la simultanéité, la protection et la longueur de chaque ligne avec le technicien.')$pole->update(['description'=>'Départs individuels demandés 6 A, longueur maximale 50 m par stand. Coffrets six sorties à dimensionner, protections, capacité amont et phases à vérifier. Aucune capacité réseau ni simultanéité validée.']);
  foreach($s->includedStands as $stand){
   $line=$s->budgetLines()->firstOrCreate(['costing_key'=>'stand-extension-'.$stand->public_id],['name'=>'Électricité : rallonge 50 m maximum · '.$stand->name,'kind'=>'cost','scope'=>'stand','stand_id'=>$stand->id,'expense_type'=>'investment','forecast_quantity'=>1,'unit'=>'rallonge','unit_gross_cents'=>23739,'vat_basis_points'=>null,'pricing_status'=>'estimate','price_checked_at'=>'2026-10-01','price_source'=>'Comparateur AS-Schwabe 60341 H07RN-F 3G2,5 50 m : Duarte Neves affiche 193 € sans base IVA explicite dans la page consultée. Pour provision UNIQUEMENT, 193 supposés HT × 1,23 = 237,39 € ; ce n’est pas un prix TTC fournisseur vérifié. https://www.duarteneves.com/pt/extensoes-e-blocos-de-tomada/2018-neoprene-borracha-extensao-cabo-50m-h07rn-f-3g25-4011160603419.html. Demander devis global/câbles à la longueur réelle. Équipement reste à QAPAS et prestation incluse au prix du stand, aucune nouvelle recette. 6 A maximum demandés : section/protections/terre/chute de tension/cheminement à valider par technicien.']);
   $infra=SiteInfrastructure::firstOrCreate(['event_project_id'=>$p->id,'template_key'=>'extension-'.$stand->public_id],['name'=>'Liaison demandée 6 A · '.$stand->name,'kind'=>'distribution','source_id'=>$pole?->id,'status'=>'declared','budget_line_id'=>$line->id,'amp_limit'=>6,'voltage_v'=>230,'phases'=>'single','cable_marking'=>'H07RN-F 3G2,5 — référence de consultation','conductor_count'=>3,'section_mm2'=>2.5,'description'=>'Liaison 50 m maximum prévue, longueur réelle à relever. AS-Schwabe 60341 comme référence de devis ; coffret partagé six sorties et protections individuelles à définir. Aucun montage/alimentation approuvés.']);
   if(!$stand->requirements()->where('kind','electricity')->exists())StandRequirement::create(['stand_id'=>$stand->id,'name'=>'Liaison de base incluse — 6 A, 50 m maximum','kind'=>'electricity','quantity'=>1,'unit'=>'liaison','requested_amps'=>6,'line_length_m'=>50,'source_id'=>$infra->id,'budget_line_id'=>$line->id,'provided_by'=>'qapas','justification'=>'Prévision de fourniture incluse dans le prix du stand, pas de supplément automatique. Longueur maximale, pas distance mesurée. Lister appareils et puissances réelles avant validation ; 1 380 W est un plafond contractuel envisagé, pas une consommation garantie.']);
  }
 }
 private function materials($p,$s): void {
  $a=$p->activities()->where('template_key','omelete-retro')->first();if(!$a)return;
  $definitions=collect(json_decode(file_get_contents(database_path('data/costing-materials-2026.json')),true,512,JSON_THROW_ON_ERROR))->where('activity_key','omelete-retro')->keyBy('name');
  $m=$a->materials()->where('name','Mini-rétro adaptée et contrôlée')->first();if($this->safe($m)&&$m->unit_gross_cents===9471&&$m->price_source===($definitions['Mini-rétro adaptée et contrôlée']['price_source']??null))$this->revise($m,[],['name'=>'Mini-rétro contrôlée avec pince compatible','price_source'=>$m->price_source.' Révision : aucune adaptation sur mesure demandée. Pince fermante compatible à fournir ou louer ; confirmer axes/attache, masse, hydraulique et aptitude à la manipulation délicate.']);
  $grip=$a->materials()->where('name','Support stable et dispositif de prise à valider')->first();
  if($this->safe($grip)&&$grip->unit_gross_cents===12000&&$grip->price_source===($definitions['Support stable et dispositif de prise à valider']['price_source']??null)){
   $this->revise($grip,[],['name'=>'Pince fermante / grappin compatible — option achat','quantity'=>1,'basis'=>'fixed','procurement'=>'purchase','unit'=>'accessoire','unit_gross_cents'=>27999,'vat_basis_points'=>null,'pricing_status'=>'estimate','price_source'=>'Repère fourni par le porteur : DANWIWEE B0DYMYH4FF, Amazon Belgique, 279,99 €. Page inaccessible à la vérification ; prix/IVA/port Portugal non confirmés. https://www.amazon.com.be/dp/B0DYMYH4FF. Achat facultatif à retirer si une pince compatible est comprise avec la mini-rétro. Ce descriptif de pince à bois ne prouve pas une commande hydraulique ni la compatibilité machine ou la prise d’œufs. Fournisseur doit confirmer axes/attache, ouverture, poids, hydraulique et notice. Pas d’adaptation sur mesure.']);
   $support=$a->materials()->firstOrCreate(['name'=>'Support stable de boîte — hors pince'],['quantity'=>1,'basis'=>'fixed','procurement'=>'loan','unit'=>'support','pricing_status'=>'estimate','price_source'=>'Support de boîte nécessaire distinct de la pince ; matériau, stabilité, mise à disposition et coût à préciser après répétition. Aucun prix nul ou prêt acquis présumé.']);$this->consultation($grip);$this->consultation($support);
  }
  $line=$s->budgetLines()->where('name','Engins : adaptation, assurance et encadrement technique')->first();
  if($this->safe($line)&&$line->unit_gross_cents===null&&str_starts_with($line->price_source??'','Hypothèse interne, non devis, 30/09/2026.'))$this->revise($line,[],['name'=>'Engins : supervision, contrôle et éventuel complément de couverture','price_source'=>'Aucune transformation sur mesure budgétée. Confirmer encadrement, vérification de la pince/machine et couverture des jeux. Assurance événement 50 € dans son poste séparé ; ne prévoir ici qu’un complément explicitement exclu. Opérateur d’équipe ≠ supervision ou couverture confirmée.']);
 }
 private function suppliers($p): void {
  $list=json_decode(file_get_contents(database_path('data/operations-suppliers-2026.json')),true,512,JSON_THROW_ON_ERROR);
  foreach($list as $row)Prospect::firstOrCreate(['event_project_id'=>$p->id,'source_key'=>$row['source_key']],$row+['category'=>'Fournisseur','sector'=>'Logistique événementielle','tour'=>'À distance · fournisseurs','municipality'=>'À distance · Portugal','priority'=>2,'visit_order'=>900,'address_confirmed'=>false,'checked_at'=>'2026-10-01']);
 }
}
