<?php
namespace Database\Seeders;
use App\Models\{EventProject,PresalePlan,OutreachVisit,SiteInfrastructure,Prospect};
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class OutreachPresalesSeeder extends Seeder {
 public function run(): void {DB::transaction(function(){
  $p=EventProject::where('slug','os-jogos-do-agricultor')->first();$s=$p?->launchScenario();if(!$s)return;
  $plan=PresalePlan::firstOrCreate(['event_project_id'=>$p->id],['name'=>'Préventes · candidats puis soutiens · 10 € TTC','terms_version'=>'draft-presales-2026-09-30','terms_fr'=>'PROJET À VALIDER. Soutien facultatif de 10 € TTC ; entrée grand public toujours prévue gratuite. Les candidats achètent une seule prévente, sans second droit de candidature. Une collecte chez un relais ne valide pas le billet : QAPAS doit confirmer la réception du solde, net de commission retenue. Le QR permet de vérifier ce statut. Hypothèse : 1 € parking/nettoyage, 1 € relais, 1 € junta et 1 € stand/défi. Les 2 € freguesia comprennent donc la junta ; pas de cinquième euro affecté ajouté silencieusement. Les 6 € QAPAS restent avant IVA, frais et prestations dues. Pour une vente directe sans relais, conserver l’enveloppe relais/réunion jusqu’à décision documentée. Les affectations liées au terrain de football ou à son balneário demandent un accord distinct. Aucun repas, boisson ou accès payant inclus dans le soutien général à ce stade.','terms_pt'=>'PROPOSTA POR VALIDAR. Apoio facultativo de 10 € com IVA; entrada do público prevista gratuita. Os candidatos compram uma única pré-venda, sem segunda taxa de candidatura. A entrega de dinheiro ao ponto-relais não valida o bilhete: a QAPAS confirma a receção do saldo após comissão retida. O QR permite consultar esse estado. Hipótese: 1 € estacionamento/limpeza, 1 € distribuidor, 1 € junta e 1 € stand/desafio. Os 2 € da freguesia incluem a parte da junta. Os 6 € QAPAS são anteriores ao IVA, custos e prestações devidas. Nas vendas diretas, manter a verba do distribuidor/reunião reservada até decisão documentada. Qualquer afetação à recuperação do campo ou balneário exige acordo próprio. O apoio geral não inclui refeição, bebida ou entrada paga nesta fase.']);
  if(!$plan->wasRecentlyCreated)return; // One-time additive upgrade; future seeds preserve all decisions and edits.
  if(!$p->proposed_start)$p->update(['proposed_start'=>'2026-12-12','proposed_end'=>'2026-12-13','proposed_website'=>'www.forquilha-de-ouro.tld']);
  $letter="Exmo. Senhor Presidente e Exmo. Senhor Tesoureiro,\n\nA QAPAS está a preparar Os Jogos do Agricultor em Aldeia do Souto, com data proposta para 12 e 13 de dezembro de 2026, ainda sujeita às condições de realização. Pretendemos reunir freguesias, produtores e famílias em torno de desafios lúdicos e saberes locais.\nPropomos que a freguesia participe com uma equipa escolhida pelos cidadãos, um stand com uma especialidade local e um desafio próprio testado previamente. Um parceiro principal e até três pontos-relais poderão apoiar o stand. As condições financeiras serão apresentadas por escrito, sem qualquer compromisso implícito.\nAgradecemos a indicação dos contactos profissionais do Presidente e do Tesoureiro e de um interlocutor para acompanhamento. Após confirmação da participação da junta, propomos uma reunião de informação num café local interessado em tornar-se ponto-relais.\nEntregamos esta apresentação em mão nos serviços e ficamos disponíveis para combinar uma conversa. O projeto só será anunciado como confirmado após validação dos meios, autorizações e financiamento.\nCom os melhores cumprimentos,\nStéphane Maissin · QAPAS\n[telefone e email a completar]";
  foreach(Prospect::where('event_project_id',$p->id)->where('category','Junta')->orderBy('visit_order')->get() as $prospect)OutreachVisit::firstOrCreate(['event_project_id'=>$p->id,'name'=>$prospect->name],['freguesia'=>$prospect->sector,'tour'=>$prospect->tour,'visit_order'=>$prospect->visit_order,'letter_pt'=>$letter,'teaser_pt'=>'Está a preparar-se um grande encontro em Aldeia do Souto: Os Jogos do Agricultor. Fim de semana proposto: 12 e 13 de dezembro de 2026, por confirmar. Em breve, novidades no site oficial [endereço definitivo a confirmar].','next_action'=>'Déposer deux courriers nominatifs (président, trésorier) et quelques cartes de visite. Montrer à l’accueil le teaser public, recueillir les coordonnées professionnelles utiles et la date de relance. Regrouper le passage avec les cafés de la tournée ; proposer la réunion seulement après accord de la junta. Ne pas montrer la prévisualisation privée des défis secrets.','contact_source'=>'Prospect déjà recensé ; horaires, accueil, titulaires et contacts personnels à confirmer avant déplacement. '.$prospect->source]);
  $costs=[
   ['field-cards','Tournée : cartes de visite QAPAS','lot','Tirage, papier, recto-verso, création, TVA et livraison à chiffrer. Supports terrain distincts des flyers déjà budgétés pour les relais.'],
   ['field-letters','Tournée : courriers président et trésorier, enveloppes','lot','Deux destinataires par junta ; copies et exemplaires accueil à dimensionner selon tournée. Aucun envoi postal supposé.'],
   ['ticket-sms','Billetterie : confirmations SMS et numéro expéditeur','forfait','Tarif Portugal, segments, numéro expéditeur, délivrabilité et éventuels frais opérateur à confirmer. Volume = billets réellement confirmés ; aucune gratuité supposée.'],
   ['ticket-print','Billetterie : reçus QR pour ventes en espèces','lot','Impression au relais ou blocs contrôlés ? Flux retenu : reçu créé en ligne et imprimé sur place. Papier, matériel et consommables à répartir par mandat. Pas de vente hors connexion sans reçu nominatif.'],
   ['palheira-septic','Palheira : assainissement à créer avant usage sanitaire','ouvrage','Aucune fosse existante. Étude, autorisations, dimensionnement, travaux, raccordements et maintenance à chiffrer ; comparer location sanitaire temporaire. Dépense intégrale à financer, usage futur du verger sans déduction fictive.'],
   ['qapas-demo-benches','QAPAS : quelques bancs de démonstration et plans gratuits','lot','Scierie de Manteigas liée à Carina : identité et interlocuteur à confirmer. Bois offert à solliciter, jamais acquis. Chiffrer transport, quincaillerie, finition, temps et contrôle des bancs. Pas de fabrication du mobilier de tous les exposants ; location participant maintenue. Définir visibilité au stand QAPAS/site et remercier seulement après accord ; plans de jardin/parc à faire vérifier avant diffusion.'],
  ];foreach($costs as [$key,$name,$unit,$note])$s->budgetLines()->firstOrCreate(['costing_key'=>$key],['name'=>$name,'kind'=>'cost','scope'=>'common','unit'=>$unit,'forecast_quantity'=>1,'unit_gross_cents'=>null,'vat_basis_points'=>null,'pricing_status'=>'estimate','price_source'=>$note]);
  $septicCost=$s->budgetLines()->where('costing_key','palheira-septic')->first();
  $main=SiteInfrastructure::firstOrCreate(['event_project_id'=>$p->id,'template_key'=>'main-ls4x16'],['name'=>'Ligne principale déclarée LS 4×16','kind'=>'main_supply','cable_marking'=>'LS 4x16 (à relever sur câble)','conductor_count'=>4,'section_mm2'=>16,'description'=>'Déclaration du porteur, non vérifiée. 4×16 désigne normalement 4 conducteurs de section 16 mm², pas un disjoncteur 16 A. Vérifier référence exacte, alimentation, neutre, terre, protections, longueurs et capacité utile avec le technicien. Aucun schéma de branchement validé.']);
  foreach([['pole-food','Poteau côté baraques QAPAS','Distribution 230 V envisagée pour soupe et boissons ; appareils, puissance continue/démarrage, phases, protections et longueur à relever.'],['pole-stands','Poteau côté stands','Plusieurs départs de 4 A envisagés, non confirmés. Dimensionner le nombre, la simultanéité, la protection et la longueur de chaque ligne avec le technicien.']] as [$key,$name,$description])SiteInfrastructure::firstOrCreate(['event_project_id'=>$p->id,'template_key'=>$key],['name'=>$name,'kind'=>'distribution','source_id'=>$main->id,'description'=>$description]);
  SiteInfrastructure::firstOrCreate(['event_project_id'=>$p->id,'template_key'=>'generator-6kva'],['name'=>'Groupe diesel déclaré 6 kVA','kind'=>'generator','declared_kva'=>6,'description'=>'Plaque signalétique, mono/triphasé, régime continu, sorties, neutre, terre, protections et charge admissible à vérifier. Secours ou source alternative à étudier ; aucune addition automatique avec le réseau ni couplage présumé.']);
  $septic=SiteInfrastructure::firstOrCreate(['event_project_id'=>$p->id,'template_key'=>'palheira-septic'],['name'=>'Fosse / assainissement de la palheira','kind'=>'septic','status'=>'to_build','budget_line_id'=>$septicCost->id,'description'=>'Installation inexistante ; solution, autorisations et financement à valider avant tout usage sanitaire.']);
  SiteInfrastructure::firstOrCreate(['event_project_id'=>$p->id,'template_key'=>'palheira'],['name'=>'Palheira · futur bloc sanitaire central','kind'=>'sanitation','source_id'=>$septic->id,'status'=>'to_build','description'=>'Entre les deux pôles électriques décrits par le porteur. Géométrie et distances à relever ; ne pas inventer de coordonnées. Eau, évacuation, lavage des mains et accessibilité à prévoir.']);
  foreach($s->includedStands()->orderBy('stands.id')->get() as $i=>$stand)if(blank($stand->pitch_number))$stand->update(['pitch_number'=>sprintf('P%02d',$i+1)]);
  $cups=\App\Models\CupPlan::where('scenario_id',$s->id)->first();if($cups&&$cups->soup_bowl_owner==='undecided')$cups->update(['soup_bowl_owner'=>'chef_proposed','soup_bowl_agreement'=>'Proposition à adresser au chef Magalhães : investir dans ses propres bols à son effigie, sous réserve de son accord écrit et des droits sur son image. Définir propriété, quantités, contact alimentaire chaud, impression/BAT, financement, vente ou mise à disposition, lavage, pertes/casse et reprise. Le coût QAPAS reste à chiffrer tant que rien n’est signé.']);
  $ideas=$p->ideas()->get()->keyBy('template_key');$new=[];
  $steps=[['field-kit','Préparer le dossier léger et les cartes de visite','promotion',['frame'],'Valider les courriers président/trésorier, teaser, contact QAPAS et domaine officiel. Chiffrer cartes, enveloppes, impressions ; regrouper juntas et cafés par tournée. www.forquilha-de-ouro.tld est un placeholder, pas un site opérationnel.'],['junta-confirm','Obtenir personnellement la réponse de la junta','place',['juntas'],'Relancer les contacts recueillis à l’accueil. Consigner interlocuteur, réponse, périmètre et accord écrit ; une remise de courrier ne constitue pas une participation.'],['cafe-groundwork','Préparer les cafés lors du même déplacement','promotion',['field-kit'],'Toucher quelques mots du projet, sans révéler les épreuves. Identifier le futur relais, sa salle, ses disponibilités et ses intérêts. Ne pas garantir une date ou la participation de la junta.'],['relay-meeting','Confirmer la réunion chez le futur point-relais','promotion',['junta-confirm','cafe-groundwork'],'Après accord de la junta ET du café, fixer invitation, horaire, supports, rôle des interlocuteurs et consommations. Récupérer l’intérêt local dans l’application. Aucun double financement de la commission et du budget boissons.'],['distribution-contract','Contractualiser et former les agents de distribution','price',['relays'],'10 % de commission prévue : à 10 € le billet, 50 ventes donnent 50 € bruts de commission pour un relais à 49,99 €, avant ses frais/fiscalité. Mandat, caisse, reçus QR, délais de reversement, remboursement, données et contrôle QAPAS à signer.'],['presales-open','Ouvrir les préventes : candidats puis public','price',['distribution-contract'],'Finaliser la contrepartie grand public et la répartition : junta incluse ou supplémentaire dans les 2 € freguesia. Tester carte, espèces, QR, SMS, annulation et réserves. Aucune inscription confirmée avant encaissement QAPAS ; la commission retenue ne doit pas être repaid.']];
  foreach($steps as [$key,$name,$pillar,$deps,$experiment]){$ids=[];foreach($deps as $dep)if(isset($ideas[$dep])||isset($new[$dep]))$ids[]=($new[$dep]??$ideas[$dep])->id;$new[$key]=$p->ideas()->firstOrCreate(['template_key'=>$key],['name'=>$name,'pillar'=>$pillar,'hypothesis'=>'Une démarche locale progressive et traçable transforme l’intérêt en engagements et paiements vérifiables.','experiment'=>$experiment,'depends_on'=>$ids,'status'=>'idea','is_public'=>false,'sort_order'=>1000+count($new)]);}
  foreach(['juntas'=>['field-kit'],'team'=>['relay-meeting'],'communication'=>['distribution-contract'],'funding'=>['presales-open']] as $key=>$deps){$item=$ideas[$key]??null;if($item&&$item->status==='idea'&&blank($item->owner)&&blank($item->evidence))$item->update(['depends_on'=>array_values(array_unique([...($item->depends_on??[]),...array_map(fn($key)=>$new[$key]->id,$deps)]))]);}
  $j=$ideas['juntas']??null;if($j&&$j->status==='idea'&&blank($j->evidence))$j->update(['name'=>'Déposer les courriers aux juntas et recueillir les contacts','experiment'=>'Remise à l’accueil de deux courriers pour président et trésorier ; montrer le teaser public, déposer quelques cartes, noter les coordonnées professionnelles et la date de relance. Ne pas présumer la présence d’élus.']);
  // Stable topological order: keep existing relative preferences where prerequisites permit.
  $remaining=$p->ideas()->orderBy('sort_order')->get();$done=[];$order=10;while($remaining->isNotEmpty()){$next=$remaining->first(fn($i)=>!array_diff($i->depends_on??[],$done));if(!$next)break;$next->update(['sort_order'=>$order]);$order+=10;$done[]=$next->id;$remaining=$remaining->reject(fn($i)=>$i->id===$next->id);}
  foreach($p->offers()->where('template_key','like','hospitality-%')->get() as $o){$o->update(['preview_current'=>true,'image_key'=>$o->kind==='village'?'village':($o->kind==='stand'?'market':'festival')]);if($o->price_gross_cents===null&&in_array($o->kind,['stand','village','relay']))$o->update(['price_gross_cents'=>$o->kind==='relay'?4999:50000,'delivery'=>'Tarif de travail TTC, proposition en préparation : périmètre, disponibilité et contrat à valider avant vente. Les locations de tente/mobilier et suppléments sont précisés dans le devis.']);if(blank($o->summary))$o->update(['summary'=>match($o->kind){'village'=>'Un partenaire principal rend possible la participation d’un stand de freguesia.','relay'=>'Un café mobilise son village et peut distribuer les préventes sous mandat.','stand'=>'Un espace pour présenter et vendre vos produits, avec accueil convivial.',default=>'Une présence utile auprès des villages et des visiteurs.'},'benefits'=>[['label'=>$o->includes,'url'=>null],['label'=>'Périmètre, options et engagements détaillés avant contrat / condições antes do contrato','url'=>null]]]);}
  $p->offers()->firstOrCreate(['template_key'=>'presale-support'],['name'=>'Soutenir sa freguesia · apoio à freguesia','kind'=>'support','summary'=>'Une contribution personnelle ; aucun droit publicitaire exclusif. / Apoio pessoal, sem exclusividade publicitária.','price_gross_cents'=>1000,'capacity'=>0,'preview_current'=>true,'image_key'=>'village','is_public'=>false,'includes'=>'Projet de répartition : parking/nettoyage 1 €, relais 1 €, junta 1 € comprise dans les 2 € freguesia, stand/défi 1 €, QAPAS 6 € avant IVA et coûts. À confirmer avant vente.','excludes'=>'Ni repas, ni boissons, ni droit publicitaire, ni sélection automatique dans une équipe. Entrée grand public prévue gratuite.','delivery'=>'Billet et QR : en attente chez le relais, confirmé seulement après réception par QAPAS. SMS transactionnel selon numéro valable et livraison opérateur.','benefits'=>[['label'=>'Soutien au stand et à son défi / apoio ao stand e desafio','url'=>null],['label'=>'Paiement vérifiable par QR / pagamento verificável por QR','url'=>null],['label'=>'Nom public uniquement sur choix / nome público apenas por opção','url'=>null]]]);
  app(\App\Domain\Procurement\Consultations::class)->synchronize();
 });}
}
