<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\{EventProject,CommunityAward,Sponsorship,WelcomePackPlan,Prospect};
class RecognitionSponsorshipSeeder extends Seeder {
 public function run(): void {DB::transaction(function(){
  $p=EventProject::where('slug','os-jogos-do-agricultor')->first();$s=$p?->launchScenario();if(!$s||$p->prize_policy_version)return;
  $cost=function($key,$name,$quantity=1,$amount=null,$unit='lot',$source=null)use($s){return $s->budgetLines()->firstOrCreate(['costing_key'=>$key],['name'=>$name,'kind'=>'cost','scope'=>'common','forecast_quantity'=>$quantity,'unit'=>$unit,'unit_gross_cents'=>$amount,'pricing_status'=>'estimate','price_source'=>$source??'Coût et apport éventuel à consulter. Une mise à disposition gratuite exige une preuve ; aucun encaissement présumé.','price_checked_at'=>'2026-09-30']);};
  $revenue=function($key,$name)use($s){return $s->budgetLines()->firstOrCreate(['costing_key'=>$key],['name'=>$name,'kind'=>'revenue','scope'=>'structural','forecast_quantity'=>1,'unit'=>'contrat','unit_gross_cents'=>null,'pricing_status'=>'estimate','price_source'=>'Contrat TTC et IVA à qualifier. Une promesse n’est pas un encaissement.']);};
  $prize=CommunityAward::where('event_project_id',$p->id)->firstOrFail();
  foreach(Sponsorship::AWARD_ROLES as $role=>$label){
   $line=$role==='prize'?$revenue('forquilha-prize-sponsor','Parrain du prix Forquilha de Ouro'):$cost('forquilha-'.$role,$label.' · Forquilha de Ouro');
   $profile=match($role){'prize'=>'Crédito Agrícola / assurance / entreprise agricole locale : financer les 500 € du prix communautaire. Piste, aucun accord.','trophy_design'=>'Artiste ou graphiste local : concevoir une fourche reconnaissable, son socle et sa plaque.','trophy_supply'=>'Quincaillerie agricole, ferronnier ou artisan : fournir la fourche, le socle stable et la plaque.','trophy_paint'=>'Peintre, carrossier ou fournisseur de peinture : préparer le support et réaliser la finition dorée.'};
   $sponsor=Sponsorship::firstOrCreate(['event_project_id'=>$p->id,'template_key'=>'forquilha-'.$role],['name'=>$label.' · Forquilha de Ouro','scope'=>'award','purpose'=>$role,'prospect_id'=>$role==='prize'?Prospect::where('event_project_id',$p->id)->where('source_key','ca-belmonte-community')->value('id'):null,'budget_line_id'=>$role==='prize'?$line->id:null,'delivery_cost_line_id'=>$role==='prize'?null:$line->id,'target_profile'=>$profile,'pitch'=>'Une récompense qui restera exposée à la junta gagnante. Crédit précis selon le rôle : prix offert par, conçu par, fourni par, finition par. Visibilité web et remise avec photos selon droits convenus. Une même entreprise peut cumuler les rôles, sans obtenir des voix ou une influence sur les résultats.','delivery_terms'=>$role==='prize'?null:'Livrable et délai à convenir avant accord. Maquette/BAT, fichiers et droits de reproduction pour la conception ; dimensions, poids, stabilité, pointes sécurisées, plaque et transport pour la fourniture ; préparation, finition dorée durable, séchage et réception pour la peinture. Aucun coût prélevé sur le prix de 500 €.','source'=>'Stratégie QAPAS du 30/09/2026. Prospects et artisans à qualifier ; aucun partenaire acquis.']);
   if($role==='prize'&&!$prize->prize_sponsorship_id)$prize->update(['prize_sponsorship_id'=>$sponsor->id,'trophy_brief'=>'Forquilha de Ouro 2026 : véritable symbole agricole, finition dorée (sans prétendre à un métal précieux), socle stable, pointes rendues sûres pour remise et exposition. Nom des Jeux, année et freguesia gagnante sur plaque. Artiste identifié, maquette acceptée par QAPAS, droits de reproduction et photographies convenus. Fourniture, peinture, transport et garde à la junta documentés séparément des 500 € intégralement remis au bénéficiaire communautaire.']);
   $includes=$role==='prize'?'Financer 500 € intégralement affectés à la freguesia gagnante pour son événement convivial de Noël. Le trophée est budgété séparément. Le prix TTC du contrat dépend de son traitement fiscal ; 500 € TTC ne sont pas automatiquement 500 € disponibles.':'Apporter ou financer : '.$label.'. Livrable, coût, délai, droits et réception à convenir. Crédit nominatif correspondant au rôle effectivement réalisé.';
   $p->offers()->firstOrCreate(['template_key'=>'forquilha-'.$role],['name'=>$label.' · Forquilha de Ouro','kind'=>'sponsor','prospect_type'=>'sponsor','capacity'=>1,'preview_current'=>true,'is_public'=>false,'summary'=>$includes,'includes'=>$includes,'excludes'=>'Aucun rang principal ou secondaire, exclusivité sectorielle, audience ou accès aux contacts inclus. Aucun droit sur le vote ou les résultats.','delivery'=>'Accord écrit, fiscalité et droits validés. Les 500 € sont encaissés et réservés avant ouverture des participations. Fabrication et peinture réceptionnées avant les Jeux. Remise du trophée et du prix ensemble.','benefits'=>[['label'=>'Crédit du rôle sur le site / reconhecimento do papel no site','url'=>null],['label'=>'Remise et photos selon droits / entrega e fotografias autorizadas','url'=>null],['label'=>'Plaque du trophée selon BAT / placa após aprovação','url'=>null]]]);
  }
  $shirt=$cost('welcome-shirts','Welcome pack · t-shirt imprimé',130,1000,'t-shirt','HYPOTHÈSE QAPAS : 10 € TTC par pièce imprimée, non devisée. Référence distincte consultée le 30/09/2026 : https://webnial.pt/grafica/t-shirts/ annonce 3,90 € HT à 100 pièces avec petite impression devant seulement ; ce n’est pas le devis pour 130 pièces avec dos et tailles hors S–XL. Confirmer modèle, tailles, grammage, marquage et IVA.');
  $setup=$cost('welcome-setup','Welcome pack · création, BAT et préparation impression',1,5000,'lot','HYPOTHÈSE de 50 € TTC pour création, BAT et préparation. Devis à demander ; si inclus dans le prix par pièce, documenter un zéro ici, sans doubler la dépense.');
  $delivery=$cost('welcome-delivery','Welcome pack · livraison et conditionnement',1,2500,'lot','HYPOTHÈSE de 25 € TTC. Confirmer livraison à Aldeia do Souto et tri par taille ; si inclus dans les pièces, documenter un zéro ici.');
  $shirtRevenue=$revenue('welcome-shirt-sponsor','Sponsor t-shirts · facture et livraison');
  $shirtSponsor=Sponsorship::firstOrCreate(['event_project_id'=>$p->id,'template_key'=>'welcome-shirts'],['name'=>'Sponsor t-shirts · welcome pack','scope'=>'welcome_pack','purpose'=>'shirts','budget_line_id'=>$shirtRevenue->id,'delivery_cost_line_id'=>$shirt->id,'target_profile'=>'Imprimeur textile en apport direct, ou entreprise agricole / assurance / banque finançant la facture. Aucun partenaire présumé.','pitch'=>'Habiller les joueurs élus, QAPAS et les personnes de service : une visibilité portée pendant les défis, la remise et les photos autorisées. Lot prévisionnel de 130 pièces à recalculer après relevé des tailles. Financement du coût complet livré ; prestation publicitaire et IVA du sponsor sur devis, sans attribuer un quatrième slot secondaire.','delivery_terms'=>'Un modèle et un visuel commun pour conserver une réserve interchangeable. QAPAS / joueur / service sur badge de fonction distinct ; pas de noms ou freguesia imprimés sur les pièces de réserve. Logo sponsor sous BAT, preuve de lavage, échantillon, guide de tailles et livraison avant répétition générale. Le t-shirt ne remplace ni vêtement chaud, ni vêtement de travail, ni équipement de protection.']);
  WelcomePackPlan::firstOrCreate(['event_project_id'=>$p->id],['name'=>'Welcome pack · QAPAS, joueurs élus et service','sponsor_id'=>$shirtSponsor->id,'shirt_cost_line_id'=>$shirt->id,'setup_cost_line_id'=>$setup->id,'delivery_cost_line_id'=>$delivery->id,'cohorts'=>[['category'=>'players','quantity'=>84],['category'=>'qapas','quantity'=>6],['category'=>'service','quantity'=>18]],'sizes'=>array_map(fn($size,$quantity)=>compact('size','quantity'),['XS','S','M','L','XL','XXL'],[4,14,32,34,18,6]),'people'=>[],'assumptions'=>'Hypothèse haute : 6 équipes × 14 personnes = 84 joueurs, plus 6 QAPAS et 18 de service. Ce n’est ni une obligation de 14 personnes ni un effectif confirmé. Une seule personne par registre, même si elle cumule des rôles ou aide plusieurs équipes. Un t-shirt par personne pour les deux jours ; réserve globale de 20 %, arrondie au supérieur. Tailles adultes indicatives à remplacer par un relevé individuel. Les exposants et visiteurs ne sont pas bénéficiaires de ce lot.','specification'=>'1 t-shirt souvenir par personne. Visuel commun Os Jogos do Agricultor · édition 2026 ; sponsor sur emplacement convenu au BAT. Coupe, matière, grammage, guide de tailles, échantillon et impression devant/dos à deviser. Porter sur une couche chaude si nécessaire en décembre. Pack simple proposé : t-shirt, badge de fonction et fiche horaires/contacts, sans ajout implicite de boissons ou cadeaux. Badges et fiches à chiffrer dans les impressions générales existantes, sans les compter deux fois.']);
  $p->offers()->firstOrCreate(['template_key'=>'welcome-shirts'],['name'=>'Sponsor t-shirts · vista quem faz os Jogos','kind'=>'sponsor','prospect_type'=>'sponsor','capacity'=>1,'preview_current'=>true,'is_public'=>false,'summary'=>'Habillez les joueurs élus, QAPAS et les personnes de service. Un lot commun avec 20 % de réserve.','includes'=>'Financement de la facture complète du lot imprimé et livré, ou apport en nature contractualisé. Quantités et tailles validées avant commande. Visibilité du sponsor sur le t-shirt et sur sa fiche web selon BAT et droits convenus.','excludes'=>'Ne comprend aucun rang principal ou secondaire, exclusivité sectorielle, audience garantie ou accès aux contacts. Le pack ne modifie pas les avantages du billet.','delivery'=>'Prix commercial sur devis, distinct du coût fournisseur. Réserve physique de 20 % déjà dans le lot ; aucune seconde majoration de 20 % sur la facture. Apport en nature réduit seulement le coût QAPAS documenté, sans encaissement fictif.','benefits'=>[['label'=>'T-shirts joueurs / organização / serviço','url'=>null],['label'=>'Logo selon BAT / logótipo aprovado','url'=>null],['label'=>'Photos autorisées et fiche web / fotos autorizadas e página web','url'=>null]]]);
  $steps=[['forquilha-prefund','Sécuriser les 500 € de la Forquilha de Ouro','price','frame','Prospecter le parrain du prix en priorité, négocier contrat et IVA, rapprocher le paiement puis réserver 500 € nets au bénéficiaire gagnant. Aucun financement de fabrication déduit du prix.'],['forquilha-design','Attribuer conception, fourniture et peinture du trophée','product','frame','Nommer les trois contributeurs, obtenir maquette/BAT, devis ou apports documentés, droits de reproduction, calendrier et responsable de réception.'],['forquilha-ready','Réceptionner la Forquilha de Ouro','product','forquilha-design','Vérifier chaque livrable, transport, finition et sécurité du trophée. Documenter la réception de chaque contribution avant les Jeux.'],['welcome-pack','Préfinancer les t-shirts des acteurs des Jeux','promotion','frame','Proposer le lot au sponsor, valider le relevé des tailles après élection, dédupliquer les rôles, ajouter 20 % de réserve globale et recueillir devis, BAT, financement et délai. Livrer avant répétition générale.'],['award-presentation','Remettre ensemble le trophée et les 500 €','product','forquilha-ready','Résultats arbitrés, bénéficiaire habilité, reçu de remise du trophée et justificatif des 500 € le même jour ; photo et remerciements selon autorisations.']];
  foreach($steps as [$key,$name,$pillar,$dependency,$experiment]){$prior=$p->ideas()->where('template_key',$dependency)->first();$p->ideas()->firstOrCreate(['template_key'=>$key],['name'=>$name,'pillar'=>$pillar,'hypothesis'=>$name,'experiment'=>$experiment,'depends_on'=>$prior?[$prior->id]:[],'sort_order'=>in_array($key,['forquilha-prefund','forquilha-design','welcome-pack'])?11:9990,'is_public'=>false]);}
  $prefund=$p->ideas()->where('template_key','forquilha-prefund')->first();$open=$p->ideas()->where('template_key','presales-open')->first();if($open&&$open->status==='idea'&&blank($open->evidence))$open->update(['depends_on'=>array_values(array_unique([...($open->depends_on??[]),$prefund->id]))]);
  $p->pressReleases()->firstOrCreate(['name'=>'Forquilha de Ouro : les 500 € du prix sont sécurisés'],['title_pt'=>'Forquilha de Ouro: os 500 € do prémio estão assegurados','kind'=>'mobilization','phase'=>'before','depends_on'=>[$prefund->id],'publication_version'=>'draft-prize-v1','channels'=>['website','email','facebook','x'],'body'=>'BROUILLON · annoncer seulement après encaissement et réservation effective des 500 €. Nom du parrain avec accord de citation. Concepteur, fournisseur et peintre cités selon leurs contrats. Le trophée et les 500 € seront remis ensemble à la freguesia gagnante.','body_pt'=>'RASCUNHO · publicar apenas após recebimento e afetação dos 500 €. Identificar o mecenas com autorização e os parceiros do troféu conforme os acordos. O troféu e os 500 € serão entregues juntos à freguesia vencedora.']);
  $remaining=$p->ideas()->orderBy('sort_order')->orderBy('id')->get();$done=[];$order=10;while($remaining->isNotEmpty()){$next=$remaining->first(fn($i)=>!array_diff($i->depends_on??[],$done));if(!$next)throw new \RuntimeException('Parcours cyclique.');$next->update(['sort_order'=>$order]);$order+=10;$done[]=$next->id;$remaining=$remaining->reject(fn($i)=>$i->id===$next->id);}
  $p->update(['prize_policy_version'=>'forquilha-2026-v1']);app(\App\Domain\Procurement\Consultations::class)->synchronize();
 });}
}
