<?php
namespace Database\Seeders;
use App\Models\{EventProject,CupPlan,Prospect};
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class RehearsalProcurementSeeder extends Seeder {
 public function run(): void {DB::transaction(function(){
  $p=EventProject::where('slug','os-jogos-do-agricultor')->first();$s=$p?->launchScenario();if(!$s)return;
  $plan=CupPlan::firstOrCreate(['scenario_id'=>$s->id],[
   'name'=>'Gobelets · 1 000 prévus · 500 / 500',
   'reference_source'=>'Copie de tarif communiquée par le porteur : Onlineprinters, 300 ml, 250 pièces, 356,39 € HT / 424,10 € avec 19 % et livraison annoncée. Ce taux et cette livraison ne confirment pas une facturation au Portugal. Prix pour 1 000, échéance, compatibilité alimentaire et thermique à demander. https://www.onlineprinters.org/p/festival-cups',
   'washing_plan'=>'À chiffrer : collecte séparée sale/propre, lavage adapté, séchage, contrôle et personnel. Pour la soupe au chou, demander des bols réutilisables adaptés au chaud, en location ou prêt, avec cuillères et lavage. Ne pas employer ce gobelet pour soupe ou vin chaud sans preuve pour la référence exacte.',
   'sales_and_returns_terms'=>'Projet : QAPAS vend aux stands avec une marge à fixer ; prix professionnel encore inconnu. Les stands gèrent leur stock, la consigne visiteur conseillée de 2,50 € et son remboursement. Définir qui reprend quoi, où et jusqu’à quand, la casse, les invendus et le solde final. Aucune hypothèse de souvenir conservé n’est une recette acquise. La gestion des gobelets ne crée pas de bar payant chez les exposants.',
   'sponsor_deliverables'=>'Proposition à négocier : financement de la production ; présence de marque définie par contrat, BAT conjoint avant impression, nombre de gobelets commandés et livrés justifié. Aucun sponsor acquis, aucune audience ni conservation des souvenirs garantie.',
  ]);
  if($plan->wasRecentlyCreated){
   $p->update(['require_activity_trials'=>true]);
   // Revise only untouched working assumptions, never quotations or actual commitments.
   $revise=function($query,$price,$qty,array $data){$line=$query->first();if($line&&$line->unit_gross_cents===$price&&$line->forecast_quantity===$qty&&!$line->committed_quantity&&!$line->paid_quantity&&in_array($line->pricing_status,['estimate','reference'],true))$line->update($data+['pricing_status'=>'estimate']);};
   $revise($s->budgetLines()->where('name','Mini-rétro : transport aller et reprise'),15990,2,['unit_gross_cents'=>15000,'forecast_quantity'=>1,'unit'=>'forfait','vat_basis_points'=>null,'price_source'=>'Indication du porteur : 150 € pour le transport mini-rétro. HT/TTC, aller-retour, période et éventuel second trajet pour répétition à confirmer. Ce n’est pas une offre de MaquiDonas. Comparer prêt/location au village et apport sponsor.']);
   $revise($s->budgetLines()->where('costing_key','bar-consumables'),12,700,['name'=>'Bar : autres consommables et lavage des gobelets','unit_gross_cents'=>null,'forecast_quantity'=>1,'unit'=>'forfait','vat_basis_points'=>null,'price_source'=>'Remplace les jetables. Stock de gobelets sur cups-purchase uniquement ; ici, lavage, produits, collecte et petits consommables hors soupe, à détailler sans recopier le stock.']);
   $revise($s->budgetLines()->where('costing_key','soup-bowls'),20,300,['name'=>'Soupe : location ou prêt de bols adaptés, cuillères et lavage','unit_gross_cents'=>null,'forecast_quantity'=>1,'unit'=>'forfait','vat_basis_points'=>null,'price_source'=>'Devis à demander : bols pour soupe au chou chaude, cuillères, collecte et lavage. Quantités à dimensionner selon 300 portions de travail et rotation réelle. Aucun usage chaud des festival cups admis sans documentation.']);
   $revise($s->budgetLines()->where('name','Animations inventées par les équipes et indépendants'),null,1,['forecast_quantity'=>0,'price_source'=>'Option inactive : chaque défi externe est testé chez son proposant puis installé et contrôlé dans la semaine avant ouverture. S’il n’est pas prêt, le stand reste et le défi est retiré. Chiffrer les besoins des défis effectivement inclus, sans ajouter une deuxième provision globale. Les dépenses déjà engagées restent dues.']);
   $s->budgetLines()->firstOrCreate(['costing_key'=>'cups-purchase'],['name'=>'Gobelets réutilisables : provision de stock à confirmer','kind'=>'cost','scope'=>'cups','unit'=>'lot de 1 000','forecast_quantity'=>1,'unit_gross_cents'=>169640,'vat_basis_points'=>null,'pricing_status'=>'estimate','price_source'=>'PROVISION, pas un devis pour 1 000 : quatre lots de 250 à 424,10 € selon copie du porteur = 1 696,40 €. Référence net : 4 × 356,39 € = 1 425,56 €. Remplacer par offre réelle 1 000 pièces livrées au Portugal, IVA et BAT confirmés. Ne pas compter de gratuité sponsor ni de remise.']);
   $s->budgetLines()->firstOrCreate(['costing_key'=>'cups-resale'],['name'=>'Revente QAPAS des gobelets aux stands','kind'=>'revenue','scope'=>'cups','unit'=>'gobelet','forecast_quantity'=>1000,'unit_gross_cents'=>null,'vat_basis_points'=>null,'pricing_status'=>'estimate','price_source'=>'Prix professionnel QAPAS à définir avec marge, IVA et conditions de stock/retour. La consigne visiteur conseillée de 2,50 € ne fixe pas ce tarif et n’est pas une recette QAPAS. Aucun stock livré ou payé présumé.']);
   foreach(['village','independent'] as $kind){$stands=$s->includedStands()->where('kind',$kind)->orderBy('stands.id')->get();$count=$stands->count();foreach($stands as $i=>$stand)$plan->allocations()->firstOrCreate(['stand_id'=>$stand->id],['planned_quantity'=>intdiv(500,$count)+($i<(500%$count)?1:0)]);}
  }
  foreach($s->includedActivities()->where('proposer_type','organization')->get() as $a)$a->trials()->firstOrCreate(['stage'=>'official_rehearsal'],['result'=>'planned','adjustments'=>'Préparer un week-end avec des volontaires du village : jouabilité, chrono, arbitrage, visibilité, accès, sécurité et quantités réelles. Dates, lieu, responsables, volontaires et encadrement restent à fixer. Le compte rendu ne constitue pas une autorisation technique d’utiliser un engin.']);
  $previous=null;foreach([
   ['trial-official','Organiser le week-end de répétition des épreuves officielles',75,'Fixer les dates avec les volontaires du village. Confirmer engins, opérateurs, assurance, coût de transport et encadrement pour les essais et pour l’événement. Mesurer consommables et durée ; corriger puis valider chaque compte rendu.'],
   ['trial-local','Faire tester chaque défi externe dans sa freguesia',80,'Le proposant teste chez lui avant transport : scénario drôle, jouable, accessible et sûr, matériel et responsable identifiés. Saisir le compte rendu local. Le stand demeure même si le défi est abandonné.'],
   ['trial-site','Installer et contrôler les défis retenus durant la semaine avant ouverture',85,'Après essai local, installation à la Quinta entre J−7 et le coup d’envoi. Vérifier l’implantation réelle, les flux et les besoins ; valider le contrôle. Sans validation : retirer le défi, maintenir le stand et conserver toute dépense déjà engagée. Le programme officiel reste le socle.'],
  ] as [$key,$name,$order,$experiment]){$idea=$p->ideas()->firstOrCreate(['template_key'=>$key],['name'=>$name,'pillar'=>'product','hypothesis'=>'Un programme officiel répété et des défis externes optionnels évitent une dépendance aux équipes non prêtes.','experiment'=>$experiment,'sort_order'=>$order,'depends_on'=>$key==='trial-site'&&$previous?[$previous->id]:[],'status'=>'idea','is_public'=>false]);$previous=$idea;}
  Prospect::firstOrCreate(['event_project_id'=>$p->id,'source_key'=>'maquidonas-donas'],['entity_key'=>'maquidonas','name'=>'MaquiDonas','category'=>'Location et transport de machines','sector'=>'Fundão / Donas','tour'=>'Fundão / Donas · sur rendez-vous','priority'=>1,'visit_order'=>10,'address'=>'Estrada Camarária Nº 10, 6230-173 Donas','phone'=>'+351 275 751 012','email'=>'geral@maquidonas.pt','opportunity'=>'Transport mini-rétro, location/prêt et geste partenaire à solliciter ; distinguer répétition et événement.','next_action'=>'Contacter avant déplacement et comparer avec les mini-rétros disponibles au village. Aucun email envoyé par l’application.','source'=>'Coordonnées professionnelles publiques : https://maquidonas.pt/sobre-nos/ ; location et transport sur https://maquidonas.pt/ . Disponibilité et geste commercial non confirmés.','checked_at'=>'2026-09-30']);
  app(\App\Domain\Procurement\Consultations::class)->synchronize();
  $transport=$s->budgetLines()->where('name','Mini-rétro : transport aller et reprise')->first();if($transport){$c=app(\App\Domain\Procurement\Consultations::class)->ensure($transport);if(blank($c->local_search_notes))$c->update(['local_search_notes'=>'Pistes : MaquiDonas, geral@maquidonas.pt, +351 275 751 012 (source https://maquidonas.pt/sobre-nos/). Référence du porteur : transport 150 €, périmètre et IVA inconnus ; aucun devis reçu de MaquiDonas. Chercher aussi prêt/location au village et bouche-à-oreille. Demander un tarif séparé pour répétition et jeux, sans promesse de sponsoring acquise.']);}
 });}
}
