@props(['project','preview'=>false])
@if($project->prize_policy_version)
@php($pt=app()->getLocale()==='pt')
@php($awardReport=app(\App\Domain\Awards\Forquilha::class)->report($project))
<section class="event-section event-card"><p class="eyebrow">Forquilha de Ouro · 2026</p><h2>{{ $pt?'Um troféu, 500 € para a freguesia vencedora':'Un trophée, 500 € pour la freguesia gagnante' }}</h2>
<p>{{ $pt?'A Forquilha de Ouro e os 500 € serão entregues juntos. O prémio cofinancia um convívio de Natal para a comunidade; o custo do troféu não é descontado desses 500 €.':'La Forquilha de Ouro et les 500 € seront remis ensemble. Le prix cofinance un événement convivial de Noël pour les citoyens ; le coût du trophée ne sera pas déduit de ces 500 €.' }}</p>
<p class="notice">{{ $awardReport['secured']?($pt?'Os 500 € do prémio foram recebidos e reservados.':'Les 500 € du prix ont été encaissés et réservés.'):($pt?'Procuramos o mecenas do prémio. As participações pagas só abrem após os 500 € estarem recebidos e reservados.':'Nous recherchons le parrain du prix. Les participations payantes n’ouvriront qu’après encaissement et réservation des 500 €.') }}</p>
<ul class="offer-benefits">@foreach(['prize','trophy_design','trophy_supply','trophy_paint'] as $purpose)
@php($partner=$purpose==='prize'?$awardReport['sponsor']:($awardReport['parts'][$purpose]['partner']??null))
<li>{{ $pt?['prize'=>'Mecenas dos 500 €','trophy_design'=>'Conceção do troféu','trophy_supply'=>'Fornecimento e construção','trophy_paint'=>'Pintura e acabamento'][$purpose]:\App\Models\Sponsorship::AWARD_ROLES[$purpose] }} — {{ $partner?->visible()?$partner->sponsor_name:($pt?'parceiro a anunciar':'partenaire à annoncer') }}</li>@endforeach</ul>
<p>{{ $pt?'Uma empresa pode assumir vários papéis. Crédito no site, na placa e na entrega conforme acordo e aprovação gráfica. Sem interferência na votação ou no resultado.':'Une entreprise peut cumuler plusieurs rôles. Crédit sur le site, la plaque et lors de la remise selon accord et BAT. Aucune influence sur le vote ou les résultats.' }}</p>
<a class="qapas-button" href="{{ route($preview?'event.preview':'event.show',['project'=>$project->slug]) }}#interest">{{ $pt?'Quero apoiar o prémio ou o troféu':'Je souhaite parrainer le prix ou contribuer au trophée' }} →</a></section>
<section class="event-section event-card"><h2>{{ $pt?'Vista quem faz os Jogos':'Habillez celles et ceux qui font les Jeux' }}</h2><p>{{ $pt?'Uma t-shirt para cada jogador eleito, membro da organização QAPAS e pessoa de serviço, com 20% de reserva. Um só pack por pessoa, mesmo com várias funções. Quantidades e tamanhos individuais confirmados antes da encomenda.':'Un t-shirt pour chaque joueur élu, membre de l’organisation QAPAS et personne de service, avec 20 % de réserve. Un seul pack par personne, même avec plusieurs fonctions. Effectifs et tailles individuelles confirmés avant commande.' }}</p>
<p>{{ $pt?'O parceiro financia o lote impresso e entregue ou fornece as peças conforme acordo. Logótipo aprovado na peça e reconhecimento no site; o preço depende do orçamento e das prestações acordadas.':'Le partenaire finance le lot imprimé et livré ou fournit les pièces selon accord. Logo validé sur le vêtement et remerciements sur le site ; prix selon devis et prestations convenues.' }}</p>
@if($preview)@php($pack=\App\Models\WelcomePackPlan::where('event_project_id',$project->id)->first())@if($pack)@php($packReport=$pack->report())<p class="notice">{{ $pt?'Pré-visualização privada · hipótese':'Prévisualisation privée · hypothèse' }} : {{ $packReport['people'] }} × {{ $pack->shirts_per_person }} + {{ $packReport['reserve'] }} = {{ $packReport['total'] }} t-shirts. {{ $pt?'Não é uma encomenda.':'Ce n’est pas une commande.' }}</p>@endif @endif
@php($shirtPartner=\App\Models\Sponsorship::where('event_project_id',$project->id)->where('scope','welcome_pack')->where('purpose','shirts')->where('status','agreed')->first())
@if($shirtPartner?->visible())<p>{{ $pt?'Parceiro t-shirts':'Partenaire t-shirts' }} : {{ $shirtPartner->sponsor_name }}</p>@endif
<a class="qapas-button" href="{{ route($preview?'event.preview':'event.show',['project'=>$project->slug]) }}#interest">{{ $pt?'Quero ser parceiro dos t-shirts':'Je souhaite sponsoriser les t-shirts' }} →</a></section>
@endif
