<x-layout :title="__('tickets.presale')"><section class="event-hero event-hero--small"><div><p class="eyebrow">{{ $project->name }}</p><h1>{{ __('tickets.presale') }}</h1><p class="lead">{{ \App\Domain\Finance\Money::format($plan->price_cents) }} · IVA incluído / TTC</p></div></section><div class="event-content">
@if(!config('registration.live'))<p class="notice">{{ __('tickets.test') }}</p>@endif
<p>{{ __('tickets.'.$plan->kind) }}</p><p>{{ __('tickets.candidate_notice') }}</p>
@if($relay)<p>{{ $relay->name }} · {{ $relay->standPartner->stand->freguesia }} · {{ $plan->relay_basis_points/100 }} %</p>@endif
@if($cash)<p class="notice">{{ __('tickets.cash_notice') }}</p>@endif
<section class="event-card"><h2>{{ __('tickets.split') }}</h2><ul>@php($assigned=0)@foreach(['parking'=>'Parking / limpeza','relay'=>'Relais / reunião','junta'=>'Junta','village'=>'Stand / desafio'] as $key=>$label)@php($part=intdiv($plan->price_cents*$plan->{$key.'_basis_points'},10000))@php($assigned+=$part)<li>{{ $label }} : {{ \App\Domain\Finance\Money::format($part) }}</li>@endforeach<li>{{ __('tickets.qapas') }} : {{ \App\Domain\Finance\Money::format($plan->price_cents-$assigned) }}</li></ul><p class="preserve-lines">{{ $plan->{'terms_'.app()->getLocale()} }}</p><h3>{{ __('tickets.refund') }}</h3><p class="preserve-lines">{{ $plan->{'refund_'.app()->getLocale()} }}</p></section>
@if(!$open)<p class="notice">{{ __('tickets.closed') }}</p>@else
@if($errors->any())<ul class="notice" role="alert">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul>@endif
<form method="post" action="{{ route('presales.store',['project'=>$project->slug]) }}" class="event-form">@csrf<input type="hidden" name="request_id" value="{{ $token }}"><input type="hidden" name="terms_version" value="{{ $plan->terms_version }}"><input type="hidden" name="candidate_terms_version" value="{{ $project->registrationCampaign?->terms_version }}">
<label>{{ __('tickets.name') }}<input name="buyer_name" required maxlength="120" value="{{ old('buyer_name') }}"></label><label>{{ __('tickets.email') }}<input type="email" name="email" maxlength="254" value="{{ old('email') }}"></label><label>{{ __('tickets.phone') }}<input type="tel" name="phone" required pattern="\+[1-9][0-9]{7,14}" maxlength="16" value="{{ old('phone') }}"></label>
<label>{{ __('tickets.village') }}<select name="stand_id" required>@foreach($stands as $stand)<option value="{{ $stand->id }}">{{ $stand->freguesia }} · {{ $stand->name }}</option>@endforeach</select></label>
@if($project->registrationCampaign)<fieldset><label class="check"><input type="checkbox" name="candidate" value="1" @checked(old('candidate',request()->boolean('candidate')))><span>{{ __('tickets.candidate') }}</span></label><p class="preserve-lines">{{ $project->registrationCampaign->{'terms_'.app()->getLocale()} }}</p><p>{{ $project->registrationCampaign->{'refund_policy_'.app()->getLocale()} }}</p>@foreach(\App\Domain\Teams\ExpertRoles::CODES as $role)<label class="check"><input type="checkbox" name="expert_roles[]" value="{{ $role }}" @checked(in_array($role,old('expert_roles',[])))><span>{{ __('events.roles.'.$role) }}</span></label>@endforeach</fieldset>@endif
<label class="check"><input type="checkbox" name="terms" value="1" required><span>{{ __('tickets.terms') }}</span></label><label class="check"><input type="checkbox" name="privacy" value="1" required><span>{{ __('tickets.privacy') }} <a href="{{ route('privacy') }}">{{ __('events.privacy') }}</a></span></label><label class="check"><input type="checkbox" name="public_listing" value="1" @checked(old('public_listing'))><span>{{ __('tickets.public_listing') }}</span></label><label>{{ __('tickets.public_name') }}<input name="public_name" maxlength="80" value="{{ old('public_name') }}"></label>
@if($cash)<label class="check"><input type="checkbox" name="cash_received" value="1" required><span>{{ __('tickets.cash_received') }}</span></label>@endif<div class="trap" aria-hidden="true"><input name="website" tabindex="-1" autocomplete="off"></div><button type="submit" class="qapas-button">{{ __('tickets.submit') }} →</button></form>@endif
<p><a href="{{ route('tickets.list',['project'=>$project->slug]) }}">{{ __('tickets.listing') }}</a></p></div></x-layout>