<x-layout :title="__('tickets.receipt')"><section class="event-hero event-hero--small"><div><p class="eyebrow">{{ $ticket->plan->eventProject->name }}</p><h1>{{ __('tickets.verify') }}</h1><p>{{ $ticket->public_id }}</p></div></section><div class="event-content">
@if(!$ticket->is_live)<p class="notice">{{ __('tickets.test') }}</p>@endif
<p class="notice" role="status"><strong>{{ __('tickets.'.($ticket->valid()?'paid':($ticket->status==='pending'?'pending':'invalid'))) }}</strong></p>
@if(session('ticket_notice'))<p role="status">{{ session('ticket_notice') }}</p>@endif
@if($errors->any())<ul class="notice">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul>@endif
<div class="event-grid"><section class="event-card"><div class="ticket-qr">{!! $ticket->qrSvg() !!}</div><p>{{ __('tickets.qr_notice') }}</p><p><a href="{{ $ticket->verifyUrl() }}">{{ $ticket->verifyUrl() }}</a></p><p>{{ __('tickets.print') }}</p></section><section class="event-card"><h2>{{ $owner?$ticket->buyer_name:mb_substr($ticket->buyer_name,0,1).'•••' }}</h2><p>{{ $ticket->freguesia }}</p><p>{{ \App\Domain\Finance\Money::format($ticket->amount_cents) }} TTC / IVA incluído</p><p>{{ __('tickets.subject') }} : {{ __('tickets.kind_'.$ticket->kind) }}</p>@if($ticket->channel==='cash')<p>{{ __('tickets.cash_notice') }}</p>@endif@if($ticket->redeemed_at)<p>{{ __('tickets.used') }} · {{ $ticket->redeemed_at->timezone('Europe/Lisbon')->format('d/m/Y H:i') }}</p>@endif
@if($owner && $ticket->benefits_snapshot!==null)<h3>{{ __('tickets.benefits') }}</h3><p>{{ __('tickets.entry_included') }}</p><ul>@foreach($ticket->benefits_snapshot as $index=>$benefit)<li>{{ $benefit['label_'.app()->getLocale()]??$benefit['label_fr'] }} · {{ $ticket->benefitRemaining($index) }} / {{ $benefit['quantity'] }}</li>@endforeach</ul>@endif
@if($owner)<p>{{ __('tickets.owner_notice') }}</p><p>{{ __('tickets.sms') }} : {{ $ticket->messages()->latest()->first()?->status ? __('tickets.sms_'.$ticket->messages()->latest()->first()->status) : __('tickets.no_sms') }}</p><details><summary>{{ __('tickets.details') }}</summary><p class="preserve-lines">{{ $ticket->terms_snapshot }}</p></details>@if($ticket->channel==='card'&&$ticket->status==='pending')<form method="post" action="{{ \Illuminate\Support\Facades\URL::temporarySignedRoute('ticket.pay',now()->addMinutes(30),['ticket'=>$ticket->public_id]) }}">@csrf<button class="qapas-button">{{ __('tickets.pay') }}</button></form>@endif
@if($ticket->valid() && $ticket->includes_admission)
@foreach(\App\Models\PlantingSession::where('event_project_id',$ticket->plan->event_project_id)->where('is_public',true)->get() as $session)
@php($tree=$session->slots()->where('event_ticket_id',$ticket->id)->first())
@if($tree)<p>{{ $session->name }} · {{ $tree->tree_code }} · {{ $tree->status }}</p>@if($tree->thanks_consented_at)<form method="post" action="{{ \Illuminate\Support\Facades\URL::temporarySignedRoute('planting.unlist',now()->addMinutes(30),['ticket'=>$ticket->public_id,'slot'=>$tree->public_id]) }}">@csrf<button>{{ __('tickets.unlist') }} · {{ $tree->tree_code }}</button></form>@endif
@elseif($session->ready())<form class="event-form" method="post" action="{{ \Illuminate\Support\Facades\URL::temporarySignedRoute('planting.reserve',now()->addMinutes(30),['ticket'=>$ticket->public_id]) }}">@csrf<input type="hidden" name="session" value="{{ $session->public_id }}"><p>{{ $session->name }} · {{ app()->getLocale()==='pt'?'Um slot = uma árvore, conforme disponibilidade.':'Un créneau = un arbre, selon disponibilité.' }}</p><label><input type="checkbox" name="thanks" value="1">{{ app()->getLocale()==='pt'?'Quero aparecer nos agradecimentos (opcional)':'Je souhaite figurer dans les remerciements (facultatif)' }}</label><label>{{ __('tickets.public_name') }}<input name="public_name" maxlength="80"></label><button>{{ app()->getLocale()==='pt'?'Reservar a minha árvore':'Réserver mon arbre' }}</button></form>@endif
@endforeach @endif
@if($ticket->public_listing)<form method="post" action="{{ \Illuminate\Support\Facades\URL::temporarySignedRoute('ticket.unlist',now()->addMinutes(30),['ticket'=>$ticket->public_id]) }}">@csrf<button>{{ __('tickets.unlist') }}</button></form>@endif @endif
@if(auth('admin')->user()?->is_active)<p><a href="{{ route('ticket.control',['ticket'=>$ticket->public_id]) }}">Contrôle QAPAS →</a></p>@endif</section></div></div></x-layout>