<?php
namespace App\Domain\Procurement;
use App\Models\{ActivityMaterial,BudgetLine,SiteNeed,CostConsultation,EventProject,SupplierQuote};
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
final class Consultations {
 public function project(?Model $target): ?EventProject {return match(true){$target instanceof BudgetLine=>$target->scenario?->eventProject,$target instanceof ActivityMaterial=>$target->activity?->eventProject,$target instanceof SiteNeed=>$target->siteFeature?->eventProject,default=>null};}
 public function quantity(Model $target): ?int {return match(true){$target instanceof BudgetLine=>$target->forecast_quantity,$target instanceof ActivityMaterial=>$target->quantity===null?null:$target->quantity*($target->basis==='per_run'?$target->activity->planned_runs:1),$target instanceof SiteNeed=>$target->quantity===null?null:($target->basis==='per_day'?($target->siteFeature->eventProject->launchScenario()?->event_days?$target->quantity*$target->siteFeature->eventProject->launchScenario()->event_days:null):$target->quantity),default=>null};}
 public function ensure(Model $target): CostConsultation {
  $p=$this->project($target);abort_unless($p,422);
  // Shared filming is one consultation on its common cost, not a repeated request per challenge.
  if($target instanceof ActivityMaterial&&filled($target->shared_cost_key)){$common=$p->launchScenario()?->budgetLines()->where('costing_key',$target->shared_cost_key)->where('kind','cost')->first();if(!$common)throw ValidationException::withMessages(['cost'=>'Créer d’abord le poste commun correspondant.']);return $this->ensure($common);}
  return CostConsultation::firstOrCreate(['costable_type'=>$target::class,'costable_id'=>$target->id],$this->definition($target));
 }
 public function definition(Model $target): array {
  $p=$this->project($target);abort_unless($p,422);
  if($target instanceof BudgetLine&&($target->kind!=='cost'||$target->superseded_by_id))throw ValidationException::withMessages(['cost'=>'Choisir une dépense active.']);
  $dates=$p->starts_at?$p->starts_at->format('d/m/Y').' – '.$p->ends_at?->format('d/m/Y'):'a confirmar / à confirmer';$q=$this->quantity($target);$quantity=$q===null?'a confirmar / à préciser':(string)$q;$unit=$target->unit??'unidade';$name=$target->name;
  $extraPt="Solicitamos o detalhe de aluguer/compra/cedência, transporte de ida e recolha, montagem, IVA, caução, seguros, exclusões, disponibilidade, prazo e validade. Identificar separadamente eventual desconto ou apoio em espécie, bem como as contrapartidas propostas. Esta consulta não constitui adjudicação, reserva nem promessa de publicidade.";
  $extraFr="Merci de distinguer achat/location/prêt, livraison et reprise, montage, IVA, caution, assurance, exclusions, disponibilité, échéances et validité. Identifier séparément tout geste commercial ou apport en nature et ses contreparties proposées. Cette consultation ne vaut ni commande, ni réservation, ni promesse de publicité.";
  if($target instanceof ActivityMaterial||str_contains(mb_strtolower($name),'rétro')||str_contains(mb_strtolower($name),'répétition')){$extraPt.=" Prever separadamente o fim de semana de ensaios com voluntários e os dias do evento: períodos, equipamento, operador habilitado, combustível, transporte e supervisão. Não pressupomos utilização gratuita nem autorização para demonstrações; confirmar por escrito as condições.";$extraFr.=" Distinguer le week-end de répétition avec volontaires des jours d’événement : périodes, matériel, opérateur qualifié, carburant, transport et supervision. Toute mise à disposition et toute utilisation en démonstration restent à convenir par écrit.";}
  if(str_contains(mb_strtolower($name),'gobelet')||str_contains(mb_strtolower($name),'bols')){$extraPt.=" Indicar a declaração de conformidade para contacto alimentar, temperaturas e durações de contacto autorizadas, compatibilidade com álcool, sopa quente e vinho quente, ciclos de lavagem, impressão, prova gráfica e entrega em Portugal. Para os copos, comparar 250 e 1 000 unidades sem extrapolar o preço. Distinguir os recipientes para sopa e respetivas colheres.";$extraFr.=" Fournir la déclaration de conformité au contact alimentaire, températures et durées admises, compatibilité alcool/soupe/vin chaud, lavages, impression, BAT et livraison au Portugal. Pour les gobelets, comparer 250 et 1 000 pièces. Distinguer bols à soupe et cuillères.";}
  if($target instanceof BudgetLine&&(str_starts_with($target->costing_key??'','cabin-build-')||\App\Models\CabinProject::where('cost_line_id',$target->id)->exists())){$extraFr.=" Le raccord d’échafaudage est la pièce maîtresse : préciser les types, références, état, quantités et compatibilité avec les tubes de démolition (diamètres, épaisseurs, longueurs et état à relever). Chiffrer la préparation, ligatures en sisal/fibre naturelle adaptée, main-d’œuvre, montage et démontage, séparément des transports mutualisés. Valider un prototype de 2,40 m de côté avant série ; aucun dimensionnement ni étanchéité du plessis présumés. Un soutien en raccords ne vaut pas versement financier.";$extraPt.=" A abraçadeira de andaime é a peça central: indicar tipos, referências, estado, quantidades e compatibilidade com os tubos recuperados de demolições (medidas e estado a verificar). Orçamentar preparação, ligações em sisal/fibra natural adequada, mão de obra, montagem e desmontagem, separando o transporte partilhado. Validar um protótipo de 2,40 m de lado antes da série; não presumimos resistência estrutural nem impermeabilidade do entrançado. Apoio em material não é receita monetária.";}
  if($target instanceof BudgetLine&&$target->costing_key==='cabins-shredder-purchase'){
   $extraFr="Nous sollicitons un devis d’achat d’un broyeur pour QAPAS, financé par l’initiative. Matériaux : mimosa et cannes, jusqu’à 60 mm de diamètre. Confirmer l’aptitude réelle aux deux matériaux, leurs conditions d’humidité/séchage, le débit utile, les protections, l’entraînement, la garantie, l’entretien et la disponibilité des pièces. Détailler prix TTC, IVA, livraison, mise en service, formation et délai. Opérateur, carburant et consommables sont chiffrés séparément. Distinguer tout apport ou remise documentés ; cette demande ne vaut ni commande ni financement acquis.";
   $extraPt="Solicitamos orçamento de compra de um triturador para a QAPAS, financiado pela iniciativa. Materiais: mimosa e canas, até 60 mm de diâmetro. Confirmar aptidão real para ambos, condições de humidade/secagem, rendimento útil, proteções, acionamento, garantia, manutenção e peças. Discriminar preço com IVA, taxa de IVA, entrega, colocação em serviço, formação e prazo. Operador, combustível e consumíveis são orçamentados à parte. Identificar apoios ou descontos documentados; este pedido não constitui encomenda nem financiamento confirmado.";
  }
  if($target instanceof ActivityMaterial&&str_starts_with($name,'Pince fermante')){
   $extraFr.=" Option achat de pince fermante ; repère communiqué DANWIWEE B0DYMYH4FF, 279,99 €, non vérifié. Confirmer la compatibilité avec la machine proposée (axes, attache, masse, commande/hydraulique, ouverture), la notice et la possibilité de l’essayer sur les œufs. Proposer en priorité une pince déjà compatible louée/prêtée avec la mini-rétro, sans adaptation sur mesure ; ne pas facturer deux accessoires.";
   $extraPt.=" Opção de compra de pinça; referência comunicada DANWIWEE B0DYMYH4FF, 279,99 €, não verificada. Confirmar compatibilidade com a máquina (eixos, engate, massa, comando/hidráulica, abertura), manual e ensaio com ovos. Preferir pinça compatível já incluída no aluguer/empréstimo da mini-escavadora, sem adaptação por medida nem acessório duplicado.";
  }
  if($target instanceof BudgetLine&&$target->costing_key==='stands-shredder-rental'){
   $extraFr.=" Location une journée REMO, 100 € indiqués par le porteur, non un devis reçu. Confirmer capacité et débit sur mimosa/cannes de 60 mm maximum, prise/restitution, transport, caution, entretien et carburant admis (20 L SP98 maximum envisagés). Séparer les frais déjà comptés ailleurs. Aucun achat de broyeur demandé.";
   $extraPt.=" Aluguer REMO por um dia, 100 € indicados pelo promotor, sem orçamento recebido. Confirmar capacidade e rendimento para mimosa/canas até 60 mm, levantamento/devolução, transporte, caução, manutenção e combustível autorizado (máximo previsto de 20 L SP98). Não se solicita compra do triturador.";
  }
  if($target instanceof BudgetLine&&str_starts_with($target->costing_key??'','wc')){
   $extraFr.=" Consulter pour 500 personnes au pic, deux jours les 12–13 décembre 2026, 10–22 h, bar et soupe. Hypothèse à confirmer : sept cabines standard et une accessible, deux lave-mains, entretien/vidange intermédiaire et livraison/reprise. Préciser effectif cumulé admis, eau/savon/papier, nettoyage pendant le service, accès camion et solution eaux grises. Fournir un devis global ventilé pour ne compter aucun service deux fois ; sans fosse temporaire construite.";
   $extraPt.=" Consultar para pico de 500 pessoas, 12–13 dezembro 2026, 10–22 h, bar e sopa. Hipótese a confirmar: sete cabines normais e uma acessível, dois lava-mãos, limpeza/esvaziamento intermédio e transporte/recolha. Indicar lotação acumulada, água/sabão/papel, limpeza durante o serviço, acesso camião e águas cinzentas. Orçamento global discriminado, sem serviços duplicados nem fossa temporária construída.";
  }
  if($target instanceof BudgetLine&&(str_starts_with($target->costing_key??'','stand-extension-')||$target->costing_key==='stands-electric-boxes')){
   $extraFr.=" Liaison maximale 50 m, limite individuelle demandée 6 A/230 V. Comparer longueur réelle et lot complet, coffrets six sorties avec protections appropriées, alimentation amont, terre, chute de tension et traversées. Une prise 16 A n’est pas une protection individuelle 6 A. Réseau et groupe 6 kVA déclarés, simultanéité non validée. Pas de supplément facturé à l’exposant pour cette liaison de base.";
   $extraPt.=" Ligação até 50 m, limite individual pretendido 6 A/230 V. Comparar comprimentos reais e lote completo, quadros de seis saídas com proteções adequadas, alimentação, terra, queda de tensão e atravessamentos. Uma tomada 16 A não limita individualmente a 6 A. Rede e gerador declarado 6 kVA, simultaneidade por validar. Ligação base incluída no preço do stand.";
  }
  if(str_contains(mb_strtolower($name),'welcome pack')){$extraFr.=" Joindre la répartition actuelle par taille du welcome pack. Demander le prix des pièces imprimées, de la création/BAT et de la livraison séparément, sans doublon. Confirmer le guide de tailles, le modèle, les marquages devant/dos, le délai et les conditions d’échange. Les 20 % de réserve sont déjà inclus dans la quantité, ne pas les ajouter à nouveau.";$extraPt.=" Juntar a distribuição atual por tamanho do welcome pack. Separar peças impressas, criação/prova gráfica e transporte, sem duplicar custos. Confirmar tamanhos, modelo, impressão frente/costas, prazo e trocas. A quantidade já inclui 20% de reserva; não acrescentar outra vez.";}
  return ['event_project_id'=>$p->id,'name'=>$name,'subject_pt'=>'Pedido de orçamento / parceria — '.$name,'subject_fr'=>'Demande de devis / partenariat — '.$name,'body_pt'=>"Bom dia,\n\nA QAPAS está a preparar Os Jogos do Agricultor, um encontro entre freguesias em torno de desafios lúdicos e saberes agrícolas.\nDatas: $dates. Local: ".($p->venue?:'a confirmar').".\nNecessidade: $name. Quantidade prevista: $quantity $unit.\n\n$extraPt\n\nAgradecemos uma proposta discriminada, com a referência deste pedido.\nCom os melhores cumprimentos,\nQAPAS\n".(config('events.contact_email')?:'[contacto a completar]'),'body_fr'=>"Bonjour,\n\nQAPAS prépare Os Jogos do Agricultor, une rencontre entre freguesias autour de défis ludiques et des savoir-faire agricoles.\nDates : $dates. Lieu : ".($p->venue?:'à confirmer').".\nBesoin : $name. Quantité prévue : $quantity $unit.\n\n$extraFr\n\nMerci de nous adresser une offre détaillée en rappelant cette demande.\nCordialement,\nQAPAS\n".(config('events.contact_email')?:'[contact à compléter]')];
 }
 public function synchronize(): int {
  $count=0;foreach(EventProject::all() as $p){$s=$p->launchScenario();if(!$s)continue;foreach($s->budgetLines()->where('kind','cost')->where('forecast_quantity','>',0)->get() as $l){$this->ensure($l);$count++;}foreach($s->includedActivities as $a)foreach($a->materials as $m){$this->ensure($m);$count++;}foreach($s->includedFeatures as $f)foreach($f->needs as $n){$this->ensure($n);$count++;}}return $count;
 }
 // Legacy quotations keep their original wording; one construction unit is still one stand.
 private function canonicalUnit(?string $unit): ?string {return in_array($unit,['cabane','cabana'],true)?'stand':$unit;}
 public function apply(SupplierQuote $quote): void {
  abort_unless(auth('admin')->user()?->is_active,403);
  DB::transaction(function()use($quote){$q=SupplierQuote::lockForUpdate()->findOrFail($quote->id);$c=$q->consultation;$target=$c->costable()->lockForUpdate()->firstOrFail();$quantity=$this->quantity($target);
   if($q->applied_at)return;
   if(!$q->received_at||$q->received_at->isFuture()||($q->valid_until&&$q->valid_until->copy()->endOfDay()->isPast())||blank($q->document_reference)||$q->unit_gross_cents===null||$q->vat_basis_points===null||$q->deposit_cents===null||$quantity===null||$q->quantity!==$quantity||$this->canonicalUnit($q->unit)!==$this->canonicalUnit($target->unit))throw ValidationException::withMessages(['quote'=>'Vérifier date, pièce, unité, quantité identique, prix TTC, IVA et caution. Les variantes restent comparables sans être appliquées.']);
   if($q->deposit_cents>0)throw ValidationException::withMessages(['quote'=>'Cette offre comporte une caution. Prévoir son financement et sa restitution séparément avant de reprendre manuellement le prix ; aucune caution n’est assimilée à un coût ni oubliée dans la trésorerie.']);
   if($q->delivery_cents!==0||$q->other_cents!==0)throw ValidationException::withMessages(['quote'=>'Demander un prix tout compris, ou décomposer livraison et frais dans leurs postes avant reprise : pas de frais annexes oubliés.']);
   if($target instanceof BudgetLine&&($target->committed_quantity||$target->paid_quantity||$target->superseded_by_id))throw ValidationException::withMessages(['quote'=>'Cette ligne possède déjà des engagements ou règlements, ou a été écartée. Traiter son avenant séparément.']);
   $target->update(['unit_gross_cents'=>$q->unit_gross_cents,'vat_basis_points'=>$q->vat_basis_points,'pricing_status'=>'quoted','price_checked_at'=>today()->toDateString(),'price_source'=>'Devis '.$q->supplier.' / '.$q->reference.' · '.$q->document_reference.' · '.$q->conditions.' · Caution séparée : '.$q->deposit_cents.' centimes. Reçu, sans commande ni paiement.']);$q->update(['applied_at'=>now(),'applied_by'=>auth('admin')->id()]);
  },3);
 }
}
