<?php
namespace App\Domain\Procurement;
use App\Models\{ActivityMaterial,BudgetLine,SiteNeed,CostConsultation,EventProject,SupplierQuote};
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
final class Consultations {
 public function project(?Model $target): ?EventProject {return match(true){$target instanceof BudgetLine=>$target->scenario?->eventProject,$target instanceof ActivityMaterial=>$target->activity?->eventProject,$target instanceof SiteNeed=>$target->siteFeature?->eventProject,default=>null};}
 public function quantity(Model $target): ?int {return match(true){$target instanceof BudgetLine=>$target->forecast_quantity,$target instanceof ActivityMaterial=>$target->quantity===null?null:$target->quantity*($target->basis==='per_run'?$target->activity->planned_runs:1),$target instanceof SiteNeed=>$target->quantity===null?null:($target->basis==='per_day'?($target->siteFeature->eventProject->launchScenario()?->event_days?$target->quantity*$target->siteFeature->eventProject->launchScenario()->event_days:null):$target->quantity),default=>null};}
 public function ensure(Model $target): CostConsultation {
  $p=$this->project($target);abort_unless($p,422);
  // Shared filming is one consultation on its common cost, not a repeated request per challenge.
  if($target instanceof ActivityMaterial&&filled($target->shared_cost_key)){$common=$p->launchScenario()?->budgetLines()->where('costing_key',$target->shared_cost_key)->where('kind','cost')->first();if(!$common)throw ValidationException::withMessages(['cost'=>'Créer d’abord le poste commun correspondant.']);return $this->ensure($common);}
  if($target instanceof BudgetLine&&($target->kind!=='cost'||$target->superseded_by_id))throw ValidationException::withMessages(['cost'=>'Choisir une dépense active.']);
  $dates=$p->starts_at?$p->starts_at->format('d/m/Y').' – '.$p->ends_at?->format('d/m/Y'):'a confirmar / à confirmer';$q=$this->quantity($target);$quantity=$q===null?'a confirmar / à préciser':(string)$q;$unit=$target->unit??'unidade';$name=$target->name;
  $extraPt="Solicitamos o detalhe de aluguer/compra/cedência, transporte de ida e recolha, montagem, IVA, caução, seguros, exclusões, disponibilidade, prazo e validade. Identificar separadamente eventual desconto ou apoio em espécie, bem como as contrapartidas propostas. Esta consulta não constitui adjudicação, reserva nem promessa de publicidade.";
  $extraFr="Merci de distinguer achat/location/prêt, livraison et reprise, montage, IVA, caution, assurance, exclusions, disponibilité, échéances et validité. Identifier séparément tout geste commercial ou apport en nature et ses contreparties proposées. Cette consultation ne vaut ni commande, ni réservation, ni promesse de publicité.";
  if($target instanceof ActivityMaterial||str_contains(mb_strtolower($name),'rétro')||str_contains(mb_strtolower($name),'répétition')){$extraPt.=" Prever separadamente o fim de semana de ensaios com voluntários e os dias do evento: períodos, equipamento, operador habilitado, combustível, transporte e supervisão. Não pressupomos utilização gratuita nem autorização para demonstrações; confirmar por escrito as condições.";$extraFr.=" Distinguer le week-end de répétition avec volontaires des jours d’événement : périodes, matériel, opérateur qualifié, carburant, transport et supervision. Toute mise à disposition et toute utilisation en démonstration restent à convenir par écrit.";}
  if(str_contains(mb_strtolower($name),'gobelet')||str_contains(mb_strtolower($name),'bols')){$extraPt.=" Indicar a declaração de conformidade para contacto alimentar, temperaturas e durações de contacto autorizadas, compatibilidade com álcool, sopa quente e vinho quente, ciclos de lavagem, impressão, prova gráfica e entrega em Portugal. Para os copos, comparar 250 e 1 000 unidades sem extrapolar o preço. Distinguir os recipientes para sopa e respetivas colheres.";$extraFr.=" Fournir la déclaration de conformité au contact alimentaire, températures et durées admises, compatibilité alcool/soupe/vin chaud, lavages, impression, BAT et livraison au Portugal. Pour les gobelets, comparer 250 et 1 000 pièces. Distinguer bols à soupe et cuillères.";}
  if(str_contains(mb_strtolower($name),'welcome pack')){$extraFr.=" Joindre la répartition actuelle par taille du welcome pack. Demander le prix des pièces imprimées, de la création/BAT et de la livraison séparément, sans doublon. Confirmer le guide de tailles, le modèle, les marquages devant/dos, le délai et les conditions d’échange. Les 20 % de réserve sont déjà inclus dans la quantité, ne pas les ajouter à nouveau.";$extraPt.=" Juntar a distribuição atual por tamanho do welcome pack. Separar peças impressas, criação/prova gráfica e transporte, sem duplicar custos. Confirmar tamanhos, modelo, impressão frente/costas, prazo e trocas. A quantidade já inclui 20% de reserva; não acrescentar outra vez.";}
  return CostConsultation::firstOrCreate(['costable_type'=>$target::class,'costable_id'=>$target->id],['event_project_id'=>$p->id,'name'=>$name,'subject_pt'=>'Pedido de orçamento / parceria — '.$name,'subject_fr'=>'Demande de devis / partenariat — '.$name,'body_pt'=>"Bom dia,\n\nA QAPAS está a preparar Os Jogos do Agricultor, um encontro entre freguesias em torno de desafios lúdicos e saberes agrícolas.\nDatas: $dates. Local: ".($p->venue?:'a confirmar').".\nNecessidade: $name. Quantidade prevista: $quantity $unit.\n\n$extraPt\n\nAgradecemos uma proposta discriminada, com a referência deste pedido.\nCom os melhores cumprimentos,\nQAPAS\n".(config('events.contact_email')?:'[contacto a completar]'),'body_fr'=>"Bonjour,\n\nQAPAS prépare Os Jogos do Agricultor, une rencontre entre freguesias autour de défis ludiques et des savoir-faire agricoles.\nDates : $dates. Lieu : ".($p->venue?:'à confirmer').".\nBesoin : $name. Quantité prévue : $quantity $unit.\n\n$extraFr\n\nMerci de nous adresser une offre détaillée en rappelant cette demande.\nCordialement,\nQAPAS\n".(config('events.contact_email')?:'[contact à compléter]')]);
 }
 public function synchronize(): int {
  $count=0;foreach(EventProject::all() as $p){$s=$p->launchScenario();if(!$s)continue;foreach($s->budgetLines()->where('kind','cost')->get() as $l){$this->ensure($l);$count++;}foreach($s->includedActivities as $a)foreach($a->materials as $m){$this->ensure($m);$count++;}foreach($s->includedFeatures as $f)foreach($f->needs as $n){$this->ensure($n);$count++;}}return $count;
 }
 public function apply(SupplierQuote $quote): void {
  abort_unless(auth('admin')->user()?->is_active,403);
  DB::transaction(function()use($quote){$q=SupplierQuote::lockForUpdate()->findOrFail($quote->id);$c=$q->consultation;$target=$c->costable()->lockForUpdate()->firstOrFail();$quantity=$this->quantity($target);
   if($q->applied_at)return;
   if(!$q->received_at||$q->received_at->isFuture()||($q->valid_until&&$q->valid_until->copy()->endOfDay()->isPast())||blank($q->document_reference)||$q->unit_gross_cents===null||$q->vat_basis_points===null||$q->deposit_cents===null||$quantity===null||$q->quantity!==$quantity||$q->unit!==$target->unit)throw ValidationException::withMessages(['quote'=>'Vérifier date, pièce, unité, quantité identique, prix TTC, IVA et caution. Les variantes restent comparables sans être appliquées.']);
   if($q->deposit_cents>0)throw ValidationException::withMessages(['quote'=>'Cette offre comporte une caution. Prévoir son financement et sa restitution séparément avant de reprendre manuellement le prix ; aucune caution n’est assimilée à un coût ni oubliée dans la trésorerie.']);
   if($q->delivery_cents!==0||$q->other_cents!==0)throw ValidationException::withMessages(['quote'=>'Demander un prix tout compris, ou décomposer livraison et frais dans leurs postes avant reprise : pas de frais annexes oubliés.']);
   if($target instanceof BudgetLine&&($target->committed_quantity||$target->paid_quantity||$target->superseded_by_id))throw ValidationException::withMessages(['quote'=>'Cette ligne possède déjà des engagements ou règlements, ou a été écartée. Traiter son avenant séparément.']);
   $target->update(['unit_gross_cents'=>$q->unit_gross_cents,'vat_basis_points'=>$q->vat_basis_points,'pricing_status'=>'quoted','price_checked_at'=>today()->toDateString(),'price_source'=>'Devis '.$q->supplier.' / '.$q->reference.' · '.$q->document_reference.' · '.$q->conditions.' · Caution séparée : '.$q->deposit_cents.' centimes. Reçu, sans commande ni paiement.']);$q->update(['applied_at'=>now(),'applied_by'=>auth('admin')->id()]);
  },3);
 }
}
