<?php
namespace Tests\Feature;
use App\Models\{Admin,EventProject,PresalePlan,Distributor,EventTicket,RegistrationCampaign,Prospect,ProspectVisit,Idea,PressRelease,Sponsorship,PublicationDispatch,PlantingSession,PlantingSlot,SiteFeature};
use App\Domain\Tickets\{Ticketing,TicketBenefits};
use App\Domain\Promotion\PromotionPipeline;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\{DB,Http,Mail,URL};
use Illuminate\Validation\ValidationException;
use Tests\TestCase;
class AdvantagesMobilizationTest extends TestCase {
 use RefreshDatabase;
 private function admin(): void {$this->actingAs(Admin::firstOrCreate(['email'=>'advantages@example.test'],['name'=>'Admin','password'=>'long-advantages-password']),'admin');}
 private function invalid(callable $f): void {try{$f();$this->fail('Expected validation error');}catch(ValidationException){$this->assertTrue(true);}}
 private function plan(): PresalePlan {
  $this->admin();config(['presales.enabled'=>true,'events.privacy_ready'=>true,'events.organizer_name'=>'QAPAS','events.contact_email'=>'info@example.test','registration.live'=>false]);
  $p=EventProject::create(['name'=>'Games','slug'=>'games','is_public'=>true,'venue'=>'Site','capacity'=>500,'starts_at'=>'2026-12-12 09:00:00','ends_at'=>'2026-12-13 21:00:00']);foreach($p->requirements as $r)$r->update(['status'=>'approved','evidence'=>'Reviewed','reviewed_by'=>'Professional','reviewed_at'=>now()]);
  return PresalePlan::create(['event_project_id'=>$p->id,'name'=>'Ticket commun','kind'=>'admission','unified_benefits'=>true,'terms_version'=>'v1','terms_fr'=>'Entrée et soupe','terms_pt'=>'Entrada e sopa','refund_fr'=>'Remboursement','refund_pt'=>'Reembolso','split_evidence'=>'Four allocations','billing_procedure'=>'Validated invoicing','approval_evidence'=>'Validated conditions','vat_basis_points'=>0,'capacity'=>100,'closes_at'=>'2026-12-01 23:00:00','benefits'=>[['label_fr'=>'Soupe','label_pt'=>'Sopa','quantity'=>1]],'benefit_cost_cents'=>200,'benefit_evidence'=>'Soup capacity and supplier cost reserved','sales_strategy'=>'presale_discount','early_until'=>'2026-10-30 23:59:59','price_cents'=>1000,'full_price_cents'=>1200,'pricing_evidence'=>'Approved launch and ordinary prices','is_open'=>true]);
 }
 private function relay(PresalePlan $p): Distributor {$stand=$p->eventProject->stands()->create(['name'=>'Village','kind'=>'village','freguesia'=>'Souto','is_public'=>true]);$partner=$stand->partners()->create(['name'=>'Café','relay_slot'=>1,'status'=>'active','mission'=>'Distribution','evidence'=>'Signed']);$d=Distributor::create(['stand_partner_id'=>$partner->id,'name'=>'Café','email'=>'cafe@example.test','password'=>'long-relay-password','contract_evidence'=>'Mandate','is_active'=>true]);$this->actingAs($d,'relay');return $d;}
 private function issue(PresalePlan $p,Distributor $d,array $extra=[]): EventTicket {return app(Ticketing::class)->issue($p,array_replace(['buyer_name'=>'Maria Private','phone'=>'+351912345678','terms_version'=>$p->terms_version,'quote_key'=>$p->quote()['key'],'channel'=>'cash','request_id'=>(string)\Illuminate\Support\Str::uuid()],$extra),$d);}
 private function paid(PresalePlan $p,Distributor $d,array $extra=[]): EventTicket {$t=$this->issue($p,$d,$extra);app(Ticketing::class)->settle($d,[$t->id],$t->expectedRemittance(),'bank-'.$t->id,'Receipt proof',now());return $t->fresh();}
 private function prospect(EventProject $p,string $key='p'): Prospect {return Prospect::create(['event_project_id'=>$p->id,'source_key'=>$key,'entity_key'=>$key,'name'=>'Prospect '.$key,'category'=>'Supplier','municipality'=>'Covilhã','sector'=>'Souto','tour'=>'T0','address'=>'Professional address','source'=>'Business website','checked_at'=>today()]);}
 public function test_upgrade_data_groups_finance_and_three_private_posters(): void {
  $this->seed();$p=EventProject::first();$this->assertTrue(PresalePlan::first()->unified_benefits);$this->assertFalse(PresalePlan::first()->is_open);$this->assertSame(96731,\App\Models\CupPlan::first()->reference_net_cents);$this->assertSame(115110,$p->launchScenario()->budgetLines()->where('costing_key','cups-purchase')->first()->unit_gross_cents);$this->assertDatabaseCount('sponsorships',10);$this->assertDatabaseCount('planting_sessions',2);$this->assertDatabaseCount('planting_slots',0);$this->assertSame(0,Prospect::where('municipality','À confirmer')->count());$this->assertSame(0,\App\Models\Offer::whereNull('prospect_type')->count());
  $s=Sponsorship::first();$s->update(['pitch'=>'Custom negotiation']);$p->launchScenario()->budgetLines()->where('costing_key','cups-purchase')->first()->update(['unit_gross_cents'=>120000]);$this->seed();$this->assertSame('Custom negotiation',$s->fresh()->pitch);$this->assertSame(120000,$p->launchScenario()->budgetLines()->where('costing_key','cups-purchase')->first()->unit_gross_cents);
  $this->get(route('campaign.poster',['poster'=>'01-teaser']))->assertForbidden();$this->admin();foreach(['01-teaser','02-candidatures','03-programme'] as $key)$this->get(route('campaign.poster',['poster'=>$key]))->assertOk()->assertHeader('Content-Type','image/webp');
 }
 public function test_visits_are_historical_and_schedule_dashboard_followups(): void {
  $p=$this->plan();$prospect=$this->prospect($p->eventProject);$visit=$prospect->visits()->create(['visited_at'=>now()->subHour(),'contact_name'=>'Reception','email'=>'office@example.test','contact_source'=>'Professional contact given during visit','feedback'=>'Interested; asks for costs','outcome'=>'qualified','next_action'=>'Send approved proposal','followup_at'=>now()->addDay()]);$this->assertSame('office@example.test',$prospect->fresh()->email);$this->assertSame('qualified',$prospect->fresh()->status);
  $this->get(\App\Filament\Pages\Dashboard::getUrl())->assertOk()->assertSee('Send approved proposal')->assertSee('Covilhã');$this->invalid(fn()=>$visit->update(['feedback'=>'Overwrite']));$this->invalid(fn()=>$prospect->visits()->create(['visited_at'=>now()->addDay(),'feedback'=>'Future visit','outcome'=>'contacted']));
  $prospect->visits()->create(['visited_at'=>now()->subDays(2),'feedback'=>'Earlier visit','outcome'=>'absent']);$this->assertSame('qualified',$prospect->fresh()->status);
 }
 public function test_native_filament_groups_tabs_and_all_new_forms_render(): void {
  $this->seed();$this->admin();foreach(['ActivityMaterial','Offer','Prospect','Sponsorship','PlantingSession','PlantingSlot','PublicationDispatch','PresalePlan','PressRelease'] as $name){$resource='App\\Filament\\Resources\\'.$name.'Resource';$this->get($resource::getUrl())->assertOk();if(!in_array($name,['PlantingSlot','PublicationDispatch']))\Livewire\Livewire::test($resource.'\\Pages\\ManageRecords')->mountAction('create')->assertHasNoActionErrors();}
  $tabs=\Livewire\Livewire::test(\App\Filament\Resources\ActivityMaterialResource\Pages\ManageRecords::class);$tabs->assertSee('Omelete Retro')->set('activeTab','teams')->assertSuccessful();$this->get(\App\Filament\Pages\CampaignPosters::getUrl())->assertOk();
  \Livewire\Livewire::test(\App\Filament\Resources\ProspectResource\Pages\ManageRecords::class)->mountAction(\Filament\Actions\Testing\TestAction::make('visit')->table(Prospect::first()))->assertHasNoActionErrors();
 }
 public function test_price_boundary_rejects_stale_form_and_preserves_prior_benefits(): void {
  $this->travelTo(\Carbon\Carbon::parse('2026-10-30 23:59:59'));$p=$this->plan();$d=$this->relay($p);$oldQuote=$p->quote();$early=$this->paid($p,$d);$this->assertSame(1000,$early->amount_cents);$this->assertSame(100,$early->relay_cents);$this->assertTrue($early->includes_admission);
  $this->travelTo(\Carbon\Carbon::parse('2026-10-31 00:00:00'));$this->invalid(fn()=>$this->issue($p,$d,['quote_key'=>$oldQuote['key']]));$late=$this->paid($p,$d);$this->assertSame(1200,$late->amount_cents);$this->assertSame(120,$late->junta_cents);$this->assertSame($early->benefits_snapshot,$late->benefits_snapshot);$this->assertSame(1000,$early->fresh()->amount_cents);
  $p->update(['bank_available_cents'=>5000,'refund_reserve_cents'=>0,'bank_evidence'=>'Bank statement']);$this->assertSame(400,$p->report()['benefit_reserve_cents']);$this->assertSame(920,$p->report()['available_cents']);
 }
 public function test_commission_reduction_is_an_alternative_and_does_not_reduce_junta(): void {
  $this->travelTo(\Carbon\Carbon::parse('2026-10-01'));$p=$this->plan();$this->invalid(fn()=>$p->update(['relay_changes_at'=>'2026-11-15','late_relay_basis_points'=>500]));$p->refresh();$p->update(['sales_strategy'=>'relay_stepdown','full_price_cents'=>null,'relay_changes_at'=>'2026-11-15 00:00:00','late_relay_basis_points'=>500]);$p->update(['is_open'=>true]);$d=$this->relay($p);$early=$this->paid($p,$d);$this->assertSame(100,$early->relay_cents);$this->travelTo(\Carbon\Carbon::parse('2026-11-15 00:00:00'));$late=$this->paid($p,$d);$this->assertSame(50,$late->relay_cents);$this->assertSame(100,$late->junta_cents);$this->assertSame(1000,$late->amount_cents);$this->assertSame(950,$late->expectedRemittance());
 }
 public function test_candidates_and_visitors_have_identical_entry_and_benefits_even_at_full_price(): void {
  $this->travelTo(\Carbon\Carbon::parse('2026-11-01'));$p=$this->plan();$d=$this->relay($p);$c=RegistrationCampaign::create(['event_project_id'=>$p->event_project_id,'name'=>'Candidates','unified_ticket_terms'=>true,'terms_version'=>'c1','terms_fr'=>'Même ticket','terms_pt'=>'Mesmo bilhete','refund_policy_fr'=>'Refund','refund_policy_pt'=>'Refund','billing_procedure'=>'Reviewed','validation_evidence'=>'Reviewed','vat_basis_points'=>0,'closes_at'=>'2026-11-20','is_open'=>true]);$visitor=$this->paid($p,$d);$candidate=$this->paid($p,$d,['candidate'=>true,'candidate_terms_version'=>'c1','expert_roles'=>['cook']]);$this->assertTrue($candidate->valid());$this->assertSame($visitor->kind,$candidate->kind);$this->assertSame($visitor->amount_cents,$candidate->amount_cents);$this->assertSame($visitor->benefits_snapshot,$candidate->benefits_snapshot);$this->assertSame(0,$candidate->candidate->credit_cents);app(Ticketing::class)->redeem($candidate,'Admission checked');$this->assertNotNull($candidate->fresh()->redeemed_at);
 }
 public function test_benefit_delivery_is_single_and_blocks_automatic_refund(): void {
  $p=$this->plan();$d=$this->relay($p);$t=$this->paid($p,$d);$id=(string)\Illuminate\Support\Str::uuid();app(TicketBenefits::class)->redeem($t,0,1,'Soup served',$id);app(TicketBenefits::class)->redeem($t,0,1,'Soup served',$id);$this->assertSame(0,$t->benefitRemaining(0));$this->assertDatabaseCount('ticket_benefit_redemptions',1);$this->invalid(fn()=>app(TicketBenefits::class)->redeem($t,0,1,'Again',(string)\Illuminate\Support\Str::uuid()));$this->invalid(fn()=>app(Ticketing::class)->refundCash($t,'Refund',100));auth('admin')->logout();$this->post(route('ticket.benefit',['ticket'=>$t->public_id]),['index'=>0,'quantity'=>1,'evidence'=>'Intrusion','operation'=>(string)\Illuminate\Support\Str::uuid()])->assertForbidden();
 }
 public function test_sponsorship_slots_are_finite_and_agreement_is_not_cash(): void {
  $p=$this->plan()->eventProject;for($i=1;$i<=3;$i++){$s=Sponsorship::create(['event_project_id'=>$p->id,'name'=>'Partner '.$i,'scope'=>'secondary','secondary_slot'=>$i,'purpose'=>$i===3?'cups':'general','sponsor_name'=>'Company '.$i,'cash_pledged_cents'=>100000,'agreement_evidence'=>'Signed','agreed_at'=>now(),'web_rights'=>'Web only','status'=>'agreed','is_public'=>true]);$this->assertTrue($s->agreed());$this->assertSame(0,$s->funding()['paid_cents']);}
  $this->invalid(fn()=>Sponsorship::create(['event_project_id'=>$p->id,'name'=>'Fourth','scope'=>'secondary','secondary_slot'=>4]));$this->invalid(fn()=>Sponsorship::create(['event_project_id'=>$p->id,'name'=>'Duplicate','scope'=>'secondary','secondary_slot'=>3,'sponsor_name'=>'Other','cash_pledged_cents'=>1,'agreement_evidence'=>'Signed','agreed_at'=>now(),'web_rights'=>'Web','status'=>'agreed']));$this->invalid(fn()=>$s->update(['print_approved_at'=>now()]));
 }
 private function release(EventProject $p): array {$idea=$p->ideas()->create(['name'=>'Junta agreed','status'=>'idea','hypothesis'=>'Local agreement supports the launch','experiment'=>'Obtain signed confirmation']);$r=$p->pressReleases()->create(['name'=>'New phase','title_pt'=>'Nova etapa','body'=>'Verified story','body_pt'=>'Notícia verificada','owner'=>'Editor','evidence'=>'Content approved','depends_on'=>[$idea->id],'auto_dispatch'=>true,'publication_version'=>'1','channels'=>['website','email','facebook','x'],'press_emails'=>['press@example.test'],'dispatch_authorization'=>'Publish these exact texts after the milestone','social_text_pt'=>'Uma nova etapa.','status'=>'approved']);return [$idea,$r];}
 public function test_promotion_waits_for_phase_publishes_website_once_and_blocks_unconfigured_external_channels(): void {
  Http::preventStrayRequests();Mail::fake();$p=$this->plan()->eventProject;[$idea,$r]=$this->release($p);app(PromotionPipeline::class)->tick();$this->assertDatabaseCount('publication_dispatches',0);$idea->update(['status'=>'validated','owner'=>'Organizer','evidence'=>'Junta signed']);$this->assertSame(1,app(PromotionPipeline::class)->tick());$this->assertTrue($r->fresh()->publiclyAvailable());$this->assertDatabaseCount('publication_dispatches',4);$this->assertSame(3,PublicationDispatch::where('status','blocked')->count());$this->assertSame(0,app(PromotionPipeline::class)->tick());Mail::assertNothingSent();
  $idea->update(['status'=>'idea']);$this->get(route('press.show',['project'=>$p->slug,'press'=>$r->public_id]))->assertNotFound();$this->invalid(fn()=>$r->fresh()->update(['body'=>'Changed without new version']));
 }
 public function test_social_publication_verifies_account_and_timeout_never_reposts(): void {
  $p=$this->plan()->eventProject;config(['app.url'=>'https://games.example.test','promotion.external_enabled'=>true,'promotion.account_evidence'=>'Official accounts verified','promotion.x_user_id'=>'42','promotion.x_user_token'=>'fixture']);URL::forceRootUrl('https://games.example.test');[$idea,$r]=$this->release($p);$r->update(['channels'=>['website','x']]);$r->update(['status'=>'approved']);$idea->update(['status'=>'validated','owner'=>'Organizer','evidence'=>'Agreed']);Http::preventStrayRequests();$postAttempts=0;Http::fake(['api.x.com/2/users/me'=>Http::response(['data'=>['id'=>'42']]),'api.x.com/2/tweets'=>function()use(&$postAttempts){$postAttempts++;throw new \Illuminate\Http\Client\ConnectionException('Timeout');}]);app(PromotionPipeline::class)->tick();$this->assertSame('unknown',PublicationDispatch::where('channel','x')->first()->status);$this->assertSame(1,$postAttempts);app(PromotionPipeline::class)->tick();$this->assertSame(1,$postAttempts);Http::assertSentCount(1);
 }
 public function test_planting_has_one_tree_per_ticket_per_day_and_real_private_coordinates(): void {
  $this->travelTo(\Carbon\Carbon::parse('2026-10-01'));$p=$this->plan();$d=$this->relay($p);$t=$this->paid($p,$d);$nursery=$this->prospect($p->eventProject);$quartel=SiteFeature::create(['event_project_id'=>$p->event_project_id,'name'=>'Quartel','category'=>'quartel','geometry'=>['type'=>'Polygon','coordinates'=>[[[-7.1,40.1],[-7,40.1],[-7,40.2],[-7.1,40.2],[-7.1,40.1]]]]]);$scenario=$p->eventProject->scenarios()->create(['name'=>'Budget']);$cost=$scenario->budgetLines()->create(['name'=>'One tree complete','kind'=>'cost','forecast_quantity'=>1,'unit_gross_cents'=>2000,'vat_basis_points'=>2300]);$s=PlantingSession::create(['event_project_id'=>$p->event_project_id,'name'=>'Closing','day_number'=>1,'starts_at'=>'2026-12-12 17:00:00','capacity'=>1,'trees_received'=>1,'quartel_id'=>$quartel->id,'nursery_prospect_id'=>$nursery->id,'budget_line_id'=>$cost->id,'receipt_evidence'=>'Delivered','supervisor'=>'Nursery expert','instructions_fr'=>'Briefing','instructions_pt'=>'Instruções','partner_agreement'=>'Signed','preparation_evidence'=>'Site ready','status'=>'ready','is_public'=>true]);app(\App\Domain\Planting\Planting::class)->generate($s);$slot=app(\App\Domain\Planting\Planting::class)->reserve($s,$t,'Maria');$this->assertSame($slot->id,app(\App\Domain\Planting\Planting::class)->reserve($s,$t)->id);$another=$this->paid($p,$d);$this->invalid(fn()=>app(\App\Domain\Planting\Planting::class)->reserve($s,$another));$this->invalid(fn()=>PlantingSession::create(['event_project_id'=>$p->event_project_id,'name'=>'Other day','day_number'=>2,'nursery_prospect_id'=>$nursery->id]));$this->invalid(fn()=>$slot->update(['latitude'=>41,'longitude'=>-8]));$slot->refresh();$this->travelTo(\Carbon\Carbon::parse('2026-12-12 17:30:00'));$slot->update(['species'=>'Olive','latitude'=>40.15,'longitude'=>-7.05,'status'=>'planted','planted_at'=>now(),'evidence'=>'Tree planted']);$this->assertFalse($slot->publicLocation());$this->get(route('planting.show',['project'=>'games']))->assertOk()->assertSee('Maria')->assertDontSee('40.15');$this->invalid(fn()=>app(Ticketing::class)->refundCash($t,'Already planted',100));
 }
}
