<?php
namespace Tests\Feature;
use App\Models\{Admin,EventProject,PresalePlan,Distributor,EventTicket,RegistrationCampaign,SiteInfrastructure,StandRequirement,OutreachVisit,PressRelease};
use App\Domain\Tickets\{Ticketing,TicketPayments,TicketSms};
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\{DB,Http,URL};
use Illuminate\Validation\ValidationException;
use Tests\TestCase;
class PresalesOutreachTest extends TestCase {
 use RefreshDatabase;
 private function admin(): Admin {$a=Admin::firstOrCreate(['email'=>'tickets@example.test'],['name'=>'Admin','password'=>'long-ticket-password']);$this->actingAs($a,'admin');return $a;}
 private function plan(string $slug='tickets',string $kind='support'): PresalePlan {
  $this->admin();config(['presales.enabled'=>true,'events.privacy_ready'=>true,'events.organizer_name'=>'QAPAS','events.contact_email'=>'info@example.test','registration.live'=>false,'registration.enabled'=>true,'registration.stripe_secret'=>'sk_test_fixture','registration.webhook_secret'=>'whsec_fixture']);
  $p=EventProject::create(['name'=>'Tickets','slug'=>$slug,'is_public'=>true,'venue'=>'Test site','capacity'=>300,'starts_at'=>now()->addDays(60),'ends_at'=>now()->addDays(61)]);foreach($p->requirements as $q)$q->update(['status'=>'approved','evidence'=>'Signed review','reviewed_by'=>'Reviewer','reviewed_at'=>now()]);
  return PresalePlan::create(['event_project_id'=>$p->id,'name'=>'Plan','kind'=>$kind,'terms_version'=>'v1','terms_fr'=>'Soutien facultatif','terms_pt'=>'Apoio facultativo','refund_fr'=>'Remboursement','refund_pt'=>'Reembolso','split_evidence'=>'Junta included within village 2 EUR','billing_procedure'=>'Verified invoicing','approval_evidence'=>'Signed conditions','vat_basis_points'=>0,'capacity'=>100,'closes_at'=>now()->addDays(20),'is_open'=>true]);
 }
 private function relay(PresalePlan $p,string $suffix='1'): Distributor {$stand=$p->eventProject->stands()->create(['name'=>'Village '.$suffix,'kind'=>'village','freguesia'=>'Village '.$suffix,'is_public'=>true]);$partner=$stand->partners()->create(['name'=>'Café '.$suffix,'relay_slot'=>1,'status'=>'active','mission'=>'Display, information and distribution','evidence'=>'Agreement']);$d=Distributor::create(['stand_partner_id'=>$partner->id,'name'=>'Relay '.$suffix,'email'=>'relay'.$suffix.'@example.test','password'=>'long-relay-password','contract_evidence'=>'Mandate with commission, cash, returns and data','is_active'=>true]);$this->actingAs($d,'relay');return $d;}
 private function ticket(PresalePlan $p,Distributor $d,array $extra=[]): EventTicket {return app(Ticketing::class)->issue($p,array_replace(['request_id'=>(string)\Illuminate\Support\Str::uuid(),'buyer_name'=>'Ana Private','email'=>'ana@example.test','phone'=>'+351912345678','public_listing'=>false,'terms_version'=>'v1','channel'=>'cash'], $extra),$d);}
 private function invalid(callable $action): void {try{$action();$this->fail('Expected validation error');}catch(ValidationException){$this->assertTrue(true);}}
 public function test_seed_is_additive_preserves_edits_and_does_not_fake_confirmed_site_or_prices(): void {
  $this->seed();$p=EventProject::first();$plan=PresalePlan::first();$this->assertFalse($plan->is_open);$this->assertNull($plan->vat_basis_points);$this->assertSame('2026-12-12',$p->proposed_start->toDateString());$this->assertNull($p->starts_at);$this->assertDatabaseCount('outreach_visits',7);$this->assertDatabaseCount('site_infrastructures',23);$this->assertDatabaseCount('event_tickets',0);
  $main=SiteInfrastructure::where('template_key','main-ls4x16')->first();$this->assertNull($main->amp_limit);$this->assertFalse($main->available());$this->assertSame('unknown',$main->phases);$this->assertSame('qapas_disposable',\App\Models\CupPlan::first()->soup_bowl_owner);$this->assertSame(881,$p->launchScenario()->budgetLines()->where('costing_key','soup-bowls')->first()->unit_gross_cents);
  $visit=OutreachVisit::first();$visit->update(['next_action'=>'My edited route']);$plan->update(['terms_fr'=>'My revised terms']);$this->seed();$this->assertSame('My edited route',$visit->fresh()->next_action);$this->assertSame('My revised terms',$plan->fresh()->terms_fr);$this->assertDatabaseCount('outreach_visits',7);$this->admin();app(\App\Domain\Planning\LaunchSequence::class)->validateOrder($p->ideas()->orderBy('sort_order')->pluck('id')->all());
 }
 public function test_press_create_and_edit_relationship_callbacks_use_builder_injection(): void {
  $this->seed();$this->admin();$page=\Livewire\Livewire::test(\App\Filament\Resources\PressReleaseResource\Pages\ManageRecords::class)->mountAction('create')->assertHasNoActionErrors();$page->fillForm(['event_project_id'=>EventProject::first()->id])->assertHasNoActionErrors();
  \Livewire\Livewire::test(\App\Filament\Resources\PressReleaseResource\Pages\ManageRecords::class)->mountAction(\Filament\Actions\Testing\TestAction::make('edit')->table(PressRelease::first()))->assertHasNoActionErrors();
 }
 public function test_relay_cash_receipt_only_validates_after_exact_qapas_receipt_and_queues_one_sms(): void {
  $p=$this->plan();$d=$this->relay($p);$t=$this->ticket($p,$d,['public_listing'=>true,'public_name'=>'Ana']);$this->assertFalse($t->valid());$this->assertSame(900,$t->expectedRemittance());$this->assertSame(100,$t->commission_retained_cents);$this->assertDatabaseCount('ticket_messages',0);
  $this->get($t->verifyUrl())->assertOk()->assertSee('EN ATTENTE')->assertDontSee('Ana Private')->assertDontSee('+351912345678');$this->get(route('tickets.list',['project'=>$p->eventProject->slug]))->assertDontSee('Ana');
  $this->invalid(fn()=>app(Ticketing::class)->settle($d,[$t->id],1000,'BANK-1','Proof',now()));$this->assertFalse($t->fresh()->valid());$settlement=app(Ticketing::class)->settle($d,[$t->id],900,'BANK-1','Counted and signed',now());$this->assertTrue($t->fresh()->valid());$this->assertSame(900,$settlement->received_cents);$this->assertDatabaseCount('ticket_messages',1);$this->invalid(fn()=>app(Ticketing::class)->settle($d,[$t->id],900,'BANK-2','Again',now()));
  $this->get($t->verifyUrl())->assertOk()->assertSee('CONFIRMÉ')->assertDontSee('Ana Private');$this->get(route('tickets.list',['project'=>$p->eventProject->slug]))->assertSee('Ana');
  $raw=DB::table('event_tickets')->where('id',$t->id)->value('phone');$this->assertNotSame('+351912345678',$raw);$this->assertStringContainsString('<svg',$t->qrSvg());
  $report=$p->report();$this->assertSame(1000,$report['gross_cents']);$this->assertSame(600,$report['qapas_before_vat_costs_cents']);$this->assertSame(100,$report['freguesias'][$t->stand_id]['junta_cents']);$this->assertSame(0,$report['available_cents']);$p->update(['bank_available_cents'=>900,'bank_evidence'=>'Bank proof','refund_reserve_cents'=>100]);$this->assertSame(500,$p->report()['available_cents']);
 }
 public function test_relay_cannot_confirm_cash_or_read_another_distributor_and_never_gets_admin(): void {
  $p=$this->plan();$d=$this->relay($p);$t=$this->ticket($p,$d);$other=$this->relay($p,'2');auth('admin')->logout();$this->get(route('relay.receipt',['ticket'=>$t->public_id]))->assertNotFound();$this->get(route('ticket.control',['ticket'=>$t->public_id]))->assertForbidden();
  $this->get(\App\Filament\Resources\EventTicketResource::getUrl())->assertRedirect();$this->expectException(\Symfony\Component\HttpKernel\Exception\HttpException::class);app(Ticketing::class)->settle($other,[$t->id],900,'X','No',now());
 }
 public function test_form_token_is_idempotent_and_status_url_never_validates_itself(): void {
  $p=$this->plan();$d=$this->relay($p);$id=(string)\Illuminate\Support\Str::uuid();$one=$this->ticket($p,$d,['request_id'=>$id]);$two=$this->ticket($p,$d,['request_id'=>$id]);$this->assertSame($one->id,$two->id);$this->assertDatabaseCount('event_tickets',1);$this->get($one->verifyUrl())->assertOk();$this->assertFalse($one->fresh()->valid());
 }
 public function test_cash_candidate_is_paid_once_with_reserved_shares_and_nonselected_credit(): void {
  $p=$this->plan();$d=$this->relay($p);$campaign=RegistrationCampaign::create(['event_project_id'=>$p->event_project_id,'name'=>'Experts','terms_version'=>'candidate-v1','terms_fr'=>'Terms','terms_pt'=>'Condições','refund_policy_fr'=>'Refund','refund_policy_pt'=>'Reembolso','vat_basis_points'=>0,'billing_procedure'=>'Invoices','validation_evidence'=>'Review','closes_at'=>now()->addDays(10),'is_open'=>true]);
  $t=$this->ticket($p,$d,['candidate'=>true,'email'=>null,'candidate_terms_version'=>'candidate-v1','expert_roles'=>['cook']]);$this->assertSame('',$t->candidate->interest->email);$this->assertNotNull($t->candidate);$this->assertFalse($t->candidate->isPaid());app(Ticketing::class)->settle($d,[$t->id],900,'CASH-1','Receipt',now());$this->assertTrue($t->fresh()->candidate->isPaid());
  $campaign->update(['bank_available_cents'=>900,'bank_evidence'=>'Proof','refund_reserve_cents'=>0]);$this->assertSame(600,$campaign->funding()['available_cents']);$this->assertSame(1000,$p->report()['candidate_credit_face_cents']);$this->travel(11)->days();$campaign->update(['vote_closed_at'=>now(),'vote_minutes_reference'=>'Signed ballot']);app(\App\Domain\Registration\RegistrationDecision::class)->record($t->fresh()->candidate,'not_selected','Result confirmed');$this->assertSame(1000,$t->fresh()->candidate->drinkCredit->face_cents);$this->assertDatabaseCount('event_tickets',1);
  $this->invalid(fn()=>app(\App\Domain\Registration\RegistrationPayments::class)->checkout($t->candidate));
 }
 public function test_card_webhook_rejects_bad_amount_and_is_idempotent_and_refunds_do_not_revive(): void {
  $p=$this->plan();$d=$this->relay($p);$t=$this->ticket($p,$d,['channel'=>'card']);Http::preventStrayRequests();Http::fake(['api.stripe.com/v1/checkout/sessions*'=>Http::response(['id'=>'cs_test_ticket','status'=>'open','url'=>'https://checkout.stripe.com/c/pay/test'])]);app(TicketPayments::class)->checkout($t);app(TicketPayments::class)->checkout($t->fresh());Http::assertSent(fn($request)=>$request->method()==='POST'&&$request->hasHeader('Idempotency-Key','ticket-'.$t->public_id.'-1')&&(int)$request['line_items'][0]['price_data']['unit_amount']===1000);
  $session=['id'=>'cs_test_ticket','payment_status'=>'paid','client_reference_id'=>$t->public_id,'metadata'=>['ticket'=>$t->public_id,'attempt'=>'1'],'amount_total'=>1000,'currency'=>'eur','livemode'=>false,'payment_intent'=>['id'=>'pi_ticket','latest_charge'=>['balance_transaction'=>['fee'=>40,'currency'=>'eur']]]];$event=['id'=>'evt_ticket','type'=>'checkout.session.completed','livemode'=>false,'data'=>['object'=>['id'=>'cs_test_ticket','metadata'=>['ticket'=>$t->public_id]]]];
  $send=function($event){$payload=json_encode($event);$stamp=time();return $this->call('POST','/payments/stripe/webhook',[],[],[],['CONTENT_TYPE'=>'application/json','HTTP_STRIPE_SIGNATURE'=>'t='.$stamp.',v1='.hash_hmac('sha256',$stamp.'.'.$payload,'whsec_fixture')],$payload);};
  Http::swap(new \Illuminate\Http\Client\Factory);Http::preventStrayRequests();Http::fake(['api.stripe.com/*'=>Http::sequence()->push(array_replace($session,['amount_total'=>999]))->push($session)->push($session)]);$send($event)->assertStatus(422);$this->assertFalse($t->fresh()->valid());$send($event)->assertOk();$send($event)->assertOk();$this->assertTrue($t->fresh()->valid());$this->assertDatabaseCount('ticket_messages',1);$this->assertSame(560,$p->report()['net_before_delivery_cents']);$this->assertSame(100,$p->report()['commission_card_due_cents']);app(Ticketing::class)->commissionPaid($t,'Bank transfer to relay');$this->assertSame(0,$p->report()['commission_card_due_cents']);$this->invalid(fn()=>app(Ticketing::class)->commissionPaid($t,'Duplicate')); 
  $send(['id'=>'evt_ticket_refund','type'=>'charge.refunded','livemode'=>false,'data'=>['object'=>['payment_intent'=>'pi_ticket','amount_refunded'=>1000]]])->assertOk();$event['id']='evt_ticket_late';$send($event)->assertOk();$this->assertFalse($t->fresh()->valid());$this->assertSame('refunded',$t->fresh()->status);$this->assertSame(40,$p->report()['refund_payment_fee_reserve_cents']);$this->assertSame(-140,$p->report()['net_before_delivery_cents']);
 }
 public function test_stock_terms_mode_and_distributor_suspension_are_server_guarded(): void {
  $p=$this->plan();$d=$this->relay($p);$p->update(['capacity'=>1]);$t=$this->ticket($p,$d);$this->invalid(fn()=>$this->ticket($p,$d));$p->update(['capacity'=>10]);$this->invalid(fn()=>$this->ticket($p,$d,['terms_version'=>'old']));$d->update(['is_active'=>false]);$this->invalid(fn()=>$this->ticket($p,$d));$p->update(['terms_version'=>'v2','terms_fr'=>'Changed conditions']);$this->assertFalse($p->is_open);$this->assertSame('v1',$t->fresh()->terms_version);config(['registration.live'=>true]);$this->invalid(fn()=>app(Ticketing::class)->settle($d,[$t->id],900,'X','Test is not real',now()));
 }
 public function test_only_admission_can_be_redeemed_once_and_refund_blocks_public_list(): void {
  $p=$this->plan(kind:'admission');$d=$this->relay($p);$t=$this->ticket($p,$d,['public_listing'=>true,'public_name'=>'ConsentName']);app(Ticketing::class)->settle($d,[$t->id],900,'R1','Proof',now());app(Ticketing::class)->redeem($t,'Gate A');$this->invalid(fn()=>app(Ticketing::class)->redeem($t,'Gate B'));$this->invalid(fn()=>app(Ticketing::class)->refundCash($t,'Already consumed'));
  $second=$this->ticket($p,$d);app(Ticketing::class)->settle($d,[$second->id],900,'R2','Proof',now());app(Ticketing::class)->refundCash($second,'Full cash returned and commission recovered');$this->assertFalse($second->fresh()->valid());$this->assertSame(100,$p->report()['refund_commission_loss_cents']);app(Ticketing::class)->commissionRecovered($second,100,'Commission returned');$this->assertSame(0,$p->report()['refund_commission_loss_cents']);
  $url=URL::temporarySignedRoute('ticket.unlist',now()->addMinutes(10),['ticket'=>$t->public_id]);$this->post($url)->assertRedirect();$this->assertFalse($t->fresh()->public_listing);$this->post(route('ticket.unlist',['ticket'=>$t->public_id]))->assertForbidden();
 }
 public function test_sms_is_disabled_by_default_and_unknown_results_are_not_resent(): void {
  $p=$this->plan();$d=$this->relay($p);$t=$this->ticket($p,$d);app(Ticketing::class)->settle($d,[$t->id],900,'SMS1','Proof',now());Http::preventStrayRequests();$this->assertSame(0,app(TicketSms::class)->dispatch());Http::assertNothingSent();
  config(['registration.live'=>true,'presales.sms_enabled'=>true,'presales.twilio_sid'=>'ACfixture','presales.twilio_token'=>'secret','presales.twilio_from'=>'+351211234567']);$t->update(['is_live'=>true]);Http::fake(['api.twilio.com/*'=>Http::response(['code'=>500],500)]);app(TicketSms::class)->dispatch();$this->assertSame('unknown',$t->messages()->first()->status);app(TicketSms::class)->dispatch();Http::assertSentCount(1);
 }
 public function test_local_preview_reveals_only_to_active_admin_and_is_never_enabled_in_production(): void {
  $this->seed();$p=EventProject::first();$activity=$p->activities()->first();$activity->update(['publication_level'=>'hidden','relay_reveal'=>false,'is_public'=>false,'rules'=>'PRIVATE SECRET RULE']);$url=route('event.preview',['project'=>$p->slug]);$this->get($url)->assertNotFound();app()->instance('env','local');$this->get($url)->assertForbidden();$admin=$this->admin();$this->get($url)->assertOk()->assertSee('festival-concept.webp')->assertSee($activity->name)->assertHeader('Cache-Control','no-store, private');$this->get(route('activity.preview',['project'=>$p->slug,'activity'=>$activity->public_id]))->assertSee('PRIVATE SECRET RULE');$this->get(route('activity.show',['project'=>$p->slug,'activity'=>$activity->public_id]))->assertNotFound();app()->instance('env','production');$this->get($url)->assertNotFound();
 }
 public function test_meeting_waits_for_junta_and_cafe_agreements_and_delivery_requires_proof(): void {
  $p=$this->plan();$v=OutreachVisit::create(['event_project_id'=>$p->event_project_id,'name'=>'Junta','freguesia'=>'Village']);$this->invalid(fn()=>$v->update(['meeting_at'=>now()->addDay()]));$v->refresh();$this->invalid(fn()=>$v->update(['letters_delivered'=>2]));$v->refresh();$v->update(['junta_status'=>'agreed','junta_evidence'=>'Written agreement','prospective_relay'=>'Café','meeting_at'=>now()->addDay(),'meeting_agreement'=>'Host and junta agree']);$this->assertNotNull($v->meeting_at);
 }
 public function test_pitch_needs_do_not_assume_power_and_revoked_upstream_invalidates_supply(): void {
  $p=$this->plan();$d=$this->relay($p);$stand=$d->standPartner->stand;$main=SiteInfrastructure::create(['event_project_id'=>$p->event_project_id,'name'=>'LS 4x16','kind'=>'main_supply','conductor_count'=>4,'section_mm2'=>16]);$this->assertNull($main->amp_limit);$this->invalid(fn()=>$main->update(['status'=>'approved']));$main->refresh();$main->update(['amp_limit'=>20,'voltage_v'=>230,'phases'=>'single','earth_verified'=>true,'review_evidence'=>'Professional checks']);$main->update(['status'=>'approved']);
  $branch=SiteInfrastructure::create(['event_project_id'=>$p->event_project_id,'name'=>'Branch','kind'=>'distribution','source_id'=>$main->id,'amp_limit'=>4,'voltage_v'=>230,'phases'=>'single','earth_verified'=>true,'review_evidence'=>'Professional checks','status'=>'approved']);$need=StandRequirement::create(['stand_id'=>$stand->id,'name'=>'Light','kind'=>'electricity','justification'=>'Evening light','power_w'=>20,'line_length_m'=>15,'source_id'=>$branch->id,'provided_by'=>'qapas','status'=>'approved','review_evidence'=>'Checked']);$this->assertTrue($need->valid());$this->invalid(fn()=>StandRequirement::create(['stand_id'=>$stand->id,'name'=>'Water','kind'=>'water','justification'=>'Cleaning','source_id'=>$branch->id,'provided_by'=>'qapas','status'=>'approved','review_evidence'=>'Wrong kind']));$main->update(['cable_marking'=>'Changed cable']);$this->assertFalse($need->valid());$other=$this->plan('other');$foreign=SiteInfrastructure::create(['event_project_id'=>$other->event_project_id,'name'=>'Foreign','kind'=>'generator']);$this->invalid(fn()=>$need->update(['source_id'=>$foreign->id]));$this->invalid(fn()=>$main->update(['source_id'=>$branch->id]));
 }
 public function test_new_admin_forms_render_including_dynamic_relations_and_cash_settlement(): void {
  $this->seed();$this->admin();foreach(['OutreachVisit','SiteInfrastructure','PresalePlan','Distributor','EventTicket','TicketSettlement','TicketMessage'] as $name){$class='App\\Filament\\Resources\\'.$name.'Resource';$this->get($class::getUrl())->assertOk();if(in_array($name,['OutreachVisit','SiteInfrastructure','PresalePlan','Distributor','TicketSettlement'])){$page=$class.'\Pages\ManageRecords';\Livewire\Livewire::test($page)->mountAction('create')->assertHasNoActionErrors();}}
  $stand=\App\Models\Stand::first();\Livewire\Livewire::test(\App\Filament\RelationManagers\StandRequirementsRelationManager::class,['ownerRecord'=>$stand,'pageClass'=>\App\Filament\Resources\StandResource\Pages\EditRecord::class])->mountAction(\Filament\Actions\Testing\TestAction::make('create')->table())->assertHasNoActionErrors();
 }
 public function test_cash_portal_submits_a_real_form_and_retries_the_same_receipt_without_double_collection(): void {
  $p=$this->plan();$d=$this->relay($p);auth('admin')->logout();$form=$this->get(route('relay.cash'))->assertOk()->assertSee('cash_received',false);$token=$form->viewData('token');
  $data=['request_id'=>$token,'buyer_name'=>'João','email'=>'joao@example.test','phone'=>'+351912345679','terms_version'=>'v1','terms'=>1,'privacy'=>1,'cash_received'=>1,'public_listing'=>1,'public_name'=>'João'];
  $url=route('presales.store',['project'=>$p->eventProject->slug]);$response=$this->post($url,$data)->assertRedirect();$this->get($response->headers->get('Location'))->assertOk()->assertSee('João')->assertSee('EN ATTENTE');$this->post($url,$data)->assertRedirect();$this->assertDatabaseCount('event_tickets',1);$this->get(route('relay.dashboard'))->assertOk()->assertSee('9,00');
  $data['request_id']=(string)\Illuminate\Support\Str::uuid();$this->post($url,$data)->assertStatus(419);
 }
 public function test_late_received_candidate_cash_is_recorded_for_review_not_validated_after_vote_deadline(): void {
  $p=$this->plan();$d=$this->relay($p);$campaign=RegistrationCampaign::create(['event_project_id'=>$p->event_project_id,'name'=>'Experts','terms_version'=>'candidate-v1','terms_fr'=>'Terms','terms_pt'=>'Condições','refund_policy_fr'=>'Refund','refund_policy_pt'=>'Reembolso','vat_basis_points'=>0,'billing_procedure'=>'Invoices','validation_evidence'=>'Review','closes_at'=>now()->addDays(10),'is_open'=>true]);
  $t=$this->ticket($p,$d,['candidate'=>true,'candidate_terms_version'=>'candidate-v1','expert_roles'=>['cook']]);$this->travel(11)->days();app(Ticketing::class)->settle($d,[$t->id],900,'LATE','Funds arrived after cutoff',now());$this->assertSame('review',$t->fresh()->status);$this->assertFalse($t->fresh()->candidate->isPaid());$this->assertDatabaseCount('ticket_messages',0);$this->assertSame(1000,$p->report()['review_received_cents']);app(Ticketing::class)->refundCash($t,'Full refund paid; commission returned',100);$this->assertSame('refunded',$t->fresh()->status);
 }
 public function test_sms_acceptance_does_not_claim_delivery_until_provider_confirms(): void {
  $p=$this->plan();$d=$this->relay($p);$t=$this->ticket($p,$d);app(Ticketing::class)->settle($d,[$t->id],900,'SMS2','Proof',now());config(['registration.live'=>true,'presales.sms_enabled'=>true,'presales.twilio_sid'=>'ACfixture','presales.twilio_token'=>'secret','presales.twilio_from'=>'+351211234567']);$t->update(['is_live'=>true]);$sid='SM'.str_repeat('1',32);Http::preventStrayRequests();Http::fake(['api.twilio.com/*'=>Http::sequence()->push(['sid'=>$sid,'status'=>'queued'])->push(['sid'=>$sid,'status'=>'sent'])->push(['sid'=>$sid,'status'=>'delivered'])]);
  $this->assertSame(1,app(TicketSms::class)->dispatch());$this->assertSame('accepted',$t->messages()->first()->status);$this->assertNull($t->messages()->first()->delivered_at);app(TicketSms::class)->dispatch();$this->assertSame('delivered',$t->messages()->first()->status);$this->assertNotNull($t->messages()->first()->delivered_at);Http::assertSentCount(3);
 }

}
