<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::table('event_projects',function(Blueprint $t){$t->string('community_version')->nullable();$t->unsignedInteger('edition_year')->nullable();$t->string('daily_hours')->nullable();});
  Schema::table('presale_plans',function(Blueprint $t){$t->unsignedInteger('drink_credit_cents')->default(0);$t->unsignedInteger('drink_cost_cents')->nullable();$t->text('drink_credit_terms_fr')->nullable();$t->text('drink_credit_terms_pt')->nullable();$t->text('drink_cost_evidence')->nullable();});
  Schema::table('event_tickets',function(Blueprint $t){$t->unsignedInteger('drink_credit_cents')->default(0);$t->text('drink_credit_terms_snapshot')->nullable();});
  Schema::create('ticket_drink_redemptions',function(Blueprint $t){$t->id();$t->foreignId('event_ticket_id')->constrained()->restrictOnDelete();$t->uuid('operation_id')->unique();$t->unsignedInteger('amount_cents');$t->foreignId('admin_id')->constrained()->restrictOnDelete();$t->text('evidence');$t->timestamp('created_at');});
  Schema::table('team_role_assignments',function(Blueprint $t){$t->boolean('shared_operator')->default(false);$t->text('sharing_evidence')->nullable();});
  Schema::table('stand_partners',function(Blueprint $t){$t->unsignedInteger('meeting_capacity')->nullable();$t->boolean('meeting_candidate')->default(false);$t->text('meeting_capacity_evidence')->nullable();$t->text('meeting_selection_reason')->nullable();});
  Schema::table('sponsorships',function(Blueprint $t){$t->json('signage_feature_ids')->nullable();$t->text('signage_deliverables')->nullable();});
  Schema::create('freguesia_agreements',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('event_project_id')->constrained()->restrictOnDelete();$t->foreignId('stand_id')->unique()->constrained()->restrictOnDelete();$t->string('name');$t->string('status')->default('draft');$t->string('terms_version');$t->text('terms_fr');$t->text('terms_pt');$t->string('legal_entity')->nullable();$t->string('signatory')->nullable();$t->text('authority_evidence')->nullable();$t->text('legal_review')->nullable();$t->text('agreement_evidence')->nullable();$t->timestamp('signed_at')->nullable();$t->timestamps();});
  Schema::create('community_awards',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('event_project_id')->unique()->constrained()->restrictOnDelete();$t->string('name');$t->foreignId('budget_line_id')->nullable()->constrained()->restrictOnDelete();$t->foreignId('winner_team_id')->nullable()->constrained('teams')->restrictOnDelete();$t->string('status')->default('planned');$t->text('rules_fr');$t->text('rules_pt');$t->text('results_evidence')->nullable();$t->string('recipient_entity')->nullable();$t->text('prize_project')->nullable();$t->text('payment_evidence')->nullable();$t->timestamp('paid_at')->nullable();$t->text('trophy_custody')->nullable();$t->string('next_host_status')->default('proposed');$t->text('next_host_evidence')->nullable();$t->boolean('is_public')->default(false);$t->timestamps();});
  Schema::create('bar_partnerships',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('event_project_id')->constrained()->restrictOnDelete();$t->foreignId('stand_partner_id')->constrained()->restrictOnDelete();$t->string('name');$t->string('status')->default('study');$t->dateTime('starts_at')->nullable();$t->dateTime('ends_at')->nullable();$t->unsignedInteger('commission_basis_points')->nullable();$t->unsignedInteger('forecast_ticket_sales_cents')->default(0);$t->unsignedInteger('forecast_other_costs_cents')->nullable();$t->foreignId('budget_line_id')->nullable()->constrained()->restrictOnDelete();$t->text('terms')->nullable();$t->text('operator_evidence')->nullable();$t->text('agreement_evidence')->nullable();$t->timestamps();});
  Schema::create('report_points',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('event_project_id')->constrained()->restrictOnDelete();$t->foreignId('stand_id')->nullable()->unique()->constrained()->restrictOnDelete();$t->foreignId('site_feature_id')->nullable()->unique()->constrained()->restrictOnDelete();$t->string('name');$t->boolean('is_active')->default(false);$t->text('placement_evidence')->nullable();$t->timestamps();});
  Schema::table('incidents',function(Blueprint $t){$t->foreignId('report_point_id')->nullable()->constrained()->restrictOnDelete();$t->uuid('submission_id')->nullable()->unique();$t->string('source')->default('admin');$t->text('report')->nullable();$t->timestamp('acknowledged_at')->nullable();$t->timestamp('closed_at')->nullable();});
  Schema::create('rally_stops',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('event_project_id')->constrained()->restrictOnDelete();$t->foreignId('stand_id')->unique()->constrained()->restrictOnDelete();$t->foreignId('site_feature_id')->nullable()->constrained()->restrictOnDelete();$t->string('name');$t->unsignedInteger('sort_order')->default(100);$t->text('story_fr')->nullable();$t->text('story_pt')->nullable();$t->text('nature_fr')->nullable();$t->text('nature_pt')->nullable();$t->text('question_fr')->nullable();$t->text('question_pt')->nullable();$t->text('answer')->nullable();$t->text('review_evidence')->nullable();$t->text('safety_evidence')->nullable();$t->boolean('is_public')->default(false);$t->timestamps();});
  Schema::create('drawing_contests',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('event_project_id')->unique()->constrained()->restrictOnDelete();$t->string('name');$t->dateTime('opens_at')->nullable();$t->dateTime('closes_at')->nullable();$t->text('rules_fr')->nullable();$t->text('rules_pt')->nullable();$t->text('jury_evidence')->nullable();$t->text('prize_description')->nullable();$t->foreignId('budget_line_id')->nullable()->constrained()->restrictOnDelete();$t->boolean('is_open')->default(false);$t->timestamps();});
  Schema::create('drawing_entries',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('drawing_contest_id')->constrained()->restrictOnDelete();$t->foreignId('stand_id')->constrained()->restrictOnDelete();$t->string('name');$t->string('age_band');$t->text('guardian_contact');$t->text('guardian_evidence');$t->string('artwork_reference');$t->text('jury_decision')->nullable();$t->string('status')->default('received');$t->string('winner_key')->nullable()->unique();$t->timestamp('awarded_at')->nullable();$t->text('award_evidence')->nullable();$t->timestamps();});
  Schema::create('feedback_campaigns',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('event_project_id')->unique()->constrained()->restrictOnDelete();$t->string('name');$t->string('version')->default('1');$t->text('body_fr');$t->text('body_pt');$t->text('authorization')->nullable();$t->dateTime('send_after')->nullable();$t->dateTime('closes_at')->nullable();$t->boolean('is_enabled')->default(false);$t->timestamps();});
  Schema::create('feedback_invitations',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('feedback_campaign_id')->constrained()->restrictOnDelete();$t->string('name');$t->string('audience');$t->text('email')->nullable();$t->string('email_hash')->nullable();$t->string('source_key');$t->string('locale')->default('pt');$t->text('contact_basis')->nullable();$t->string('status')->default('draft');$t->text('body_snapshot')->nullable();$t->timestamp('started_at')->nullable();$t->timestamp('sent_at')->nullable();$t->text('delivery_evidence')->nullable();$t->unsignedTinyInteger('rating')->nullable();$t->text('positive')->nullable();$t->text('improvements')->nullable();$t->timestamp('responded_at')->nullable();$t->timestamps();$t->unique(['feedback_campaign_id','source_key']);$t->unique(['feedback_campaign_id','email_hash']);});
  Schema::create('editorial_posts',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('event_project_id')->constrained()->restrictOnDelete();$t->string('template_key')->nullable();$t->string('name');$t->string('title_pt')->nullable();$t->text('body_fr')->nullable();$t->text('body_pt')->nullable();$t->string('youtube_id')->nullable();$t->text('rights_evidence')->nullable();$t->string('status')->default('draft');$t->timestamp('published_at')->nullable();$t->timestamps();$t->unique(['event_project_id','template_key']);});
 }
 public function down(): void {
  foreach(['editorial_posts','feedback_invitations','feedback_campaigns','drawing_entries','drawing_contests','rally_stops'] as $table)Schema::dropIfExists($table);
  Schema::table('incidents',function(Blueprint $t){$t->dropConstrainedForeignId('report_point_id');$t->dropColumn(['submission_id','source','report','acknowledged_at','closed_at']);});
  foreach(['report_points','bar_partnerships','community_awards','freguesia_agreements','ticket_drink_redemptions'] as $table)Schema::dropIfExists($table);
  Schema::table('sponsorships',fn(Blueprint $t)=>$t->dropColumn(['signage_feature_ids','signage_deliverables']));
  Schema::table('stand_partners',fn(Blueprint $t)=>$t->dropColumn(['meeting_capacity','meeting_candidate','meeting_capacity_evidence','meeting_selection_reason']));
  Schema::table('team_role_assignments',fn(Blueprint $t)=>$t->dropColumn(['shared_operator','sharing_evidence']));
  Schema::table('event_tickets',fn(Blueprint $t)=>$t->dropColumn(['drink_credit_cents','drink_credit_terms_snapshot']));
  Schema::table('presale_plans',fn(Blueprint $t)=>$t->dropColumn(['drink_credit_cents','drink_cost_cents','drink_credit_terms_fr','drink_credit_terms_pt','drink_cost_evidence']));
  Schema::table('event_projects',fn(Blueprint $t)=>$t->dropColumn(['community_version','edition_year','daily_hours']));
 }
};
