<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::table('event_projects',function(Blueprint $t){$t->boolean('geo_is_public')->default(false);$t->text('land_contribution')->nullable();});
  Schema::create('site_features',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('event_project_id')->constrained()->restrictOnDelete();$t->string('name');$t->string('category');$t->json('geometry');$t->string('access')->default('restricted');$t->boolean('is_public')->default(false);$t->boolean('needs_complete')->default(false);$t->unsignedInteger('capacity')->nullable();$t->string('owner')->nullable();$t->text('notes')->nullable();$t->timestamps();});
  Schema::create('site_needs',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('site_feature_id')->constrained()->restrictOnDelete();$t->string('name');$t->string('unit')->default('unité');$t->unsignedInteger('quantity')->nullable();$t->string('basis')->default('fixed');$t->unsignedInteger('unit_gross_cents')->nullable();$t->unsignedInteger('vat_basis_points')->nullable();$t->boolean('deductible')->default(false);$t->text('evidence')->nullable();$t->timestamps();});
  Schema::create('activity_locations',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('activity_id')->constrained()->restrictOnDelete();$t->foreignId('site_feature_id')->constrained()->restrictOnDelete();$t->string('role')->default('performance');$t->timestamps();$t->unique(['activity_id','site_feature_id','role']);});
  Schema::table('stands',function(Blueprint $t){$t->string('template_key')->nullable();$t->string('freguesia')->nullable();$t->text('specialty')->nullable();$t->text('sales_staff')->nullable();$t->boolean('direct_costs_complete')->default(false);$t->foreignId('site_feature_id')->nullable()->constrained()->restrictOnDelete();$t->unique(['event_project_id','template_key']);});
  Schema::create('stand_partners',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('stand_id')->constrained()->restrictOnDelete();$t->string('name');$t->unsignedTinyInteger('main_slot')->nullable();$t->unsignedTinyInteger('relay_slot')->nullable();$t->string('status')->default('prospect');$t->text('mission')->nullable();$t->text('evidence')->nullable();$t->timestamps();$t->unique(['stand_id','main_slot']);$t->unique(['stand_id','relay_slot']);});
  Schema::table('scenarios',function(Blueprint $t){$t->string('template_key')->nullable();$t->boolean('launch_model')->default(false);$t->foreignId('parent_id')->nullable()->constrained('scenarios')->restrictOnDelete();$t->unsignedInteger('event_days')->nullable();$t->unsignedInteger('minimum_daily_activities')->default(3);$t->unsignedInteger('independent_target')->default(0);$t->unsignedInteger('guests_per_stand')->nullable();$t->unsignedInteger('tent_capacity')->nullable();$t->unsignedInteger('contingency_cents')->nullable();$t->unsignedInteger('refund_reserve_cents')->nullable();$t->text('reserve_evidence')->nullable();$t->unique(['event_project_id','template_key']);});
  Schema::create('scenario_stand',function(Blueprint $t){$t->id();$t->foreignId('scenario_id')->constrained()->restrictOnDelete();$t->foreignId('stand_id')->constrained()->restrictOnDelete();$t->unique(['scenario_id','stand_id']);});
  Schema::create('scenario_site_feature',function(Blueprint $t){$t->id();$t->foreignId('scenario_id')->constrained()->restrictOnDelete();$t->foreignId('site_feature_id')->constrained()->restrictOnDelete();$t->unique(['scenario_id','site_feature_id']);});
  Schema::create('program_slots',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('scenario_id')->constrained()->restrictOnDelete();$t->foreignId('activity_id')->constrained()->restrictOnDelete();$t->unsignedInteger('day_number');$t->string('time_label')->nullable();$t->text('notes')->nullable();$t->timestamps();$t->unique(['scenario_id','activity_id','day_number']);});
  Schema::table('budget_lines',function(Blueprint $t){$t->unsignedInteger('unit_gross_cents')->nullable()->change();$t->string('scope')->default('common');$t->foreignId('stand_id')->nullable()->constrained()->restrictOnDelete();$t->foreignId('stand_partner_id')->nullable()->constrained()->restrictOnDelete();$t->string('paid_by')->default('qapas');$t->unsignedInteger('reimbursed_cents')->default(0);$t->text('receipt_reference')->nullable();$t->timestamp('reconciled_at')->nullable();$t->unsignedBigInteger('reconciled_by')->nullable();});
  Schema::table('ideas',function(Blueprint $t){$t->string('template_key')->nullable();$t->string('owner')->nullable();$t->date('due_at')->nullable();$t->json('depends_on')->nullable();$t->unsignedInteger('sort_order')->default(100);$t->boolean('is_public')->default(false);$t->string('public_label')->nullable();$t->unique(['event_project_id','template_key']);});
  Schema::table('activities',function(Blueprint $t){$t->string('publication_level')->default('details');$t->foreignId('funding_scenario_id')->nullable()->constrained('scenarios')->restrictOnDelete();$t->string('youtube_id')->nullable();});
  Schema::table('offers',function(Blueprint $t){$t->string('template_key')->nullable();$t->boolean('is_founder')->default(false);$t->unsignedInteger('regular_price_gross_cents')->nullable();$t->date('founder_deadline')->nullable();$t->unique(['event_project_id','template_key']);});
 }
 public function down(): void {
  Schema::table('offers',function(Blueprint $t){$t->dropUnique(['event_project_id','template_key']);$t->dropColumn(['template_key','is_founder','regular_price_gross_cents','founder_deadline']);});
  Schema::table('activities',function(Blueprint $t){$t->dropForeign(['funding_scenario_id']);$t->dropColumn(['publication_level','funding_scenario_id','youtube_id']);});
  Schema::table('ideas',function(Blueprint $t){$t->dropUnique(['event_project_id','template_key']);$t->dropColumn(['template_key','owner','due_at','depends_on','sort_order','is_public','public_label']);});
  Schema::table('budget_lines',function(Blueprint $t){$t->dropForeign(['stand_id']);$t->dropForeign(['stand_partner_id']);$t->dropColumn(['scope','stand_id','stand_partner_id','paid_by','reimbursed_cents','receipt_reference','reconciled_at','reconciled_by']);});
  Schema::dropIfExists('program_slots');Schema::dropIfExists('scenario_site_feature');Schema::dropIfExists('scenario_stand');
  Schema::table('scenarios',function(Blueprint $t){$t->dropForeign(['parent_id']);$t->dropUnique(['event_project_id','template_key']);$t->dropColumn(['template_key','launch_model','parent_id','event_days','minimum_daily_activities','independent_target','guests_per_stand','tent_capacity','contingency_cents','refund_reserve_cents','reserve_evidence']);});
  Schema::dropIfExists('stand_partners');Schema::table('stands',function(Blueprint $t){$t->dropForeign(['site_feature_id']);$t->dropUnique(['event_project_id','template_key']);$t->dropColumn(['template_key','freguesia','specialty','sales_staff','direct_costs_complete','site_feature_id']);});
  Schema::dropIfExists('activity_locations');Schema::dropIfExists('site_needs');Schema::dropIfExists('site_features');Schema::table('event_projects',fn(Blueprint $t)=>$t->dropColumn(['geo_is_public','land_contribution']));
 }
};
