<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::table('activities',fn(Blueprint $t)=>$t->boolean('relay_reveal')->default(false));
  Schema::table('activity_locations',function(Blueprint $t){$t->string('name')->nullable();$t->json('geometry')->nullable();$t->json('additional_quartel_ids')->nullable();$t->string('access')->default('restricted');$t->boolean('is_public')->default(false);$t->text('coordination_notes')->nullable();});
  Schema::table('activity_materials',fn(Blueprint $t)=>$t->foreignId('activity_location_id')->nullable()->constrained()->restrictOnDelete());
  Schema::table('scenarios',fn(Blueprint $t)=>$t->string('shelter_model')->default('common'));
  Schema::table('stands',function(Blueprint $t){$t->unsignedInteger('shelter_target')->default(24);$t->unsignedInteger('sheltered_capacity')->nullable();$t->unsignedInteger('seated_capacity')->nullable();$t->unsignedInteger('included_furniture_sets')->default(1);$t->unsignedInteger('extra_furniture_sets')->default(0);$t->string('shelter_source')->default('undecided');$t->boolean('larger_tent_requested')->default(false);$t->boolean('hospitality_validated')->default(false);$t->text('hospitality_evidence')->nullable();});
  Schema::table('stand_partners',function(Blueprint $t){$t->boolean('hosts_information_meeting')->default(false);$t->timestamp('meeting_at')->nullable();$t->string('meeting_place')->nullable();$t->text('meeting_agreement')->nullable();});
  Schema::table('interests',function(Blueprint $t){$t->boolean('larger_tent_requested')->default(false);$t->boolean('extra_furniture_requested')->default(false);$t->unsignedInteger('expected_guests')->nullable();});
  Schema::create('press_releases',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('event_project_id')->constrained()->restrictOnDelete();$t->string('template_key')->nullable();$t->string('name');$t->string('title_pt')->nullable();$t->string('phase')->default('before');$t->string('kind')->default('mobilization');$t->text('body')->nullable();$t->text('body_pt')->nullable();$t->string('owner')->nullable();$t->integer('day_offset')->nullable();$t->string('date_anchor')->default('start');$t->timestamp('target_at')->nullable();$t->timestamp('published_at')->nullable();$t->string('status')->default('draft');$t->boolean('is_public')->default(false);$t->json('depends_on')->nullable();$t->foreignId('scenario_id')->nullable()->constrained()->restrictOnDelete();$t->text('evidence')->nullable();$t->text('media_targets')->nullable();$t->text('assets_and_rights')->nullable();$t->text('coverage')->nullable();$t->timestamps();$t->unique(['event_project_id','template_key']);});
  Schema::create('furniture_plans',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('event_project_id')->constrained()->restrictOnDelete();$t->string('template_key')->nullable();$t->string('name');$t->json('parts');$t->unsignedInteger('quantity')->default(12);$t->unsignedInteger('waste_basis_points')->default(1500);$t->unsignedInteger('wood_price_cents_m3')->nullable();$t->unsignedInteger('can_price_cents')->default(4000);$t->decimal('can_litres',8,3)->default(5);$t->decimal('coverage_m2_litre',8,3)->nullable();$t->unsignedInteger('coats')->nullable();$t->unsignedInteger('hardware_cents_unit')->nullable();$t->unsignedInteger('roller_cents_batch')->nullable();$t->unsignedInteger('other_cents_batch')->nullable();$t->unsignedInteger('work_minutes_unit')->nullable();$t->unsignedInteger('hourly_cents')->nullable();$t->unsignedInteger('service_cents_unit')->nullable();$t->unsignedInteger('rental_gross_cents')->default(5000);$t->unsignedInteger('vat_basis_points')->nullable();$t->boolean('inputs_verified')->default(false);$t->text('evidence')->nullable();$t->timestamps();$t->unique(['event_project_id','template_key']);});
  Schema::create('catering_services',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('event_project_id')->constrained()->restrictOnDelete();$t->string('template_key')->nullable();$t->string('name');$t->string('recipe');$t->string('chef');$t->boolean('chef_confirmed')->default(false);$t->string('production_place')->nullable();$t->unsignedInteger('planned_portions')->nullable();$t->unsignedInteger('prepared_portions')->nullable();$t->unsignedInteger('sold_portions')->nullable();$t->unsignedInteger('price_gross_cents')->nullable();$t->text('allergens')->nullable();$t->text('service_plan')->nullable();$t->text('evidence')->nullable();$t->timestamps();$t->unique(['event_project_id','template_key']);});
  Schema::create('prospects',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('event_project_id')->constrained()->restrictOnDelete();$t->string('source_key');$t->string('entity_key');$t->string('name');$t->string('category');$t->string('sector');$t->string('tour');$t->unsignedInteger('priority')->default(2);$t->unsignedInteger('visit_order')->default(100);$t->text('address');$t->string('phone')->nullable();$t->string('email')->nullable();$t->text('opportunity')->nullable();$t->text('next_action')->nullable();$t->string('status')->default('new');$t->timestamp('appointment_at')->nullable();$t->boolean('address_confirmed')->default(false);$t->text('source');$t->date('checked_at');$t->text('notes')->nullable();$t->timestamps();$t->unique(['event_project_id','source_key']);});
 }
 public function down(): void {
  Schema::table('activities',fn(Blueprint $t)=>$t->dropColumn('relay_reveal'));
  foreach(['prospects','catering_services','furniture_plans','press_releases'] as $table)Schema::dropIfExists($table);
  Schema::table('interests',fn(Blueprint $t)=>$t->dropColumn(['larger_tent_requested','extra_furniture_requested','expected_guests']));
  Schema::table('stand_partners',fn(Blueprint $t)=>$t->dropColumn(['hosts_information_meeting','meeting_at','meeting_place','meeting_agreement']));
  Schema::table('stands',fn(Blueprint $t)=>$t->dropColumn(['shelter_target','sheltered_capacity','seated_capacity','included_furniture_sets','extra_furniture_sets','shelter_source','larger_tent_requested','hospitality_validated','hospitality_evidence']));
  Schema::table('scenarios',fn(Blueprint $t)=>$t->dropColumn('shelter_model'));
  Schema::table('activity_materials',function(Blueprint $t){$t->dropForeign(['activity_location_id']);$t->dropColumn('activity_location_id');});
  Schema::table('activity_locations',fn(Blueprint $t)=>$t->dropColumn(['name','geometry','additional_quartel_ids','access','is_public','coordination_notes']));
 }
};
