<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('presale_plans',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('event_project_id')->unique()->constrained()->restrictOnDelete();$t->string('name');$t->string('terms_version');$t->string('kind')->default('support');$t->unsignedInteger('price_cents')->default(1000);foreach(['parking','relay','junta','village'] as $part)$t->unsignedInteger($part.'_basis_points')->default(1000);$t->unsignedInteger('vat_basis_points')->nullable();$t->string('stripe_tax_rate_id')->nullable();$t->text('terms_fr')->nullable();$t->text('terms_pt')->nullable();$t->text('refund_fr')->nullable();$t->text('refund_pt')->nullable();$t->text('split_evidence')->nullable();$t->text('billing_procedure')->nullable();$t->text('approval_evidence')->nullable();$t->boolean('is_open')->default(false);$t->unsignedInteger('capacity')->default(0);$t->timestamp('closes_at')->nullable();$t->unsignedBigInteger('bank_available_cents')->nullable();$t->unsignedBigInteger('refund_reserve_cents')->nullable();$t->text('bank_evidence')->nullable();$t->timestamps();});
  Schema::create('distributors',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('stand_partner_id')->unique()->constrained()->restrictOnDelete();$t->string('name');$t->string('email')->unique();$t->string('password');$t->rememberToken();$t->boolean('is_active')->default(false);$t->text('contract_evidence')->nullable();$t->timestamps();});
  Schema::create('ticket_settlements',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('presale_plan_id')->constrained()->restrictOnDelete();$t->foreignId('distributor_id')->constrained()->restrictOnDelete();$t->boolean('is_live');$t->unsignedBigInteger('received_cents');$t->string('reference');$t->text('evidence');$t->timestamp('received_at');$t->foreignId('admin_id')->constrained()->restrictOnDelete();$t->timestamps();$t->unique(['presale_plan_id','reference']);});
  Schema::create('event_tickets',function(Blueprint $t){$t->id();$t->uuid('request_id')->nullable()->unique();$t->uuid('public_id')->unique();$t->foreignId('presale_plan_id')->constrained()->restrictOnDelete();$t->foreignId('distributor_id')->nullable()->constrained()->restrictOnDelete();$t->foreignId('stand_id')->nullable()->constrained()->restrictOnDelete();$t->foreignId('candidate_registration_id')->nullable()->unique()->constrained()->restrictOnDelete();$t->foreignId('ticket_settlement_id')->nullable()->constrained()->restrictOnDelete();$t->string('kind');$t->string('buyer_name');$t->string('email')->nullable();$t->text('phone');$t->string('freguesia');$t->boolean('public_listing')->default(false);$t->string('public_name')->nullable();$t->timestamp('listing_consented_at')->nullable();$t->string('terms_version');$t->text('terms_snapshot');$t->timestamp('accepted_at');$t->boolean('is_live')->default(false);$t->string('channel');$t->string('status')->default('pending');$t->unsignedInteger('amount_cents');$t->unsignedInteger('vat_basis_points');foreach(['parking','relay','junta','village','commission_retained'] as $part)$t->unsignedInteger($part.'_cents')->default(0);$t->unsignedInteger('fee_cents')->nullable();$t->timestamp('cash_collected_at')->nullable();$t->timestamp('paid_at')->nullable();$t->string('stripe_session_id')->nullable()->unique();$t->string('stripe_payment_intent')->nullable()->unique();$t->text('checkout_url')->nullable();$t->unsignedInteger('checkout_attempt')->default(1);$t->timestamp('redeemed_at')->nullable();$t->foreignId('redeemed_by')->nullable()->constrained('admins')->restrictOnDelete();$t->text('redemption_evidence')->nullable();$t->text('refund_evidence')->nullable();$t->timestamps();});
  Schema::create('ticket_webhooks',function(Blueprint $t){$t->string('provider_event_id')->primary();$t->timestamp('processed_at');});
  Schema::create('ticket_messages',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('event_ticket_id')->constrained()->restrictOnDelete();$t->string('purpose');$t->string('status')->default('queued');$t->string('provider_id')->nullable();$t->string('error_code')->nullable();$t->timestamp('attempted_at')->nullable();$t->timestamp('delivered_at')->nullable();$t->timestamps();$t->unique(['event_ticket_id','purpose']);});
 }
 public function down(): void {Schema::dropIfExists('ticket_messages');Schema::dropIfExists('ticket_webhooks');Schema::dropIfExists('event_tickets');Schema::dropIfExists('ticket_settlements');Schema::dropIfExists('distributors');Schema::dropIfExists('presale_plans');}
};
