<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;
return new class extends Migration {
 public function up(): void {
  Schema::table('event_projects',function(Blueprint $t){$t->boolean('require_activity_trials')->default(false);$t->date('rehearsal_weekend_start')->nullable();$t->date('rehearsal_weekend_end')->nullable();});
  Schema::table('activities',function(Blueprint $t){$t->foreignId('stand_id')->nullable()->constrained()->restrictOnDelete();$t->string('participation_decision')->default('challenge');$t->text('withdrawal_reason')->nullable();});
  Schema::table('budget_lines',function(Blueprint $t){$t->string('identity_key',64)->nullable()->unique();$t->foreignId('superseded_by_id')->nullable()->constrained('budget_lines')->restrictOnDelete();});
  // Existing repeated rows remain reviewable; never silently discard historical money.
  $seen=[];foreach(DB::table('budget_lines')->orderBy('id')->get() as $l){$key=\App\Domain\Finance\BudgetIdentity::key((array)$l);if(!isset($seen[$key])){DB::table('budget_lines')->where('id',$l->id)->update(['identity_key'=>$key]);$seen[$key]=true;}}
  Schema::create('activity_trials',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('activity_id')->constrained()->restrictOnDelete();$t->string('stage');$t->timestamp('planned_at')->nullable();$t->timestamp('performed_at')->nullable();$t->string('location')->nullable();$t->string('responsible')->nullable();$t->unsignedInteger('volunteers')->nullable();$t->unsignedInteger('duration_seconds')->nullable();$t->string('result')->default('planned');$t->text('evidence')->nullable();$t->text('adjustments')->nullable();$t->string('protocol_hash',64)->nullable();$t->timestamp('reviewed_at')->nullable();$t->foreignId('reviewed_by')->nullable()->constrained('admins')->nullOnDelete();$t->timestamps();});
  Schema::create('cost_consultations',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('event_project_id')->constrained()->restrictOnDelete();$t->string('costable_type');$t->unsignedBigInteger('costable_id');$t->unique(['costable_type','costable_id']);$t->string('name');$t->string('subject_fr');$t->string('subject_pt');$t->text('body_fr');$t->text('body_pt');$t->text('local_search_notes')->nullable();$t->timestamp('sent_at')->nullable();$t->date('reply_due_at')->nullable();$t->timestamps();});
  Schema::create('supplier_quotes',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('cost_consultation_id')->constrained()->restrictOnDelete();$t->string('supplier');$t->string('email')->nullable();$t->string('source_type')->default('supplier');$t->string('reference')->nullable();$t->date('received_at')->nullable();$t->date('valid_until')->nullable();$t->unsignedInteger('quantity')->nullable();$t->string('unit')->nullable();$t->unsignedInteger('unit_gross_cents')->nullable();$t->unsignedInteger('vat_basis_points')->nullable();$t->unsignedInteger('delivery_cents')->nullable();$t->unsignedInteger('other_cents')->nullable();$t->unsignedInteger('deposit_cents')->nullable();$t->text('conditions')->nullable();$t->text('document_reference')->nullable();$t->timestamp('applied_at')->nullable();$t->foreignId('applied_by')->nullable()->constrained('admins')->nullOnDelete();$t->timestamps();});
  Schema::create('cup_plans',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('scenario_id')->unique()->constrained()->restrictOnDelete();$t->string('name');$t->unsignedInteger('quantity')->default(1000);$t->unsignedInteger('village_pool')->default(500);$t->unsignedInteger('independent_pool')->default(500);$t->unsignedInteger('capacity_ml')->default(300);$t->unsignedInteger('received_quantity')->default(0);$t->text('receipt_evidence')->nullable();$t->unsignedInteger('suggested_deposit_cents')->default(250);$t->unsignedInteger('reference_quantity')->default(250);$t->unsignedInteger('reference_net_cents')->default(35639);$t->unsignedInteger('reference_gross_cents')->default(42410);$t->text('reference_source')->nullable();$t->string('hot_food_status')->default('unverified');$t->text('hot_food_evidence')->nullable();$t->text('washing_plan')->nullable();$t->text('sponsor_deliverables')->nullable();$t->text('sales_and_returns_terms')->nullable();$t->timestamps();});
  Schema::create('cup_allocations',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('cup_plan_id')->constrained()->restrictOnDelete();$t->foreignId('stand_id')->constrained()->restrictOnDelete();$t->unique(['cup_plan_id','stand_id']);$t->unsignedInteger('planned_quantity')->default(0);$t->unsignedInteger('issued_quantity')->default(0);$t->unsignedInteger('returned_quantity')->default(0);$t->string('responsible')->nullable();$t->text('handover_evidence')->nullable();$t->text('stock_notes')->nullable();$t->timestamps();});
 }
 public function down(): void {
  foreach(['cup_allocations','cup_plans','supplier_quotes','cost_consultations','activity_trials'] as $name)Schema::dropIfExists($name);
  Schema::table('budget_lines',function(Blueprint $t){$t->dropConstrainedForeignId('superseded_by_id');$t->dropColumn('identity_key');});
  Schema::table('activities',function(Blueprint $t){$t->dropConstrainedForeignId('stand_id');$t->dropColumn(['participation_decision','withdrawal_reason']);});
  Schema::table('event_projects',fn(Blueprint $t)=>$t->dropColumn(['require_activity_trials','rehearsal_weekend_start','rehearsal_weekend_end']));
 }
};
