<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('registration_campaigns',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('event_project_id')->unique()->constrained()->restrictOnDelete();$t->string('name');$t->string('terms_version');$t->text('terms_fr')->nullable();$t->text('terms_pt')->nullable();$t->text('refund_policy_fr')->nullable();$t->text('refund_policy_pt')->nullable();$t->unsignedInteger('vat_basis_points')->nullable();$t->string('stripe_tax_rate_id')->nullable();$t->text('billing_procedure')->nullable();$t->text('validation_evidence')->nullable();$t->boolean('is_open')->default(false);$t->timestamp('closes_at')->nullable();$t->timestamp('reviewed_at')->nullable();$t->foreignId('reviewed_by')->nullable()->constrained('admins')->nullOnDelete();$t->string('drinks_supplier')->nullable();$t->text('drinks_contract_reference')->nullable();$t->unsignedInteger('drinks_contract_cents')->nullable();$t->unsignedInteger('drinks_allocated_cents')->default(0);$t->unsignedInteger('refund_reserve_cents')->nullable();$t->text('funding_evidence')->nullable();$t->unsignedInteger('bank_available_cents')->nullable();$t->text('bank_evidence')->nullable();$t->timestamp('vote_closed_at')->nullable();$t->text('vote_minutes_reference')->nullable();$t->timestamps();});
  Schema::create('candidate_registrations',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('registration_campaign_id')->constrained()->restrictOnDelete();$t->foreignId('interest_id')->unique()->constrained()->restrictOnDelete();$t->string('email_key');$t->boolean('is_live')->default(false);$t->unsignedInteger('amount_cents')->default(1000);$t->unsignedInteger('credit_cents')->default(1000);$t->unsignedInteger('vat_basis_points');$t->string('currency')->default('eur');$t->string('terms_version');$t->text('terms_snapshot');$t->timestamp('accepted_at');$t->string('payment_status')->default('pending');$t->string('stripe_session_id')->nullable()->unique();$t->string('stripe_payment_intent')->nullable()->unique();$t->string('checkout_url',2048)->nullable();$t->unsignedInteger('checkout_attempt')->default(1);$t->timestamp('paid_at')->nullable();$t->unsignedInteger('fee_cents')->nullable();$t->unsignedInteger('refunded_cents')->default(0);$t->string('invoice_reference')->nullable();$t->string('decision')->default('pending');$t->text('vote_evidence')->nullable();$t->timestamp('decision_at')->nullable();$t->foreignId('decision_by')->nullable()->constrained('admins')->nullOnDelete();$t->timestamps();$t->unique(['registration_campaign_id','email_key']);});
  Schema::create('registration_webhooks',function(Blueprint $t){$t->id();$t->string('provider_event_id')->unique();$t->string('type');$t->timestamp('processed_at');});
  Schema::create('drink_credits',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('candidate_registration_id')->unique()->constrained()->restrictOnDelete();$t->unsignedInteger('face_cents')->default(1000);$t->unsignedInteger('redeemed_cents')->default(0);$t->timestamps();});
  Schema::create('drink_redemptions',function(Blueprint $t){$t->id();$t->uuid('operation_id')->unique();$t->foreignId('drink_credit_id')->constrained()->restrictOnDelete();$t->unsignedInteger('amount_cents');$t->string('description');$t->foreignId('admin_id')->constrained('admins')->restrictOnDelete();$t->timestamp('created_at');});
 }
 public function down(): void {foreach(['drink_redemptions','drink_credits','registration_webhooks','candidate_registrations','registration_campaigns'] as $table)Schema::dropIfExists($table);}
};
