<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::table('prospects',function(Blueprint $t){$t->string('municipality')->default('À confirmer')->index();$t->string('contact_name')->nullable();$t->text('contact_source')->nullable();$t->timestamp('last_visited_at')->nullable();$t->timestamp('followup_at')->nullable()->index();});
  Schema::create('prospect_visits',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('prospect_id')->constrained()->restrictOnDelete();$t->timestamp('visited_at');$t->string('contact_name')->nullable();$t->string('phone')->nullable();$t->string('email')->nullable();$t->text('contact_source')->nullable();$t->text('feedback');$t->string('outcome');$t->text('next_action')->nullable();$t->timestamp('followup_at')->nullable();$t->foreignId('admin_id')->constrained('admins');$t->timestamps();});
  Schema::table('registration_campaigns',fn(Blueprint $t)=>$t->boolean('unified_ticket_terms')->default(false));
  Schema::table('offers',fn(Blueprint $t)=>$t->string('prospect_type')->nullable()->index());
  Schema::table('presale_plans',function(Blueprint $t){$t->boolean('unified_benefits')->default(false);$t->string('sales_strategy')->default('fixed');$t->unsignedInteger('full_price_cents')->nullable();$t->timestamp('early_until')->nullable();$t->timestamp('relay_changes_at')->nullable();$t->unsignedInteger('late_relay_basis_points')->nullable();$t->text('pricing_evidence')->nullable();$t->json('benefits')->nullable();$t->json('early_benefits')->nullable();$t->unsignedInteger('benefit_cost_cents')->nullable();$t->unsignedInteger('early_benefit_cost_cents')->nullable();$t->text('benefit_evidence')->nullable();});
  Schema::table('event_tickets',function(Blueprint $t){$t->boolean('includes_admission')->default(false);$t->json('benefits_snapshot')->nullable();$t->unsignedInteger('benefit_cost_cents')->nullable();$t->string('commercial_phase')->nullable();$t->string('quote_key')->nullable();});
  Schema::create('ticket_benefit_redemptions',function(Blueprint $t){$t->id();$t->foreignId('event_ticket_id')->constrained()->restrictOnDelete();$t->unsignedInteger('benefit_index');$t->unsignedInteger('quantity');$t->uuid('operation_id')->unique();$t->text('evidence');$t->foreignId('admin_id')->constrained('admins');$t->timestamp('created_at');});
  Schema::table('press_releases',function(Blueprint $t){$t->boolean('auto_dispatch')->default(false);$t->string('publication_version')->default('1');$t->json('channels')->nullable();$t->json('press_emails')->nullable();$t->json('sponsor_ids')->nullable();$t->json('relay_ids')->nullable();$t->text('dispatch_authorization')->nullable();$t->text('social_text_pt')->nullable();});
  Schema::create('publication_dispatches',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('press_release_id')->constrained()->restrictOnDelete();$t->string('version');$t->string('channel');$t->string('destination')->default('official');$t->string('dedupe_key',64)->unique();$t->string('status')->default('queued');$t->json('payload');$t->string('provider_reference')->nullable();$t->text('evidence')->nullable();$t->timestamp('started_at')->nullable();$t->timestamp('sent_at')->nullable();$t->timestamps();});
  Schema::create('sponsorships',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('event_project_id')->constrained()->restrictOnDelete();$t->string('template_key')->nullable();$t->foreignId('activity_id')->nullable()->constrained()->restrictOnDelete();$t->foreignId('prospect_id')->nullable()->constrained()->restrictOnDelete();$t->foreignId('budget_line_id')->nullable()->unique()->constrained()->restrictOnDelete();$t->string('name');$t->string('scope')->default('activity');$t->string('purpose')->default('general');$t->unsignedTinyInteger('secondary_slot')->nullable();$t->string('slot_key')->nullable();$t->string('status')->default('prospecting');$t->string('sponsor_name')->nullable();$t->string('dealer_name')->nullable();$t->text('target_profile')->nullable();$t->text('pitch')->nullable();$t->text('source')->nullable();$t->string('website_url')->nullable();$t->unsignedInteger('cash_pledged_cents')->nullable();$t->text('in_kind')->nullable();$t->text('agreement_evidence')->nullable();$t->timestamp('agreed_at')->nullable();$t->text('web_rights')->nullable();$t->text('print_evidence')->nullable();$t->timestamp('print_approved_at')->nullable();$t->boolean('is_public')->default(false);$t->timestamps();$t->unique(['event_project_id','slot_key']);$t->unique(['event_project_id','template_key']);});
  Schema::create('planting_sessions',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('event_project_id')->constrained()->restrictOnDelete();$t->foreignId('quartel_id')->nullable()->constrained('site_features')->restrictOnDelete();$t->foreignId('nursery_prospect_id')->nullable()->constrained('prospects')->restrictOnDelete();$t->foreignId('budget_line_id')->nullable()->constrained()->restrictOnDelete();$t->unsignedTinyInteger('day_number');$t->string('name');$t->timestamp('starts_at')->nullable();$t->unsignedInteger('capacity')->default(0);$t->unsignedInteger('trees_received')->default(0);$t->text('receipt_evidence')->nullable();$t->string('supervisor')->nullable();$t->text('instructions_fr')->nullable();$t->text('instructions_pt')->nullable();$t->text('partner_agreement')->nullable();$t->text('preparation_evidence')->nullable();$t->string('status')->default('draft');$t->boolean('is_public')->default(false);$t->timestamps();$t->unique(['event_project_id','day_number']);});
  Schema::create('planting_slots',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('planting_session_id')->constrained()->restrictOnDelete();$t->foreignId('event_ticket_id')->nullable()->constrained()->restrictOnDelete();$t->string('tree_code');$t->string('species')->nullable();$t->string('participant_name')->nullable();$t->string('public_name')->nullable();$t->timestamp('thanks_consented_at')->nullable();$t->decimal('latitude',10,7)->nullable();$t->decimal('longitude',10,7)->nullable();$t->string('status')->default('available');$t->timestamp('planted_at')->nullable();$t->text('evidence')->nullable();$t->timestamps();$t->unique(['planting_session_id','tree_code']);$t->unique(['planting_session_id','event_ticket_id']);});
 }
 public function down(): void {
  foreach(['planting_slots','planting_sessions','sponsorships','publication_dispatches','ticket_benefit_redemptions','prospect_visits'] as $table)Schema::dropIfExists($table);
  Schema::table('press_releases',fn(Blueprint $t)=>$t->dropColumn(['auto_dispatch','publication_version','channels','press_emails','sponsor_ids','relay_ids','dispatch_authorization','social_text_pt']));
  Schema::table('event_tickets',fn(Blueprint $t)=>$t->dropColumn(['includes_admission','benefits_snapshot','benefit_cost_cents','commercial_phase','quote_key']));
  Schema::table('presale_plans',fn(Blueprint $t)=>$t->dropColumn(['unified_benefits','sales_strategy','full_price_cents','early_until','relay_changes_at','late_relay_basis_points','pricing_evidence','benefits','early_benefits','benefit_cost_cents','early_benefit_cost_cents','benefit_evidence']));
  Schema::table('registration_campaigns',fn(Blueprint $t)=>$t->dropColumn('unified_ticket_terms'));
  Schema::table('offers',fn(Blueprint $t)=>$t->dropColumn('prospect_type'));
  Schema::table('prospects',fn(Blueprint $t)=>$t->dropColumn(['municipality','contact_name','contact_source','last_visited_at','followup_at']));
 }
};
