<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::table('event_projects',function(Blueprint $t){$t->date('proposed_start')->nullable();$t->date('proposed_end')->nullable();$t->string('proposed_website')->nullable();});
  Schema::table('offers',function(Blueprint $t){$t->text('summary')->nullable();$t->json('benefits')->nullable();$t->string('image_key')->nullable();$t->text('regular_price_evidence')->nullable();$t->boolean('preview_current')->default(false);});
  Schema::table('stands',function(Blueprint $t){$t->foreignId('quartel_id')->nullable()->constrained('site_features')->restrictOnDelete();$t->string('pitch_number',40)->nullable();$t->boolean('is_public')->default(false);$t->text('public_description')->nullable();$t->unique(['event_project_id','pitch_number']);});
  Schema::create('outreach_visits',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('event_project_id')->constrained()->restrictOnDelete();$t->string('name');$t->string('freguesia');$t->string('tour')->nullable();$t->unsignedInteger('visit_order')->default(100);$t->timestamp('planned_at')->nullable();$t->timestamp('visited_at')->nullable();$t->string('reception_contact')->nullable();$t->string('president_name')->nullable();$t->string('president_email')->nullable();$t->string('president_phone')->nullable();$t->string('treasurer_name')->nullable();$t->string('treasurer_email')->nullable();$t->string('treasurer_phone')->nullable();$t->text('contact_source')->nullable();$t->unsignedInteger('letters_delivered')->default(0);$t->unsignedInteger('cards_delivered')->default(0);$t->text('delivery_evidence')->nullable();$t->string('junta_status')->default('to_visit');$t->text('junta_evidence')->nullable();$t->string('prospective_relay')->nullable();$t->timestamp('meeting_at')->nullable();$t->text('meeting_agreement')->nullable();$t->text('next_action')->nullable();$t->timestamp('followup_at')->nullable();$t->text('letter_pt')->nullable();$t->text('teaser_pt')->nullable();$t->timestamps();});
  Schema::create('site_infrastructures',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('event_project_id')->constrained()->restrictOnDelete();$t->string('template_key')->nullable();$t->unique(['event_project_id','template_key']);$t->string('name');$t->string('kind');$t->foreignId('source_id')->nullable()->constrained('site_infrastructures')->restrictOnDelete();$t->foreignId('site_feature_id')->nullable()->constrained()->restrictOnDelete();$t->decimal('declared_kva',10,2)->nullable();$t->unsignedInteger('voltage_v')->nullable();$t->string('phases')->default('unknown');$t->decimal('amp_limit',10,2)->nullable();$t->string('cable_marking')->nullable();$t->unsignedInteger('conductor_count')->nullable();$t->decimal('section_mm2',8,2)->nullable();$t->boolean('neutral_verified')->default(false);$t->boolean('earth_verified')->default(false);$t->string('status')->default('declared');$t->text('description')->nullable();$t->text('review_evidence')->nullable();$t->foreignId('budget_line_id')->nullable()->constrained()->restrictOnDelete();$t->timestamps();});
  Schema::create('stand_requirements',function(Blueprint $t){$t->id();$t->uuid('public_id')->unique();$t->foreignId('stand_id')->constrained()->restrictOnDelete();$t->string('name');$t->string('kind');$t->text('justification');$t->unsignedInteger('quantity')->nullable();$t->string('unit')->default('unité');$t->decimal('power_w',12,2)->nullable();$t->decimal('starting_power_w',12,2)->nullable();$t->decimal('requested_amps',10,2)->nullable();$t->decimal('line_length_m',10,2)->nullable();$t->decimal('water_litres',12,2)->nullable();$t->decimal('gas_kg',10,2)->nullable();$t->foreignId('source_id')->nullable()->constrained('site_infrastructures')->restrictOnDelete();$t->foreignId('budget_line_id')->nullable()->constrained()->restrictOnDelete();$t->string('provided_by')->default('undecided');$t->string('status')->default('requested');$t->text('review_evidence')->nullable();$t->timestamps();});
  Schema::table('cup_plans',function(Blueprint $t){$t->string('soup_bowl_owner')->default('undecided');$t->text('soup_bowl_agreement')->nullable();});
 }
 public function down(): void {Schema::table('cup_plans',fn(Blueprint $t)=>$t->dropColumn(['soup_bowl_owner','soup_bowl_agreement']));Schema::dropIfExists('stand_requirements');Schema::dropIfExists('site_infrastructures');Schema::dropIfExists('outreach_visits');Schema::table('stands',function(Blueprint $t){$t->dropUnique(['event_project_id','pitch_number']);$t->dropConstrainedForeignId('quartel_id');$t->dropColumn(['pitch_number','is_public','public_description']);});Schema::table('offers',fn(Blueprint $t)=>$t->dropColumn(['summary','benefits','image_key','regular_price_evidence','preview_current']));Schema::table('event_projects',fn(Blueprint $t)=>$t->dropColumn(['proposed_start','proposed_end','proposed_website']));}
};
