<?php

return [
    'demo_enabled' => (bool) env('QAPAS_EVENT_DEMO_ENABLED', false),
    'payments_enabled' => false,
    'maximum_decision_days' => 21,
    'phases' => ['teaser' => 'Teaser', 'applications' => 'Candidatures ouvertes', 'official' => 'Événement confirmé'],
    'audiences' => ['visitors' => 'Visiteurs', 'villages' => 'Villages et équipes', 'exhibitors' => 'Exposants', 'sponsors' => 'Sponsors', 'relays' => 'Relais', 'workforce' => 'Équipes et prestataires'],
    'prerequisites' => ['site' => 'Site disponible', 'permissions' => 'Autorisations et conditions de lancement', 'workforce' => 'Postes essentiels couverts', 'audience' => 'Objectifs minimaux atteints', 'delivery' => 'Prestations et délais vérifiés', 'cash' => 'Calendrier de trésorerie rapproché'],
    'categories' => [
        'toilets' => ['label' => 'Toilettes et sanitaires', 'shape' => 'rectangle', 'color' => '#168aad', 'items' => ['portable' => 'WC portable', 'accessible' => 'WC accessible', 'block' => 'Bloc sanitaires', 'urinal' => 'Urinoir', 'handwash' => 'Lave-mains', 'shower' => 'Douche', 'service' => 'Vidange et nettoyage']],
        'audiovisual' => ['label' => 'Audiovisuel', 'shape' => 'rectangle', 'color' => '#7949ad', 'items' => ['stage' => 'Scène et estrade', 'sound' => 'Sonorisation', 'microphone' => 'Micro', 'control' => 'Régie', 'screen' => 'Écran et projection', 'lighting' => 'Éclairage de spectacle', 'data' => 'Liaison de données']],
        'electricity' => ['label' => 'Électricité', 'shape' => 'rectangle', 'color' => '#d69e16', 'items' => ['inlet' => 'Arrivée principale', 'panel' => 'Tableau et coffret', 'outlet' => 'Prise de stand', 'cable' => 'Câble et rallonge', 'generator' => 'Groupe électrogène', 'battery' => 'Batterie', 'lighting' => 'Éclairage de service']],
        'structures' => ['label' => 'Structures', 'shape' => 'square', 'color' => '#258052', 'items' => ['village_stand' => 'Stand villageois', 'independent_stand' => 'Stand indépendant', 'shelter' => 'Abri', 'chalet' => 'Chalet', 'tent' => 'Tente', 'marquee' => 'Chapiteau', 'floor' => 'Plancher', 'anchoring' => 'Ancrage et lestage']],
        'furniture' => ['label' => 'Mobilier et fournitures', 'shape' => 'rectangle', 'color' => '#a86632', 'items' => ['table' => 'Table', 'chair' => 'Chaise', 'bench' => 'Banc', 'counter' => 'Comptoir', 'shelf' => 'Étagère', 'storage' => 'Rangement', 'cleaning' => 'Nettoyage', 'supplies' => 'Consommables']],
        'vehicles' => ['label' => 'Véhicules et engins', 'shape' => 'rectangle', 'color' => '#58667e', 'items' => ['truck' => 'Camion et Dyna', 'van' => 'Utilitaire', 'trailer' => 'Remorque', 'tractor' => 'Tracteur', 'handling' => 'Manutention', 'shredder' => 'Broyeur', 'shuttle' => 'Navette', 'emergency' => 'Véhicule de secours']],
        'food_beverage' => ['label' => 'Food & beverage', 'shape' => 'rectangle', 'color' => '#df7145', 'items' => ['kitchen' => 'Cuisine collective', 'food' => 'Point de restauration', 'bar' => 'Bar', 'water' => 'Point d’eau', 'cold' => 'Chambre froide et frigo', 'storage' => 'Stockage alimentaire', 'tasting' => 'Dégustation', 'pickup' => 'Retrait des repas']],
        'waste' => ['label' => 'Déchets', 'shape' => 'rectangle', 'color' => '#71893b', 'items' => ['bin' => 'Poubelle', 'sorting' => 'Tri', 'glass' => 'Verre', 'organic' => 'Biodéchets', 'oil' => 'Huiles', 'collection' => 'Collecte', 'container' => 'Conteneur', 'cleaning' => 'Nettoyage final']],
        'branding_signage' => ['label' => 'Marque et signalétique', 'shape' => 'rectangle', 'color' => '#d5488e', 'items' => ['welcome' => 'Accueil', 'direction' => 'Flèche', 'map' => 'Plan affiché', 'poster' => 'Affiche', 'banner' => 'Banderole', 'sponsor' => 'Logo sponsor', 'stand' => 'Panneau de stand', 'qr' => 'QR', 'safety' => 'Consigne et sécurité']],
        'barriers' => ['label' => 'Barrières', 'shape' => 'line', 'color' => '#bf4040', 'items' => ['crowd' => 'Barrière de foule', 'fence' => 'Clôture', 'gate' => 'Portillon', 'queue' => 'File d’attente', 'protection' => 'Protection', 'road' => 'Fermeture de voie']],
        'areas' => ['label' => 'Espaces', 'shape' => 'free_polygon', 'color' => '#439575', 'items' => ['public' => 'Zone publique', 'private' => 'Zone privée', 'parking' => 'Stationnement public', 'staff_parking' => 'Stationnement équipes', 'activity' => 'Zone d’activité', 'family' => 'Espace familial', 'storage' => 'Stockage', 'backstage' => 'Coulisses', 'unavailable' => 'Zone indisponible']],
        'routes_accesses' => ['label' => 'Routes et accès', 'shape' => 'free_polygon', 'color' => '#4684bd', 'items' => ['entrance' => 'Entrée publique', 'exit' => 'Sortie publique', 'accessible' => 'Accès accessible', 'emergency' => 'Accès secours', 'service' => 'Accès technique', 'delivery' => 'Livraison', 'pedestrian' => 'Parcours piéton', 'road' => 'Route et emprise']],
        'workforce' => ['label' => 'Workforce QAPAS et sous-traitants', 'shape' => 'circle', 'color' => '#484ab7', 'items' => ['security' => 'Sécurité', 'medical' => 'Médical', 'police' => 'Police', 'fire' => 'Incendie', 'steward' => 'Steward', 'supervisor' => 'Steward supervisor', 'manager' => 'Manager', 'volunteer' => 'Bénévole', 'welcome' => 'Accueil', 'technical' => 'Technique', 'cleaning' => 'Nettoyage', 'logistics' => 'Logistique']],
    ],
];
