<?php

return [
    'fr' => ['account' => 'Mon compte QAPAS', 'home' => 'Accueil QAPAS', 'overview' => 'Vue d’ensemble', 'apps' => 'Applications', 'soon' => 'À venir', 'language' => 'Langue', 'eyebrow' => 'ÉCOSYSTÈME QAPAS', 'hero' => 'Une application, un métier. Un accès clair à tout QAPAS.', 'intro' => 'Ce socle est prêt à accueillir une application autonome. Chaque équipe définit ici son service, ses parcours et ses règles métier.', 'explore' => 'Découvrir QAPAS', 'about' => 'À propos de cette application', 'about_copy' => 'Son contenu métier sera ajouté dans le dépôt de l’application qui utilisera ce template.', 'privacy' => 'Des données séparées, des liens communs', 'privacy_copy' => 'Chaque installation conserve sa base, ses sessions et ses permissions. La barre QAPAS ne transporte que des liens publics.', 'footer' => 'Une application de l’écosystème QAPAS.'],
    'en' => ['account' => 'My QAPAS account', 'home' => 'QAPAS home', 'overview' => 'Overview', 'apps' => 'Applications', 'soon' => 'Coming soon', 'language' => 'Language', 'eyebrow' => 'QAPAS ECOSYSTEM', 'hero' => 'One application, one purpose. A clear path through QAPAS.', 'intro' => 'This foundation is ready for an independent application. Each team defines its service, journeys and domain rules here.', 'explore' => 'Explore QAPAS', 'about' => 'About this application', 'about_copy' => 'Its domain content belongs in the repository of the application built from this template.', 'privacy' => 'Separate data, shared links', 'privacy_copy' => 'Each installation keeps its own database, sessions and permissions. The QAPAS bar carries public links only.', 'footer' => 'An application in the QAPAS ecosystem.'],
    'pt' => ['account' => 'A minha conta QAPAS', 'home' => 'Início QAPAS', 'overview' => 'Visão geral', 'apps' => 'Aplicações', 'soon' => 'Em breve', 'language' => 'Idioma', 'eyebrow' => 'ECOSSISTEMA QAPAS', 'hero' => 'Uma aplicação, uma finalidade. Um caminho claro pelo QAPAS.', 'intro' => 'Esta base está pronta para uma aplicação autónoma. Cada equipa define aqui o seu serviço, percurso e regras de negócio.', 'explore' => 'Conhecer o QAPAS', 'about' => 'Sobre esta aplicação', 'about_copy' => 'O conteúdo próprio fica no repositório da aplicação criada a partir deste modelo.', 'privacy' => 'Dados separados, ligações comuns', 'privacy_copy' => 'Cada instalação guarda a sua base de dados, sessões e permissões. A barra QAPAS contém apenas ligações públicas.', 'footer' => 'Uma aplicação do ecossistema QAPAS.'],
    'nl' => ['account' => 'Mijn QAPAS-account', 'home' => 'QAPAS start', 'overview' => 'Overzicht', 'apps' => 'Toepassingen', 'soon' => 'Binnenkort', 'language' => 'Taal', 'eyebrow' => 'QAPAS ECOSYSTEEM', 'hero' => 'Eén toepassing, één doel. Een duidelijk pad door QAPAS.', 'intro' => 'Deze basis is klaar voor een zelfstandige toepassing. Elk team bepaalt hier zijn dienst en regels.', 'explore' => 'Ontdek QAPAS', 'about' => 'Over deze toepassing', 'about_copy' => 'De inhoud van de toepassing hoort in haar eigen repository.', 'privacy' => 'Afzonderlijke gegevens, gedeelde links', 'privacy_copy' => 'Elke installatie houdt haar eigen database, sessies en rechten. De QAPAS balk bevat alleen openbare links.', 'footer' => 'Een toepassing binnen het QAPAS ecosysteem.'],
    'es' => ['account' => 'Mi cuenta QAPAS', 'home' => 'Inicio QAPAS', 'overview' => 'Vista general', 'apps' => 'Aplicaciones', 'soon' => 'Próximamente', 'language' => 'Idioma', 'eyebrow' => 'ECOSISTEMA QAPAS', 'hero' => 'Una aplicación, un propósito. Un camino claro por QAPAS.', 'intro' => 'Esta base está lista para una aplicación autónoma. Cada equipo define aquí su servicio y sus reglas.', 'explore' => 'Descubrir QAPAS', 'about' => 'Sobre esta aplicación', 'about_copy' => 'Su contenido propio pertenece al repositorio de la aplicación creada con esta plantilla.', 'privacy' => 'Datos separados, enlaces compartidos', 'privacy_copy' => 'Cada instalación conserva su base de datos, sesiones y permisos. La barra QAPAS solo contiene enlaces públicos.', 'footer' => 'Una aplicación del ecosistema QAPAS.'],
    'de' => ['account' => 'Mein QAPAS-Konto', 'home' => 'QAPAS Startseite', 'overview' => 'Überblick', 'apps' => 'Anwendungen', 'soon' => 'Demnächst', 'language' => 'Sprache', 'eyebrow' => 'QAPAS ÖKOSYSTEM', 'hero' => 'Eine Anwendung, ein Zweck. Ein klarer Weg durch QAPAS.', 'intro' => 'Diese Grundlage ist für eine eigenständige Anwendung bereit. Jedes Team definiert hier seinen Dienst und seine Fachregeln.', 'explore' => 'QAPAS entdecken', 'about' => 'Über diese Anwendung', 'about_copy' => 'Fachspezifische Inhalte gehören in das Repository der Anwendung.', 'privacy' => 'Getrennte Daten, gemeinsame Links', 'privacy_copy' => 'Jede Installation hat ihre eigene Datenbank, Sitzungen und Rechte. Die QAPAS Leiste enthält nur öffentliche Links.', 'footer' => 'Eine Anwendung im QAPAS Ökosystem.'],
];
