<div class="planner-two-columns">
    <section class="planner-card"><h2>Catalogue et stocks</h2><table class="planner-table"><thead><tr><th>Produit</th><th>Prix TTC</th><th>Stock</th><th></th></tr></thead><tbody>@foreach($products as $p)<tr><td>{{ $p->name }}<small>{{ $p->sku }} · {{ $p->seller }}</small></td><td>{{ $money::display($p->price_cents) }}</td><td>{{ $p->stock }}</td><td><button wire:click="editProduct({{ $p->id }})">Modifier</button></td></tr>@endforeach</tbody></table></section>
    <section class="planner-card"><h2>Définir un produit</h2><form wire:submit="saveProduct">
        <x-planner-field model="product.sku" label="Référence de variante" /><x-planner-field model="product.name" label="Produit" /><x-planner-field model="product.element_id" label="Point de présentation" :options="$elementOptions" />
        <x-planner-field model="product.seller" label="Vendeur" :options="['organizer'=>'Organisateur','independent'=>'Exposant indépendant']" /><x-planner-field model="product.price" label="Prix TTC en euros" inputmode="decimal" /><x-planner-field model="product.net_price" label="Recette nette de gestion par unité" inputmode="decimal" /><x-planner-field model="product.unit_cost" label="Coût net du produit consommé, si connu" inputmode="decimal" />
        <x-planner-field model="product.description" label="Présentation" type="textarea" /><x-planner-field model="product.is_public" label="Présenter dans la prochaine publication" type="checkbox" /><button class="planner-button">Enregistrer le produit</button>
    </form></section>
</div>
<section class="planner-card"><h2>Réception, vente et retour de stock</h2><p>Chaque mouvement possède une référence unique. Les ventes d’un indépendant restent dans son économie. L’achat du stock est suivi comme approvisionnement ; la consommation du produit est imputée une seule fois au résultat.</p><form wire:submit="recordMovement" class="planner-form-grid">
    <x-planner-field model="movement.product_id" label="Produit" :options="[''=>'Choisir']+$products->pluck('name','id')->all()" /><x-planner-field model="movement.kind" label="Mouvement" :options="['receipt'=>'Réception','sale'=>'Vente réalisée','return'=>'Retour physique sans remboursement','adjustment'=>'Entrée justifiée','loss'=>'Perte de stock','transfer'=>'Transfert']" /><x-planner-field model="movement.quantity" label="Quantité" type="number" min="1" />
    <x-planner-field model="movement.element_id" label="Emplacement (vide = dépôt) ou destination" :options="$elementOptions" /><x-planner-field model="movement.source_element_id" label="Source du transfert (vide = dépôt)" :options="$elementOptions" /><x-planner-field model="movement.reference" label="Référence unique de la pièce ou opération" /><x-planner-field model="movement.reason" label="Justification" type="textarea" /><button class="planner-button">Enregistrer le mouvement</button>
</form></section>
<section class="planner-card"><h2>Disponibilités par emplacement</h2><table class="planner-table"><thead><tr><th>Produit</th><th>Emplacement</th><th>Quantité</th></tr></thead><tbody>@foreach($products as $p)@foreach($p->locations as $location)<tr><td>{{ $p->name }}</td><td>{{ $location->element?->name??'Dépôt' }}</td><td>{{ $location->quantity }}</td></tr>@endforeach@endforeach</tbody></table><p>Un retour physique ne constitue pas une restitution d’argent. Une vente et son éventuel avoir conservent leurs pièces de rapprochement.</p></section>
