<x-layout :title="$plan['event']['name']">
    @vite(['resources/css/event-planner.css','resources/js/planner-map.js'])
    @php
        $public=$plan['event']; $lang=app()->getLocale(); $phase=$public['phase'];
        $copy=$public['phase_copy'][$phase][$lang]??$public['phase_copy'][$phase]['fr']??[];
        $title=$copy['title']??config('event_planner.phases.'.$phase);
        $message=$copy['message']??($public['description'][$lang]??$public['description']['fr']??'');
        $money=\App\Services\Events\Money::class;
        $features=$plan['plan']['features'];
        $exceptional=in_array($public['decision'],['not_confirmed','cancelled'],true);
        if($exceptional){$title='Édition non confirmée';$message='Cette édition n’est pas confirmée. Les offres sont fermées ; consultez les informations sur les engagements concernés.';}
    @endphp
    <div class="planner-public">
        @if($public['is_demo'])<p class="planner-notice">Démonstration Farmers Games : implantation illustrative et offres proposées. Cette page ne confirme aucun événement ni disponibilité réelle.</p>@endif
        @if(session('proposal_received'))<p role="status" class="planner-notice">Votre proposition est enregistrée. L’organisation doit encore l’examiner ; aucune commande ou place n’est confirmée.</p>@endif
        @if($exceptional)<p role="status" class="planner-notice">Cette édition n’a pas été confirmée ou a été retirée. Les engagements concernés suivent leurs conditions de restitution. Les offres sont fermées.</p>@endif
        @if($public['status_changed'])<p class="planner-notice">Le statut de préparation a changé. Une nouvelle version du plan et de ses supports attend sa publication.</p>@endif
        <section class="planner-public-hero"><div><span class="planner-badge">{{ $title }}</span><h1>{{ $public['name'] }}</h1><p>{{ $message }}</p><p>{{ $public['venue'] }}@if($public['starts_at']) · {{ \Carbon\CarbonImmutable::parse($public['starts_at'])->timezone($public['timezone'])->format('d/m/Y') }}@if($public['ends_at']) – {{ \Carbon\CarbonImmutable::parse($public['ends_at'])->timezone($public['timezone'])->format('d/m/Y') }}@endif @if($public['decision']!=='confirmed') · Dates proposées @endif @endif</p><div class="planner-actions"><a class="planner-button" href="#tour">Explorer la visite</a><a class="planner-button secondary" href="#offers">Voir les possibilités</a></div>@if($public['decision_deadline']&&$public['decision']==='pending')<p>Décision annoncée au plus tard le {{ \Carbon\CarbonImmutable::parse($public['decision_deadline'])->timezone($public['timezone'])->format('d/m/Y à H:i') }}.</p>@endif</div><div class="planner-public-art" aria-hidden="true"><svg viewBox="0 0 200 200"><path d="M25 130h150M40 130V75l30-30 30 30v55M115 130V60l25-20 25 20v70" stroke="#d7efaf" stroke-width="5" fill="none"/><circle cx="73" cy="108" r="12" fill="#94b673"/><path d="M66 93V80m14 13V80M57 153h85" stroke="#d7efaf" stroke-width="5" stroke-linecap="round"/></svg></div></section>
        <section class="planner-public-map" aria-label="Plan de la visite"><div data-planner-map data-api="{{ route('events.data',$event->slug) }}" data-center="{{ json_encode($plan['center']) }}"><div class="planner-map" aria-label="Carte interactive"></div></div><aside class="planner-card"><h2>Votre parcours</h2><label class="planner-field"><span>Rechercher un lieu ou une activité</span><input type="search" data-plan-search></label><label class="planner-field"><span>Catégorie</span><select data-plan-category><option value="">Tout découvrir</option>@foreach(config('event_planner.categories') as $key=>$category)<option value="{{ $key }}">{{ $category['label'] }}</option>@endforeach</select></label><div class="planner-public-list">@foreach($features as $feature)<button data-focus-element="{{ $feature['properties']['uuid'] }}">{{ $feature['properties']['name'] }}</button>@endforeach</div></aside></section>
        <div class="planner-actions" style="margin-top:1rem"><a class="planner-button secondary" href="{{ route('events.geojson',$event->slug) }}">GeoJSON</a><a class="planner-button secondary" href="{{ route('events.svg',$event->slug) }}">Plan vectoriel SVG</a><a class="planner-button secondary" href="{{ route('events.pdf',$event->slug) }}">Plan PDF A3</a><button class="planner-button secondary" data-export-png="{{ route('events.svg',$event->slug) }}" data-filename="{{ $event->slug }}-plan.png">Plan PNG</button><a class="planner-button secondary" href="{{ route('events.poster',$event->slug) }}">Voir et imprimer l’affiche</a><button class="planner-button secondary" onclick="window.print()">Imprimer la visite</button></div>
        <h2 class="planner-section-title" id="tour">La visite guidée</h2><p>Choisissez les étapes qui vous intéressent et préparez votre venue. Les horaires et accès publiés restent à vérifier avant le déplacement.</p>
        <div class="planner-tour">@foreach($features as $feature)@php($item=$feature['properties'])<article class="planner-card planner-stop" id="stop-{{ $item['uuid'] }}"><span class="planner-badge">{{ config('event_planner.categories.'.$item['category'].'.label') }}</span><h3>{{ $item['name'] }}</h3><p>{{ $item['description'] }}</p>@if($item['four_ps']['promotion'])<p>{{ $item['four_ps']['promotion'] }}</p>@endif@if($item['public_price'])<p><strong>{{ $item['public_price'] }}</strong></p>@endif@if($item['hours'])<p>{{ $item['hours'] }}</p>@endif@if($item['access'])<p>{{ $item['access'] }}</p>@endif<button class="planner-button secondary" data-focus-element="{{ $item['uuid'] }}">Situer sur le plan</button></article>@endforeach</div>
        <h2 class="planner-section-title" id="offers">Les possibilités encore disponibles</h2><div class="planner-offers">
            @forelse($plan['offers'] as $offer)<article class="planner-card"><span class="planner-badge">{{ config('event_planner.audiences.'.$offer['audience']) }}</span><h3>{{ $offer['name'] }}</h3><p>{{ $offer['description'] }}</p><div class="planner-offer-price">{{ $money::display($offer['price_cents'],$public['currency']) }} TTC</div><p>{{ $offer['included'] }}</p><p>{{ $offer['conditions'] }}</p>@if($offer['available'])<p>{{ $offer['remaining']===null?'Disponibilité sur proposition':$offer['remaining'].' unité(s) proposées' }}</p><a class="planner-button" href="{{ route('events.candidate',[$event->slug,$offer['uuid']]) }}">Présenter une proposition</a>@else<p>Propositions fermées ou capacité indisponible.</p>@endif</article>@empty<p>Les offres seront présentées après leur publication.</p>@endforelse
        </div>
        @if($plan['products'])<h2 class="planner-section-title">Produits proposés par les vendeurs</h2><div class="planner-offers">@foreach($plan['products'] as $product)<article class="planner-card"><h3>{{ $product['name'] }}</h3><p>{{ $product['description'] }}</p><strong>{{ $money::display($product['price_cents'],$public['currency']) }} TTC</strong><p>{{ $product['available']?'Disponible auprès du vendeur indiqué sur le plan':'Stock actuellement indisponible' }}</p></article>@endforeach</div>@endif
        <h2 class="planner-section-title" id="faq">Les réponses à vos questions</h2>@foreach($public['faq'] as $faq)<details><summary>{{ $faq['question'][$lang]??$faq['question']['fr']??'' }}</summary><p>{{ $faq['answer'][$lang]??$faq['answer']['fr']??'' }}</p></details>@endforeach
        <p style="margin-top:2rem">Plan publié le {{ \Carbon\CarbonImmutable::parse($plan['publication']['published_at'])->format('d/m/Y') }} · version {{ $plan['publication']['number'] }}.</p>
    </div>
</x-layout>
