<?php

// Questions propres à A Forqua de Ouro. Filament peut ensuite les éditer sans modifier ce fichier.
return [
    'items' => [
        'weekend' => [
            'question' => [
                'fr' => 'Quand et où se déroulent les Jeux ?',
                'pt' => 'Quando e onde decorrem os Jogos?',
                'en' => 'When and where are the Games?',
                'nl' => 'Wanneer en waar zijn de Spelen?',
                'es' => '¿Cuándo y dónde se celebran los Juegos?',
                'de' => 'Wann und wo finden die Spiele statt?',
            ],
            'answer' => [
                'fr' => 'La première édition d’A Forqua de Ouro est prévue les 12 et 13 décembre 2026 à Aldeia do Souto, entre Belmonte, Manteigas, Covilhã et Guarda. Les horaires et emplacements non confirmés sont indiqués comme tels dans le programme.',
                'pt' => 'A primeira edição de A Forqua de Ouro está prevista para 12 e 13 de dezembro de 2026 em Aldeia do Souto, entre Belmonte, Manteigas, Covilhã e Guarda. Os horários e locais por confirmar são identificados no programa.',
                'en' => 'The first edition of A Forqua de Ouro is planned for 12–13 December 2026 in Aldeia do Souto, between Belmonte, Manteigas, Covilhã and Guarda. Unconfirmed times and locations are marked in the programme.',
                'nl' => 'De eerste editie van A Forqua de Ouro is gepland op 12 en 13 december 2026 in Aldeia do Souto. Nog niet bevestigde tijden en locaties staan als zodanig in het programma.',
                'es' => 'La primera edición de A Forqua de Ouro está prevista para el 12 y 13 de diciembre de 2026 en Aldeia do Souto. Los horarios y lugares pendientes figuran como tales en el programa.',
                'de' => 'Die erste Ausgabe von A Forqua de Ouro ist für den 12. und 13. Dezember 2026 in Aldeia do Souto geplant. Noch nicht bestätigte Zeiten und Orte sind im Programm gekennzeichnet.',
            ],
        ],
        'team' => [
            'question' => [
                'fr' => 'Comment rejoindre l’équipe de mon village ?',
                'pt' => 'Como posso entrar na equipa da minha freguesia?',
                'en' => 'How do I join my village team?',
                'nl' => 'Hoe sluit ik mij aan bij mijn dorpsteam?',
                'es' => '¿Cómo me uno al equipo de mi pueblo?',
                'de' => 'Wie trete ich meinem Dorfteam bei?',
            ],
            'answer' => [
                'fr' => 'Choisissez votre freguesia dans « Rejoindre l’aventure », puis proposez votre candidature pour l’un des 24 postes. Il existe une seule équipe par village ; les candidatures restent ouvertes même si aucun lieu relais n’a encore été confirmé. QAPAS confirme les places après examen.',
                'pt' => 'Escolha a freguesia em « Juntar-me à aventura » e candidate-se a uma das 24 funções. Há uma só equipa por freguesia; as candidaturas estão abertas mesmo sem um ponto de informação confirmado. A QAPAS confirma os lugares após análise.',
                'en' => 'Choose your village in Join the adventure and apply for one of the 24 roles. There is one team per village; applications remain open even without a confirmed local relay. QAPAS confirms places after review.',
                'nl' => 'Kies je dorp bij \'Doe mee\' en meld je aan voor een van de 24 rollen. Er is één team per dorp; aanmelding kan ook zonder bevestigd informatiepunt. QAPAS bevestigt de plaatsen na beoordeling.',
                'es' => 'Elige tu freguesia en « Unirme a la aventura » y solicita uno de los 24 puestos. Hay un equipo por pueblo; puedes presentarte aunque no haya un punto de información confirmado. QAPAS confirma las plazas.',
                'de' => 'Wähle dein Dorf unter \'Mitmachen\' und bewirb dich für eine der 24 Aufgaben. Es gibt ein Team pro Dorf; Bewerbungen sind auch ohne bestätigte Anlaufstelle möglich. QAPAS bestätigt die Plätze nach Prüfung.',
            ],
        ],
        'challenges' => [
            'question' => [
                'fr' => 'Tous les stands organisent-ils une épreuve ?',
                'pt' => 'Todas as bancas organizam uma prova?',
                'en' => 'Does every stand run a scored challenge?',
                'nl' => 'Heeft elke stand een wedstrijd?',
                'es' => '¿Todos los puestos organizan una prueba?',
                'de' => 'Hat jeder Stand einen Wettbewerb?',
            ],
            'answer' => [
                'fr' => 'Non. Chaque village participant prépare un stand avec un défi officiel que les autres équipes relèvent. Les stands indépendants proposent des produits, savoir-faire ou animations sans points pour la Fourche d’or. Les règles du défi sont validées par QAPAS.',
                'pt' => 'Não. Cada freguesia participante prepara uma banca com uma prova oficial para as outras equipas. As bancas independentes oferecem produtos, ofícios ou animações sem pontos para a Forquilha de Ouro. A QAPAS valida as regras.',
                'en' => 'No. Each participating village hosts one official challenge for the other teams. Independent stands offer products, skills or activities without scores for the Golden Fork. QAPAS validates the challenge rules.',
                'nl' => 'Nee. Elk deelnemend dorp organiseert één officiële proef voor de andere teams. Onafhankelijke stands bieden producten of activiteiten zonder wedstrijdpunten. QAPAS keurt de regels goed.',
                'es' => 'No. Cada pueblo participante prepara una prueba oficial para los demás equipos. Los puestos independientes ofrecen productos o actividades sin puntos para el premio. QAPAS valida las reglas.',
                'de' => 'Nein. Jedes teilnehmende Dorf bereitet eine offizielle Aufgabe für die anderen Teams vor. Unabhängige Stände bieten Produkte oder Aktivitäten ohne Wertung an. QAPAS bestätigt die Regeln.',
            ],
        ],
        'relays' => [
            'question' => [
                'fr' => 'Mon commerce peut-il devenir lieu relais si un café participe déjà ?',
                'pt' => 'O meu comércio pode ser ponto de informação se já houver um café?',
                'en' => 'Can my shop be a village relay if a café already joined?',
                'nl' => 'Kan mijn winkel meedoen als er al een café is?',
                'es' => '¿Puede mi comercio ser punto de información si ya hay un café?',
                'de' => 'Kann mein Geschäft mitmachen, wenn es bereits ein Café gibt?',
            ],
            'answer' => [
                'fr' => 'Oui. Cafés, épiceries, commerces et associations peuvent se proposer dans la freguesia choisie sur « Rejoindre l’aventure ». QAPAS retient les lieux pertinents pour le parcours local, sans quota automatique par village. QAPAS vérifie l’accord et les informations de chaque lieu avant publication.',
                'pt' => 'Sim. Cafés, mercearias, lojas e associações podem propor-se na freguesia escolhida em « Juntar-me à aventura ». Não há limite de um ponto por freguesia. A QAPAS verifica o acordo e os dados antes de publicar.',
                'en' => 'Yes. Cafés, grocers, shops and associations can apply in their village through Join the adventure. QAPAS selects suitable venues for the local route, without an automatic one-relay quota. QAPAS checks each venue\'s consent and details before publication.',
                'nl' => 'Ja. Cafés, buurtwinkels en verenigingen kunnen zich via \'Doe mee\' aanmelden. Er is geen maximum van één locatie per dorp. QAPAS controleert toestemming en gegevens vóór publicatie.',
                'es' => 'Sí. Cafés, tiendas y asociaciones pueden proponerse desde « Unirme a la aventura ». No hay un límite de un punto por pueblo. QAPAS verifica el acuerdo y los datos antes de publicarlos.',
                'de' => 'Ja. Cafés, Läden und Vereine können sich über \'Mitmachen\' melden. Es gibt keine Begrenzung auf eine Anlaufstelle pro Dorf. QAPAS prüft Zustimmung und Angaben vor der Veröffentlichung.',
            ],
        ],
        'relay_contribution' => [
            'question' => [
                'fr' => 'Combien coûte l’inscription d’un point relais et quand figure-t-il dans la liste ?',
                'pt' => 'Quanto custa inscrever um ponto de informação e quando aparece na lista?',
                'en' => 'How much does a village relay pay and when is it listed?',
                'nl' => 'Wat kost een informatiepunt en wanneer wordt het vermeld?',
                'es' => '¿Cuánto cuesta inscribir un punto de información y cuándo se publica?',
                'de' => 'Was kostet eine Anlaufstelle und wann wird sie aufgeführt?',
            ],
            'answer' => [
                'fr' => 'La participation est de 50 € TTC minimum par lieu et par édition. Après la demande, QAPAS envoie automatiquement par courriel une invitation personnelle au paiement sécurisé. Le paiement seul ne suffit pas : le lieu figure dans la liste de sa freguesia après confirmation du règlement, accord du responsable et vérification des informations par QAPAS. L’organisateur remet la facture correspondante après encaissement.',
                'pt' => 'A inscrição custa no mínimo 50 € com IVA incluído, por local e por edição. Após a candidatura, a QAPAS envia por email um convite pessoal para pagamento seguro. O pagamento não basta: o ponto entra na lista da freguesia após confirmação do pagamento, autorização do responsável e verificação dos dados pela QAPAS. A organização emite a fatura após o recebimento.',
                'en' => 'The fee is at least €50 including VAT per venue and edition. QAPAS emails a personal secure payment invitation after the application. Listing follows verified payment, venue consent and review by QAPAS. The organiser issues the invoice after receiving payment.',
                'nl' => 'De bijdrage bedraagt minimaal € 50 inclusief btw per locatie en editie. QAPAS mailt na de aanvraag een persoonlijke betaallink. Vermelding volgt na bevestigde betaling, toestemming van de locatie en controle door QAPAS. De organisator verstrekt de factuur na ontvangst.',
                'es' => 'La cuota es de al menos 50 € IVA incluido por local y edición. QAPAS envía por correo una invitación personal de pago seguro. El local aparece tras confirmar el pago, obtener su consentimiento y verificar sus datos. La organización entrega la factura después del cobro.',
                'de' => 'Der Beitrag beträgt mindestens 50 € einschließlich Mehrwertsteuer je Ort und Ausgabe. QAPAS sendet nach der Anmeldung per E-Mail eine persönliche Zahlungseinladung. Die Aufnahme erfolgt nach bestätigter Zahlung, Zustimmung des Orts und Prüfung der Angaben. Der Veranstalter stellt danach die Rechnung aus.',
            ],
        ],
        'village_funding' => [
            'question' => [
                'fr' => 'Comment financer la participation de ma freguesia ?',
                'pt' => 'Como financiar a participação da minha freguesia?',
                'en' => 'How can my village fund its participation?',
                'nl' => 'Hoe financiert ons dorp de deelname?',
                'es' => '¿Cómo financia mi pueblo su participación?',
                'de' => 'Wie finanziert mein Dorf die Teilnahme?',
            ],
            'answer' => [
                'fr' => 'L’équipe désigne un comptable certifié pour suivre sa caisse. Si elle n’en a pas, QAPAS propose un professionnel mandaté pour une mission précisément décrite. Son forfait négocié à l’avance est annoncé dans le prix de participation avant paiement, avec le mandat et les règles de remboursement. QAPAS vise une répercussion sans marge cachée : sa facture à l’équipe et celle du comptable sont rapprochées, sans présumer que leur différence comptable ou fiscale sera nulle. TVA, émetteur des factures et flux sont validés par le comptable officiel. Les avances, dons définitifs et honoraires restent enregistrés séparément ; aucune compensation informelle. Aucun montant n’est fixé à ce jour.',
                'pt' => 'A equipa designa um contabilista certificado para acompanhar as contas. Na sua falta, a QAPAS propõe um profissional com missão delimitada. O valor fixo negociado previamente integra o preço de participação anunciado antes do pagamento, com mandato e regras de reembolso. A QAPAS pretende repercutir o custo sem margem oculta; as duas faturas são reconciliadas, sem presumir saldo contabilístico ou fiscal nulo. IVA, faturação e fluxos são validados pelo contabilista oficial. Adiantamentos, donativos e honorários ficam separados. Ainda não há preço aprovado.',
                'en' => 'The team appoints an accounting professional. If unavailable, QAPAS proposes a professional for a defined assignment. A negotiated fixed fee is disclosed within participation costs before payment, with scope and refund terms. QAPAS aims to pass through the cost without hidden margin; the two invoices are reconciled, without assuming a zero accounting or tax difference. Its accountant validates VAT and billing. Advances, gifts and fees remain separate. No price is approved yet.',
                'nl' => 'Het team benoemt een boekhoudprofessional. Zo niet, dan stelt QAPAS een afgebakende opdracht tegen vooraf overeengekomen vaste prijs voor, opgenomen in de deelnamekosten vóór betaling. Kosten worden zonder verborgen marge doorgerekend; de btw en facturatie worden gecontroleerd. Een nulsaldo wordt niet beloofd. Er is nog geen prijs vastgesteld.',
                'es' => 'El equipo designa un profesional contable; si no lo tiene, QAPAS propone una misión delimitada con tarifa fija pactada previamente e incluida en el precio comunicado antes del pago. Se busca repercutir el coste sin margen oculta. El contable valida IVA y facturas: no se promete saldo fiscal cero. Aún no hay precio aprobado.',
                'de' => 'Das Team benennt eine Buchhaltungsfachkraft. Fehlt sie, bietet QAPAS einen begrenzten Auftrag zum vorab vereinbarten Festpreis an, der vor Zahlung im Teilnahmebetrag ausgewiesen wird. Ziel ist Kostenweitergabe ohne versteckte Marge. Rechnungen und Steuerfragen prüft die Fachkraft; ein Nullsaldo wird nicht zugesagt. Ein Preis ist noch nicht festgelegt.',
            ],
        ],
        'sponsors' => [
            'question' => [
                'fr' => 'Que devient l’argent versé par un sponsor de village ?',
                'pt' => 'O que acontece ao dinheiro de um patrocinador da freguesia?',
                'en' => 'What happens to a village sponsor\'s payment?',
                'nl' => 'Wat gebeurt er met de bijdrage van een dorpssponsor?',
                'es' => '¿Qué ocurre con el pago de un patrocinador del pueblo?',
                'de' => 'Was geschieht mit dem Beitrag eines Dorfsponsors?',
            ],
            'answer' => [
                'fr' => 'Le sponsor paie QAPAS, qui lui facture la prestation convenue en identifiant le stand aidé. Le versement encaissé est inscrit avec sa référence dans le suivi de ce stand ; QAPAS conserve les factures d’achat du matériel et réduit une seule fois le montant dû par l’équipe. L’équipe ne reçoit pas de liquidités. Si sa facture était déjà émise, la correction suit le circuit de facturation. Le comptable professionnel mandaté par l’équipe, ou par QAPAS à défaut, rapproche versement, affectation, achats et réduction. Les totaux vérifiés sont communiqués à l’équipe et publiés sans données privées ; les justificatifs restent consultables par les personnes habilitées. La séparation des pièces et des contrôles rend les écarts détectables et contestables.',
                'pt' => 'O patrocinador paga à QAPAS, que fatura o serviço acordado identificando a banca apoiada. O recebimento fica registado com referência; a QAPAS guarda as faturas das compras e reduz uma só vez o valor devido pela equipa. A equipa não recebe dinheiro. Uma fatura já emitida é retificada no circuito de faturação. O profissional de contabilidade mandatado pela equipa, ou pela QAPAS na sua falta, reconcilia pagamento, afetação, compras e desconto. Os totais verificados são comunicados à equipa e publicados sem dados privados; os comprovativos ficam acessíveis aos responsáveis autorizados.',
                'en' => 'The sponsor pays QAPAS, which invoices the agreed service naming the supported stand. Receipt, allocation, purchase invoices and the single reduction in the team\'s amount due are recorded. The team receives no cash. A previously issued team invoice is corrected through the invoicing process. The team\'s accounting professional, or one appointed by QAPAS, reconciles the records. Verified totals are shared with the team and published without private data; authorised people may inspect the supporting documents.',
                'nl' => 'De sponsor betaalt QAPAS, dat de afgesproken prestatie factureert met vermelding van de gesteunde stand. Ontvangst, toewijzing, inkoopfacturen en de eenmalige vermindering voor het team worden vastgelegd. Het team ontvangt geen geld. De boekhouder van het team, of die van QAPAS, controleert de aansluiting. Geverifieerde totalen zijn openbaar zonder privégegevens; bevoegden kunnen de bewijsstukken inzien.',
                'es' => 'El patrocinador paga a QAPAS, que factura la prestación identificando el puesto apoyado. Se registran cobro, destino, facturas de compra y una única reducción de la deuda del equipo. El equipo no recibe efectivo. El contable profesional del equipo, o el designado por QAPAS, concilia los documentos. Se publican totales verificados sin datos privados; las personas autorizadas pueden consultar los justificantes.',
                'de' => 'Der Sponsor zahlt an QAPAS, das die vereinbarte Leistung mit Angabe des geförderten Stands berechnet. Zahlung, Verwendung, Einkaufsrechnungen und die einmalige Minderung für das Team werden erfasst. Das Team erhält kein Bargeld. Die Buchhaltungsfachkraft des Teams oder von QAPAS gleicht die Belege ab. Geprüfte Summen werden ohne private Daten veröffentlicht; Berechtigte können Belege einsehen.',
            ],
        ],
        'village_plan' => [
            'question' => [
                'fr' => 'Comment notre équipe peut-elle couvrir ses frais sans vendre du rêve ?',
                'pt' => 'Como pode a nossa equipa cobrir as despesas sem prometer lucros?',
                'en' => 'How can our team cover its costs without promising profit?',
                'nl' => 'Hoe kan ons team de kosten dekken zonder winst te beloven?',
                'es' => '¿Cómo cubrir los gastos sin prometer beneficios?',
                'de' => 'Wie deckt unser Team die Kosten, ohne Gewinn zu versprechen?',
            ],
            'answer' => [
                'fr' => 'Un petit plan en 4 P : Projet (équipe, défi, plat et stand), Prix (inscription, kit, transport, cuisine et marge nette par plat), Place (relais du village, stand officiel et cuisine collective), Promotion (habitants, commerces, partenaires et interviews QAPAS). Le trésorier comptable calcule le reste à couvrir après dons définitivement acquis et réduction du matériel financé par les sponsors réellement encaissés. Il divise ce solde par la marge nette d’un plat pour estimer le nombre de ventes nécessaires, sans garantir la fréquentation. Prix et enchères du banc ne comptent qu’une fois attribués et versés ; ils servent en priorité à défrayer les avances justifiées selon les règles écrites. Le but est de participer et de limiter les frais ; les liens entre habitants et la visibilité ont une valeur réelle, mais pas une valeur de caisse.',
                'pt' => 'Plano simples dos 4 P: Projeto (equipa, prova, prato e banca), Preço (inscrição, banca, transporte, cozinha e margem líquida), Praça (pontos de informação, prova e cozinha coletiva), Promoção (habitantes, comércio, parceiros e entrevistas da QAPAS). O contabilista calcula o valor por cobrir depois dos donativos definitivamente adquiridos e do desconto do material pago por patrocinadores recebidos. Divide-o pela margem líquida por prato para estimar vendas necessárias, sem garantir visitantes. Prémios e leilões do banco só contam após atribuição e recebimento e ajudam primeiro a reembolsar despesas documentadas. O objetivo é participar com custos controlados; os laços e a visibilidade não entram na caixa.',
                'en' => 'Use four Ps: Project (team, challenge, dish, stand), Price (registration, materials, travel, kitchen and net margin), Place (village relays, official stand and shared kitchen), Promotion (residents, shops, partners and QAPAS interviews). The accounting professional calculates the gap after unconditional gifts and paid sponsorship deductions, then divides it by net margin per dish to estimate sales needed. Attendance is uncertain. Bench prizes and auction proceeds count only after award and actual receipt; they first reimburse documented advances under written rules. The goal is controlled participation costs; friendships and visibility have real value but are not cash.',
                'nl' => 'Maak een plan met vier P’s: Project, Prijs, Plaats en Promotie. De boekhouder berekent het tekort na definitieve bijdragen en ontvangen sponsoring en deelt dit door de nettomarge per gerecht. Publiek, prijzen en veilingen zijn niet gegarandeerd. Gedocumenteerde voorschotten worden volgens schriftelijke afspraken eerst vergoed.',
                'es' => 'Plan de cuatro P: Proyecto, Precio, Plaza y Promoción. El contable calcula los costes pendientes tras donativos definitivos y patrocinio cobrado; los divide por el margen neto de cada plato. Asistencia, premios y subastas no están garantizados. Los adelantos justificados se reembolsan primero según el acuerdo escrito.',
                'de' => 'Plan mit vier P: Projekt, Preis, Platz und Promotion. Die Buchhaltung berechnet die Restkosten nach endgültigen Spenden und eingegangenen Sponsorengeldern und teilt sie durch die Nettomarge je Gericht. Gäste, Preise und Auktionen sind nicht garantiert. Belegte Vorschüsse werden nach schriftlicher Vereinbarung zuerst erstattet.',
            ],
        ],
        'independent_stand' => [
            'question' => [
                'fr' => 'Comment savoir si mon stand indépendant peut couvrir ses frais ?',
                'pt' => 'Como saber se a minha banca independente cobre os custos?',
                'en' => 'How can I tell whether an independent stand covers its costs?',
                'nl' => 'Hoe weet ik of mijn eigen stand de kosten dekt?',
                'es' => '¿Cómo sé si mi puesto independiente cubre los gastos?',
                'de' => 'Wie erkenne ich, ob mein eigener Stand kostendeckend ist?',
            ],
            'answer' => [
                'fr' => 'Additionnez l’emplacement, le matériel, le transport et les frais d’exploitation, puis estimez la marge par vente après coûts variables. Le nombre minimal de ventes est le coût restant à couvrir divisé par cette marge, si elle est positive. Les tarifs et conditions doivent être confirmés par QAPAS avant engagement. Aucun autre stand de restauration n’est prévu hors la friterie QAPAS et le stand collectif des villages.',
                'pt' => 'Some espaço, material, transporte e exploração; estime a margem por venda após os custos variáveis. As vendas necessárias correspondem ao custo por cobrir dividido por essa margem, se for positiva. A QAPAS confirma preços e condições antes do compromisso. A restauração limita-se à banca coletiva das freguesias e à casa de batatas fritas QAPAS.',
                'en' => 'Add space, materials, transport and operating costs, then estimate the margin per sale after variable costs. Required sales equal the remaining fixed cost divided by that margin, if positive. QAPAS confirms prices and terms before commitment. Food is limited to the shared village kitchen and QAPAS fries stand.',
                'nl' => 'Tel plaats, materiaal, vervoer en bedrijfskosten op. Schat de marge per verkoop na variabele kosten. Benodigde verkopen zijn de resterende vaste kosten gedeeld door die marge, als die positief is. QAPAS bevestigt tarieven en voorwaarden vooraf. Eten komt alleen van de dorpskeuken en QAPAS-frietkraam.',
                'es' => 'Suma espacio, material, transporte y operación. Calcula el margen por venta tras los costes variables. Las ventas necesarias son los costes fijos pendientes divididos por ese margen, si es positivo. QAPAS confirma precios y condiciones antes del compromiso. La comida corresponde a la cocina compartida y la freiduría QAPAS.',
                'de' => 'Addiere Platz, Material, Transport und Betriebskosten. Schätze die Marge je Verkauf nach variablen Kosten. Nötige Verkäufe sind die offenen Fixkosten geteilt durch diese Marge, sofern sie positiv ist. QAPAS bestätigt Preise und Bedingungen vor einer Zusage. Essen bieten nur die Dorfküche und der QAPAS-Pommesstand.',
            ],
        ],
        'kitchen' => [
            'question' => [
                'fr' => 'Puis-je vendre le plat de mon village ?',
                'pt' => 'Posso vender o prato da minha freguesia?',
                'en' => 'Can I sell my village dish?',
                'nl' => 'Kan ik het gerecht van mijn dorp verkopen?',
                'es' => '¿Puedo vender el plato de mi pueblo?',
                'de' => 'Kann ich das Dorfgericht verkaufen?',
            ],
            'answer' => [
                'fr' => 'Oui, sans obligation pour une équipe de village. Proposez une cuisinière, un cuisinier ou un restaurant lié au village ; les places et les recettes chaudes ou froides sont coordonnées. Le client paie au comptoir QAPAS et reçoit un ticket au prix du plat : aucun encaissement dans la cuisine. QAPAS prélève sa commission une seule fois sur le ticket. La part de l’équipe, les justificatifs, le sort des tickets inutilisés et les éventuels frais de place sont annoncés par écrit avant confirmation. Le code est validé une seule fois, puis le support détruit après le service ; les ventes et consommations sont rapprochées en direct.',
                'pt' => 'Sim, sem obrigação para uma equipa. Proponha uma cozinheira, um cozinheiro ou restaurante da freguesia. O cliente paga no balcão QAPAS e recebe um bilhete ao preço do prato; a cozinha não cobra. A comissão incide uma vez por bilhete. A parte da equipa, os comprovativos, os bilhetes não usados e eventuais custos do lugar são acordados por escrito. O bilhete é validado uma vez e destruído após servir.',
                'en' => 'Yes, but cooking is optional for each village team. The customer buys a priced ticket from QAPAS, never paying in the kitchen. The QAPAS commission is charged once per ticket. Team proceeds, receipts, unused tickets and any space fee are agreed in writing first. The code is redeemed once and the paper destroyed after service.',
                'nl' => 'Ja, vrijwillig. De klant koopt een maaltijdticket bij QAPAS en betaalt nooit in de keuken. De commissie wordt eenmaal ingehouden; afrekening en ongebruikte tickets worden vooraf schriftelijk geregeld.',
                'es' => 'Sí, voluntariamente. El cliente compra el vale a QAPAS y no paga en la cocina. La comisión se aplica una sola vez; reparto y vales no usados se acuerdan por escrito.',
                'de' => 'Ja, freiwillig. Gäste kaufen Speisetickets bei QAPAS, nicht in der Küche. Die Provision fällt einmal an; Verteilung und ungenutzte Tickets werden vorher schriftlich geregelt.',
            ],
        ],
        'kit' => [
            'question' => [
                'fr' => 'Que devient le stand du village après les Jeux ?',
                'pt' => 'O que acontece à banca da freguesia após os Jogos?',
                'en' => 'What happens to the village stand after the Games?',
                'nl' => 'Wat gebeurt er na de Spelen met de dorpsstand?',
                'es' => '¿Qué pasa con el puesto del pueblo después de los Juegos?',
                'de' => 'Was geschieht nach den Spielen mit dem Dorfstand?',
            ],
            'answer' => [
                'fr' => 'L’équipe peut financer le kit, le démonter et le réutiliser ailleurs ou lors d’une autre édition. Elle peut aussi choisir une location annoncée à la moitié du coût réel vérifié du kit et le restituer. Le coût, la propriété et la réduction liée aux sponsors doivent être convenus avant toute dépense.',
                'pt' => 'A equipa pode financiar o kit, desmontá-lo e reutilizá-lo noutro local ou edição. Também pode optar por alugá-lo por metade do custo real verificado e devolvê-lo. Custo, propriedade e apoio dos patrocinadores são acordados antes da despesa.',
                'en' => 'The team may fund, dismantle and reuse its kit elsewhere or next year. It may instead rent the kit for half its verified actual cost and return it. Cost, ownership and sponsor reductions are agreed before spending.',
                'nl' => 'Het team kan de bouwset betalen, demonteren en later hergebruiken. Het kan de set ook huren voor de helft van de gecontroleerde werkelijke kostprijs en teruggeven. Kosten, eigendom en sponsorkorting worden vooraf afgesproken.',
                'es' => 'El equipo puede financiar el kit, desmontarlo y reutilizarlo. También puede alquilarlo por la mitad de su coste real verificado y devolverlo. Coste, propiedad y ayuda de patrocinadores se acuerdan antes de gastar.',
                'de' => 'Das Team kann den Bausatz bezahlen, abbauen und wiederverwenden. Alternativ kann es ihn für die Hälfte der geprüften tatsächlichen Kosten mieten und zurückgeben. Kosten, Eigentum und Sponsorennachlass werden vorab vereinbart.',
            ],
        ],
        'documents' => [
            'question' => [
                'fr' => 'Où trouver l’affiche, les tracts et les formulaires ?',
                'pt' => 'Onde estão o cartaz, os folhetos e os formulários?',
                'en' => 'Where are the poster, flyers and forms?',
                'nl' => 'Waar vind ik affiches en formulieren?',
                'es' => '¿Dónde están los carteles y formularios?',
                'de' => 'Wo finde ich Plakat und Formulare?',
            ],
            'answer' => [
                'fr' => 'Le menu Documents utiles rassemble le plan indicatif du stand, l’affiche A4, les tracts publics A5/A6 à découper, les points relais approuvés, le courrier aux sponsors et une note de frais vierge. Demandez l’accord du magasin ou du lieu avant distribution. Les tracts publics ne permettent aucune collecte d’argent ; les tracts officiels d’une équipe sont numérotés et réservés aux personnes mandatées après validation de l’inscription.',
                'pt' => 'O menu Documentos úteis reúne o plano indicativo da banca, cartaz A4, folhetos públicos A5/A6, pontos de informação aprovados, carta aos parceiros e nota de despesas. Peça autorização ao local antes de distribuir. Os folhetos públicos não autorizam recolhas de dinheiro; os oficiais de uma equipa são numerados e reservados a membros mandatados após confirmação.',
                'en' => 'Useful documents contains the stand outline, A4 poster, public A5/A6 flyers, approved relays, sponsor letter and expense form. Obtain venue permission to distribute. Public flyers do not authorise fundraising; numbered team flyers are only issued to authorised members after confirmation.',
                'nl' => 'Bij Nuttige documenten staan standplan, poster, flyers, bevestigde contactpunten, sponsorbrief en kostenformulier. Vraag toestemming voor verspreiding. Publieke flyers machtigen geen geldinzameling.',
                'es' => 'Documentos útiles reúne plano, cartel, folletos, contactos aprobados, carta a patrocinadores y gastos. Solicite permiso para repartir. El folleto público no autoriza recaudación.',
                'de' => 'Unter Nützliche Dokumente stehen Standplan, Plakat, Flyer, bestätigte Kontaktstellen, Sponsorenbrief und Ausgabenformular. Für Verteilung Erlaubnis einholen. Öffentliche Flyer berechtigen nicht zur Geldsammlung.',
            ],
        ],
        'expenses' => [
            'question' => [
                'fr' => 'Comment faire rembourser une dépense d’équipe ?',
                'pt' => 'Como pedir o reembolso de uma despesa da equipa?',
                'en' => 'How do team expenses get reimbursed?',
                'nl' => 'Hoe worden teamkosten vergoed?',
                'es' => '¿Cómo se reembolsan los gastos?',
                'de' => 'Wie werden Teamkosten erstattet?',
            ],
            'answer' => [
                'fr' => 'Utilisez la note de frais imprimable, joignez les factures originales, indiquez le motif et remettez l’ensemble au comptable désigné par l’équipe ou au professionnel mandaté par QAPAS. Il vérifie la nature de la somme (avance remboursable, don ou dépense), le budget et l’accord écrit avant décision. La note seule ne vaut ni facture ni droit automatique à remboursement.',
                'pt' => 'Use a nota de despesas imprimível, anexe as faturas originais e entregue tudo ao contabilista da equipa ou ao profissional mandatado pela QAPAS. O profissional verifica se é adiantamento, donativo ou despesa e aplica o acordo escrito antes de decidir. A nota não é uma fatura nem garante reembolso.',
                'en' => 'Use the printable expense note, attach original receipts and submit it to the team\'s accountant or QAPAS-appointed professional. They check the payment type, budget and written agreement before reimbursement. The note alone is not an invoice or an entitlement.',
                'nl' => 'Lever het formulier met originele bewijsstukken bij de boekhouder in. De schriftelijke afspraken bepalen of en wanneer een voorschot of uitgave wordt vergoed.',
                'es' => 'Entregue el formulario y facturas originales al contable. El acuerdo escrito determina si el gasto es reembolsable.',
                'de' => 'Reichen Sie Formular und Originalbelege bei der Buchhaltung ein. Ob eine Erstattung möglich ist, richtet sich nach der schriftlichen Vereinbarung.',
            ],
        ],
        'cleaning_and_challenge' => [
            'question' => [
                'fr' => 'Qui nettoie le site, et que se passe-t-il si notre équipe manque son tour ?',
                'pt' => 'Quem limpa o recinto e se a nossa equipa falhar um turno?',
                'en' => 'Who cleans the site if our team misses a shift?',
                'nl' => 'Wie ruimt op als ons team een beurt mist?',
                'es' => '¿Quién limpia si nuestro equipo falta a su turno?',
                'de' => 'Wer reinigt den Platz, wenn unser Team einen Dienst versäumt?',
            ],
            'answer' => [
                'fr' => 'Chaque équipe transporte les déchets de son emplacement aux conteneurs désignés et participe aux permanences convenues. Les sanitaires sont nettoyés sous la responsabilité de personnes formées ou d’un prestataire ; leur location éventuelle entre dans le budget communiqué avant l’inscription payante. Après constat contradictoire et possibilité de remédier, un coût supplémentaire réellement justifié peut être réclamé uniquement selon des conditions plafonnées acceptées par écrit avant confirmation. La solidarité entre membres n’est pas automatique et doit être validée juridiquement puis acceptée individuellement. Aucun montant n’est encore fixé. L’épreuve officielle reste gratuite pour les équipes ; les essais publics facultatifs peuvent être payants, avec caisse et justificatifs tenus par l’équipe.',
                'pt' => 'Cada equipa leva os resíduos aos contentores indicados e cumpre os turnos acordados. A higienização dos sanitários fica sob responsabilidade de pessoal preparado ou prestador; eventual aluguer entra no orçamento antes da inscrição paga. Após registo dos factos e oportunidade de corrigir, só despesas extraordinárias comprovadas e sujeitas a limite previamente aceite podem ser cobradas. A solidariedade entre membros não é automática: exige análise jurídica e aceitação individual. Ainda não há valor definido. A prova oficial é gratuita para as equipas; experiências facultativas do público podem ser pagas, com caixa e comprovativos da equipa.',
                'en' => 'Each team takes its waste to designated containers and covers agreed shifts. Trained staff or a provider handles toilet sanitation; rental costs are disclosed before paid registration. Any extra cleaning charge needs documented actual cost, an opportunity to remedy and capped terms accepted in advance. Joint liability is not automatic. Official challenges are free for competing teams; optional public trials may have a posted fee collected and documented by the stand team.',
                'nl' => 'Elk team brengt afval weg en dekt afgesproken diensten. Toiletwerk wordt deskundig begeleid. Extra kosten vereisen bewijs en vooraf aanvaarde voorwaarden; hoofdelijke aansprakelijkheid is niet automatisch. Officiële proeven zijn gratis voor teams.',
                'es' => 'Cada equipo retira residuos y cumple turnos acordados. La limpieza sanitaria corresponde a personal preparado. Los cargos extra requieren prueba y acuerdo previo; la responsabilidad solidaria no es automática. Las pruebas oficiales son gratuitas para los equipos.',
                'de' => 'Jedes Team entsorgt Abfall und erfüllt vereinbarte Dienste. Toilettenreinigung erfolgt fachlich. Mehrkosten erfordern Nachweis und vorherige Zustimmung; gesamtschuldnerische Haftung entsteht nicht automatisch. Offizielle Prüfungen sind für Teams kostenlos.',
            ],
        ],
    ],
];
