<?php

return [
    'title' => ['fr' => 'La caisse des équipes', 'en' => 'Team funds', 'nl' => 'Teamkassen', 'es' => 'Fondos de los equipos', 'de' => 'Teamkassen', 'pt' => 'Contas das equipas'],
    'link' => ['fr' => 'Voir les fonds vérifiés des équipes', 'en' => 'See verified team funds', 'nl' => 'Bekijk gecontroleerde teambedragen', 'es' => 'Ver fondos verificados por equipo', 'de' => 'Geprüfte Teamkassen ansehen', 'pt' => 'Ver os fundos verificados das equipas'],
    'lead' => ['fr' => 'Chaque équipe désigne un trésorier. Les sommes réellement reçues et les dépenses payées sont publiées par équipe après contrôle des justificatifs. Les noms et montants individuels ne sont cités qu’avec l’accord distinct du contributeur ; les contacts et justificatifs restent privés. Les promesses de sponsor sont exclues.', 'en' => 'Each team appoints a treasurer. Verified receipts and paid expenses are shown by team. Names and individual amounts appear only with separate consent; contacts and evidence stay private. Sponsorship pledges are excluded.', 'nl' => 'Elk team benoemt een penningmeester. Gecontroleerde ontvangsten en betaalde kosten verschijnen per team; namen en bedragen verschijnen alleen met afzonderlijke toestemming; beloften blijven buiten beeld.', 'es' => 'Cada equipo nombra tesorero. Se publican ingresos recibidos y gastos pagados verificados por equipo, los nombres y montos individuales requieren consentimiento separado; las promesas no cuentan.', 'de' => 'Jedes Team benennt eine Kassenführung. Belegte Einnahmen und bezahlte Ausgaben erscheinen pro Team, Namen und Einzelbeträge nur mit gesonderter Einwilligung; Zusagen zählen nicht.', 'pt' => 'Cada equipa escolhe um tesoureiro ou tesoureira. Mostramos receitas recebidas e despesas pagas após verificação, nomes e valores individuais só com consentimento separado; contactos privados e promessas não são publicados.'],
    'income' => ['fr' => 'Reçus vérifiés', 'en' => 'Verified receipts', 'nl' => 'Gecontroleerde ontvangsten', 'es' => 'Ingresos verificados', 'de' => 'Geprüfte Einnahmen', 'pt' => 'Receitas verificadas'],
    'expense' => ['fr' => 'Dépenses vérifiées', 'en' => 'Verified spending', 'nl' => 'Gecontroleerde uitgaven', 'es' => 'Gastos verificados', 'de' => 'Geprüfte Ausgaben', 'pt' => 'Despesas verificadas'],
    'balance' => ['fr' => 'Solde', 'en' => 'Balance', 'nl' => 'Saldo', 'es' => 'Saldo', 'de' => 'Saldo', 'pt' => 'Saldo'],
    'empty' => ['fr' => 'Aucun montant vérifié pour le moment.', 'en' => 'No verified amounts yet.', 'nl' => 'Nog geen gecontroleerde bedragen.', 'es' => 'Aún no hay importes verificados.', 'de' => 'Noch keine geprüften Beträge.', 'pt' => 'Ainda não há valores verificados.'],
    'team_heading' => ['fr' => 'Comment l’équipe finance sa participation', 'en' => 'How the team funds its participation', 'pt' => 'Como a equipa financia a participação', 'nl' => 'Hoe het team deelname financiert', 'es' => 'Cómo se financia el equipo', 'de' => 'Wie das Team seine Teilnahme finanziert'],
    'team_explain' => ['fr' => 'Collecte reçue par l’équipe, aide des sponsors encaissée par QAPAS et affectée au matériel, et marge nette de la cuisine peuvent couvrir kit, transport, décoration et ingrédients. La réduction accordée par QAPAS ne constitue pas une entrée d’argent dans la caisse de l’équipe et n’est comptée qu’une fois. Ce solde vérifié ne promet aucun remboursement individuel.', 'en' => 'Village fundraising, paid sponsorships and shared food sales may cover the stand, transport, decoration, ingredients and food space. Sales only help after these costs. A verified balance is not a promise of individual reimbursement.', 'pt' => 'Angariação local, patrocínios pagos e vendas na banca coletiva podem cobrir banca, transporte, decoração, ingredientes e lugar de cozinha. As vendas só ajudam depois desses custos. O saldo verificado não promete reembolso individual.', 'nl' => 'Inzameling, betaalde sponsors en verkopen kunnen kosten dekken; het saldo belooft geen persoonlijke terugbetaling.', 'es' => 'Colectas, patrocinio cobrado y ventas pueden cubrir costes; el saldo no promete reembolsos individuales.', 'de' => 'Sammlung, bezahlte Sponsoren und Verkäufe können Kosten decken; der Saldo verspricht keine persönliche Erstattung.'],
    'contributors' => ['fr' => 'Celles et ceux qui soutiennent l’équipe', 'en' => 'People supporting the team', 'pt' => 'Quem apoia a equipa', 'nl' => 'Steun voor het team', 'es' => 'Quienes apoyan al equipo', 'de' => 'Unterstützende des Teams'],
    'contributors_note' => ['fr' => 'Seuls les noms choisis et, le cas échéant, les montants autorisés sont affichés. Les autres contributions restent dans les totaux, sans identité publique.', 'en' => 'Only chosen names and separately approved amounts appear. Other contributions remain in the totals without public identities.', 'pt' => 'Só os nomes escolhidos e os valores autorizados em separado aparecem. As restantes contribuições permanecem nos totais sem identidade pública.', 'nl' => 'Alleen gekozen namen en afzonderlijk toegestane bedragen verschijnen.', 'es' => 'Solo aparecen nombres elegidos e importes autorizados por separado.', 'de' => 'Nur gewählte Namen und gesondert freigegebene Beträge erscheinen.'],
    'gave' => ['fr' => 'a donné', 'en' => 'contributed', 'pt' => 'contribuiu com', 'nl' => 'droeg bij', 'es' => 'aportó', 'de' => 'spendete'],
    'contributors_empty' => ['fr' => 'Les premiers soutiens peuvent choisir de rester anonymes.', 'en' => 'Supporters may choose to remain anonymous.', 'pt' => 'Os primeiros apoiantes podem optar pelo anonimato.', 'nl' => 'Steun kan anoniem blijven.', 'es' => 'Las aportaciones pueden ser anónimas.', 'de' => 'Beiträge können anonym bleiben.'],
    'contribution_categories' => [
        'community' => ['fr' => 'Habitant·e', 'en' => 'Resident', 'pt' => 'Habitante', 'nl' => 'Inwoner', 'es' => 'Habitante', 'de' => 'Einwohner·in'],
        'sponsor' => ['fr' => 'Partenaire local', 'en' => 'Local partner', 'pt' => 'Parceiro local', 'nl' => 'Lokale partner', 'es' => 'Colaborador local', 'de' => 'Lokaler Partner'],
        'team' => ['fr' => 'Équipe', 'en' => 'Team', 'pt' => 'Equipa', 'nl' => 'Team', 'es' => 'Equipo', 'de' => 'Team'],
        'other' => ['fr' => 'Soutien', 'en' => 'Supporter', 'pt' => 'Apoiante', 'nl' => 'Steun', 'es' => 'Apoyo', 'de' => 'Unterstützung'],
    ],
    'friendly' => ['fr' => 'La collecte crée une émulation entre villages ; elle n’ajoute aucun point au classement sportif.', 'en' => 'Fundraising is a friendly village challenge and adds no sports points.', 'nl' => 'De inzameling is een vriendschappelijke dorpswedstrijd zonder sportpunten.', 'es' => 'La recaudación es una competición amistosa sin puntos deportivos.', 'de' => 'Die Sammlung ist ein freundschaftlicher Dorfwettbewerb ohne Sportpunkte.', 'pt' => 'A angariação é uma competição amigável entre aldeias, sem pontos desportivos.'],
];
