<?php

return [
    'next' => ['fr' => 'En trois étapes', 'en' => 'Three simple steps', 'nl' => 'Drie stappen', 'es' => 'Tres pasos', 'de' => 'Drei Schritte', 'pt' => 'Três passos'],
    'lead' => ['fr' => 'Choisissez votre envie, partagez une proposition et attendez la validation de l’organisation avant d’engager des frais.', 'en' => 'Choose a role, send a proposal and wait for organisers to confirm before spending.', 'nl' => 'Kies je rol, stuur een voorstel en wacht op bevestiging voor je kosten maakt.', 'es' => 'Elige tu papel, envía una propuesta y espera la confirmación antes de gastar.', 'de' => 'Wähle deine Rolle, schicke einen Vorschlag und warte auf Bestätigung, bevor du Geld ausgibst.', 'pt' => 'Escolha o seu papel, envie uma proposta e aguarde a confirmação antes de assumir despesas.'],
    'choose_title' => ['fr' => '1. Choisir', 'en' => '1. Choose', 'nl' => '1. Kies', 'es' => '1. Elegir', 'de' => '1. Wählen', 'pt' => '1. Escolher'],
    'choose' => ['fr' => 'Jouer, tenir un stand, cuisiner, exposer, visiter ou aider.', 'en' => 'Play, run a stand, cook, exhibit, visit or help.', 'nl' => 'Speel, beheer een stand, kook, toon, bezoek of help.', 'es' => 'Juega, organiza un puesto, cocina, expón, visita o ayuda.', 'de' => 'Spielen, einen Stand betreuen, kochen, ausstellen, besuchen oder helfen.', 'pt' => 'Jogar, gerir uma banca, cozinhar, expor, visitar ou ajudar.'],
    'propose_title' => ['fr' => '2. Proposer', 'en' => '2. Propose', 'nl' => '2. Stel voor', 'es' => '2. Proponer', 'de' => '2. Vorschlagen', 'pt' => '2. Propor'],
    'propose' => ['fr' => 'Un formulaire transmet l’idée à QAPAS ; il ne vaut pas inscription.', 'en' => 'The form sends your idea to QAPAS; it is not a registration.', 'nl' => 'Het formulier stuurt je idee naar QAPAS; het is geen inschrijving.', 'es' => 'El formulario envía tu idea a QAPAS; no es una inscripción.', 'de' => 'Das Formular übermittelt deine Idee an QAPAS; es ist keine Anmeldung.', 'pt' => 'O formulário envia a ideia à QAPAS; ainda não é uma inscrição.'],
    'confirm_title' => ['fr' => '3. Confirmer', 'en' => '3. Confirm', 'nl' => '3. Bevestig', 'es' => '3. Confirmar', 'de' => '3. Bestätigen', 'pt' => '3. Confirmar'],
    'confirm' => ['fr' => 'L’organisation répond, vérifie les conditions et confirme l’équipe ou l’emplacement.', 'en' => 'Organisers reply, review the terms and confirm a team or space.', 'nl' => 'De organisatie antwoordt en bevestigt team of plaats.', 'es' => 'La organización responde y confirma equipo o espacio.', 'de' => 'Die Organisation antwortet und bestätigt Team oder Platz.', 'pt' => 'A organização responde, verifica as condições e confirma a equipa ou o lugar.'],
    'roles' => ['fr' => 'Ce que vous pouvez faire', 'en' => 'What you can do', 'nl' => 'Wat je kunt doen', 'es' => 'Qué puedes hacer', 'de' => 'Was du tun kannst', 'pt' => 'O que pode fazer'],
    'practical' => ['fr' => 'En pratique : stand, financement et animations', 'en' => 'Practical details: stands, funding and activities', 'nl' => 'Praktisch: stands, financiering en activiteiten', 'es' => 'En la práctica: puestos, financiación y actividades', 'de' => 'Praktisch: Stände, Finanzierung und Aktivitäten', 'pt' => 'Na prática: bancas, financiamento e atividades'],
];
