<?php

return [
    'edition_label' => ['fr' => 'QAPAS · première édition', 'en' => 'QAPAS · first edition', 'nl' => 'QAPAS · eerste editie', 'es' => 'QAPAS · primera edición', 'de' => 'QAPAS · erste Ausgabe', 'pt' => 'QAPAS · primeira edição'],
    'tagline' => ['fr' => 'Villages, saveurs, défis et rencontres : chacun y trouvera sa place.', 'en' => 'Villages, flavours, challenges and encounters: there is a place for everyone.', 'nl' => 'Dorpen, smaken, uitdagingen en ontmoetingen: er is plek voor iedereen.', 'es' => 'Pueblos, sabores, retos y encuentros: hay sitio para todos.', 'de' => 'Dörfer, Genuss, Spiele und Begegnungen: Platz für alle.', 'pt' => 'Aldeias, sabores, desafios e encontros: há lugar para toda a gente.'],
    'title' => ['fr' => 'L’affiche', 'en' => 'The poster', 'nl' => 'De affiche', 'es' => 'El cartel', 'de' => 'Das Plakat', 'pt' => 'O cartaz'],
    'lead' => ['fr' => 'La fête se prépare : partagez cette affiche et retrouvez ici la date, le lieu et les équipes dès leur publication.', 'en' => 'The festival is taking shape: share this poster and find the date, venue and teams here when announced.', 'nl' => 'Het feest krijgt vorm: deel deze affiche en ontdek hier de datum, plaats en teams na publicatie.', 'es' => 'La fiesta toma forma: comparte este cartel y consulta aquí la fecha, el lugar y los equipos cuando se publiquen.', 'de' => 'Das Fest nimmt Gestalt an: Teile dieses Plakat und entdecke hier Termin, Ort und Teams, sobald sie bekannt sind.', 'pt' => 'A festa está a tomar forma: partilhe este cartaz e veja aqui a data, o local e as equipas quando forem publicados.'],
    'share' => ['fr' => 'Partager l’affiche', 'en' => 'Share the poster', 'nl' => 'De affiche delen', 'es' => 'Compartir el cartel', 'de' => 'Plakat teilen', 'pt' => 'Partilhar o cartaz'],
    'share_description' => ['fr' => 'Envoyez le lien à vos proches ou partagez-le sur un réseau social.', 'en' => 'Send the link to friends or share it on social media.', 'nl' => 'Stuur de link naar vrienden of deel hem via sociale media.', 'es' => 'Envía el enlace a otras personas o compártelo en redes sociales.', 'de' => 'Verschicke den Link oder teile ihn in sozialen Medien.', 'pt' => 'Envie o link a amigos ou partilhe-o nas redes sociais.'],
    'email' => ['fr' => 'Par courriel', 'en' => 'By email', 'nl' => 'Via e-mail', 'es' => 'Por correo', 'de' => 'Per E-Mail', 'pt' => 'Por email'],
    'link' => ['fr' => 'Lien de l’affiche', 'en' => 'Poster link', 'nl' => 'Link naar de affiche', 'es' => 'Enlace del cartel', 'de' => 'Link zum Plakat', 'pt' => 'Link para o cartaz'],
];
