<div class="space-y-5 rounded-xl border border-gray-200 dark:border-gray-700 p-5">
 <div><h2 class="text-xl font-semibold">Pilotage financier · {{ $scenario->name }}</h2><a class="text-primary-600 underline" href="{{ \App\Filament\Pages\FinancialPlanning::getUrl(['scenario'=>$scenario->public_id]) }}">Modifier les prix, coûts fixes, quantités et échéances →</a></div>
 @if(!$report)
 <p>Ouvrez le pilotage financier pour initialiser les hypothèses et le calendrier de ce scénario.</p>
 @else
 @php
  $money=fn($c)=>\App\Domain\Finance\Money::format($c);
  $phases=collect($report['phases']);$labels=$phases->map(fn($p,$i)=>'P'.($i+1))->all();
  $curve=collect($report['curve']);
 @endphp
 <p class="rounded-lg bg-amber-50 text-amber-900 p-3">Prévision de gestion {{ $report['complete']?'documentée selon les saisies':'conditionnelle · '.count($report['issues']).' points à compléter' }}. Une courbe positive ne vaut ni encaissement, ni autorisation d’engager des dépenses.</p>
 <div class="grid gap-4 md:grid-cols-3">
  @foreach(['price'=>['Prix de vente TTC non engagés',25],'volume'=>['Volume des postes variables non engagés',0],'fixed'=>['Coûts fixes non engagés, hors porteur',25]] as $key=>[$label,$min])
   <label class="block text-sm">{{ $label }} · <strong>{{ $this->$key }} %</strong><input class="block w-full mt-2" type="range" min="{{ $min }}" max="200" step="5" wire:model.live.debounce.500ms="{{ $key }}" aria-label="{{ $label }}"></label>
  @endforeach
 </div>
 <p class="text-sm">Simulation temporaire : mix de ventes constant, quantités proportionnelles. Les contrats engagés restent inchangés ; les curseurs ne réécrivent aucune fiche. Le calendrier couvre toute l’édition, avec un solde initial antérieur à sa première phase.</p>
 <x-filament::button color="gray" size="sm" wire:click="resetSimulation">Revenir aux saisies · 100 %</x-filament::button>
 <div class="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
  @foreach([
   ['Résultat prévisionnel',$report['result_cents']],['Manque pour l’équilibre',$report['result_gap_cents']],['Manque pour objectif + imprévus',$report['target_gap_cents']],['Financement complémentaire à mobiliser',$report['funding_need_cents']],
   ['Pic du BFR d’exploitation',$report['peak_bfr_cents']],['Investissements : décaissement total',$report['investment_cash_cents']],['IVA prévue à reverser',$report['vat_paid_cents']],['Trésorerie finale avant réserves',$report['closing_cash_cents']],
  ] as [$label,$amount])<div class="rounded-lg border p-3"><p class="text-sm">{{ $label }}</p><strong class="text-xl {{ $amount<0?'text-red-600':'' }}">{{ $money($amount) }}</strong></div>@endforeach
 </div>
 <p>Seuil de rentabilité du mix : <strong>{{ $report['break_even_sales_cents']===null?'Impossible avec cette marge variable':$money($report['break_even_sales_cents']).' de recettes nettes, soit '.$report['break_even_volume_pct'].' % du volume variable simulé' }}</strong>. Sponsors fixes : {{ $money($report['fixed_revenue_cents']) }} inclus comme hypothèses. Un seuil au-delà de la capacité impose de revoir le format ou le financement.</p>
 <div class="grid gap-5 xl:grid-cols-2">
  <x-financial-chart title="Rentabilité · variation du volume, mix constant" :labels="$curve->map(fn($p)=>$p['volume'].' %')->all()" :series="[['label'=>'Recettes nettes','color'=>'#059669','values'=>$curve->pluck('revenue')->all()],['label'=>'Charges de l’édition','color'=>'#dc2626','values'=>$curve->pluck('cost')->all()],['label'=>'Charges + objectif + imprévus','color'=>'#d97706','values'=>$curve->pluck('target_cost')->all()]]" />
  <x-financial-chart title="Flux TTC par phase · financements inclus" :labels="$labels" :bars="true" :series="[['label'=>'Entrées','color'=>'#059669','values'=>$phases->map(fn($p)=>$p['operating_in']+$p['financing_in']+$p['restricted_in'])->all()],['label'=>'Sorties, IVA comprise','color'=>'#dc2626','values'=>$phases->map(fn($p)=>$p['operating_out']+$p['investment_out']+$p['financing_out']+$p['restricted_out']+$p['vat_paid'])->all()]]" />
  <x-financial-chart title="Trésorerie disponible et besoin d’exploitation" :labels="$labels" :series="[['label'=>'Trésorerie bancaire prévue','color'=>'#2563eb','values'=>$phases->pluck('cash')->all()],['label'=>'Disponible après réserves','color'=>'#059669','values'=>$phases->pluck('free_cash')->all()],['label'=>'BFR','color'=>'#d97706','values'=>$phases->pluck('bfr')->all()]]" />
  <x-financial-chart title="IVA par phase · exigibilité et droit à déduction" :labels="$labels" :bars="true" :series="[['label'=>'IVA collectée / autoliquidée','color'=>'#dc2626','values'=>$phases->pluck('vat_output')->all()],['label'=>'IVA déductible documentée','color'=>'#2563eb','values'=>$phases->pluck('vat_input')->all()]]" />
 </div>
 <div class="overflow-x-auto"><table class="w-full text-sm"><caption class="text-left font-semibold mb-2">Calendrier des flux prévisionnels · euros TTC</caption><thead><tr>@foreach(['Phase','Exploitation +','Exploitation −','Investissements −','Financement net','Fonds affectés nets','IVA versée','BFR','Solde bancaire','Disponible'] as $label)<th class="p-2 text-right">{{ $label }}</th>@endforeach</tr></thead><tbody>
 @foreach($phases as $p)<tr class="border-t"><th class="p-2 text-left">P{{ $loop->iteration }} · {{ $p['label'] }}<span class="block font-normal">{{ $p['date'] }}</span></th>@foreach([$p['operating_in'],$p['operating_out'],$p['investment_out'],$p['financing_in']-$p['financing_out'],$p['restricted_in']-$p['restricted_out'],$p['vat_paid'],$p['bfr'],$p['cash'],$p['free_cash']] as $amount)<td class="p-2 text-right whitespace-nowrap {{ $amount<0?'text-red-600':'' }}">{{ $money($amount) }}</td>@endforeach</tr>@endforeach
 </tbody></table></div>
 <p class="text-sm">Disponible = banque − IVA encore due − fonds affectés − réserves ({{ $money($report['reserve_cents']) }}). Financement nécessaire = déficit maximal de ce disponible, solde initial inclus. Crédit IVA final de {{ $money($report['vat_credit_cents']) }} reporté, sans remboursement supposé. Les dates proposées sont à adapter aux échéances fiscales réelles.</p>
 <details><summary class="cursor-pointer font-semibold">Postes du business plan et composition du BFR</summary>
 <div class="overflow-x-auto"><table class="w-full text-sm"><thead><tr><th class="text-left p-2">Poste</th><th>Recettes nettes</th><th>Charges fixes</th><th>Charges variables</th><th>Décaissement investissement</th></tr></thead><tbody>@foreach($report['groups'] as $g)<tr class="border-t"><th class="p-2 text-left">{{ $g['label'] }}</th>@foreach(['revenue','fixed','variable','investment'] as $key)<td class="text-right p-2">{{ $money($g[$key]) }}</td>@endforeach</tr>@endforeach</tbody></table></div>
 <p class="my-3">BFR = stocks au coût économique + créances clients TTC + avances fournisseurs − dettes fournisseurs TTC − avances clients. Investissements, emprunts et IVA sont suivis séparément. Les crédits boissons ne créent pas une seconde recette lors de leur utilisation ; leur consommation et leur coût doivent être provisionnés dans les postes correspondants.</p>
 <div class="overflow-x-auto"><table class="w-full text-sm"><thead><tr><th>Phase</th><th>Stocks</th><th>Créances</th><th>Avances fournisseurs</th><th>Dettes</th><th>Avances clients</th></tr></thead><tbody>@foreach($phases as $p)<tr><th class="p-2">{{ $p['label'] }}</th>@foreach(['stock','receivables','supplier_advances','payables','customer_advances'] as $key)<td class="text-right p-2">{{ $money($p[$key]) }}</td>@endforeach</tr>@endforeach</tbody></table></div>
 </details>
 <details><summary class="cursor-pointer font-semibold">IVA : qualifications à documenter</summary><p class="mt-2">Le financement collectif ne constitue pas en lui-même une exonération. Stand, publicité, billets et crédits boissons nécessitent une qualification distincte. À 23 %, 1 000 € TTC correspondent à 813,01 € HT et 186,99 € d’IVA, sous réserve de l’arrondi des factures. Une facture étrangère à 19 % n’ouvre pas automatiquement une déduction au Portugal.</p><p>Le régime, les taux, la déduction et les acomptes se renseignent dans les hypothèses et chaque poste. Ce modèle applique un calendrier normal d’exigibilité documenté ; il ne produit ni facture fiscale ni déclaration IVA. Un régime spécial exige une adaptation avant usage.</p><p class="mt-2">Références AT : <a class="underline" href="https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/civa_rep/Pages/iva18.aspx" target="_blank" rel="noopener">taux</a> · <a class="underline" href="https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/civa_rep/Pages/iva8.aspx" target="_blank" rel="noopener">acomptes</a> · <a class="underline" href="https://info.portaldasfinancas.gov.pt/pt/informacao_fiscal/codigos_tributarios/civa_rep/Pages/iva19.aspx" target="_blank" rel="noopener">déduction</a>.</p></details>
 @if($report['issues'])<details><summary class="cursor-pointer font-semibold text-amber-700">{{ count($report['issues']) }} hypothèses ou postes à compléter</summary><ul class="list-disc ps-5 mt-2 space-y-1 max-h-96 overflow-y-auto">@foreach($report['issues'] as $issue)<li>{{ $issue }}</li>@endforeach</ul></details>@endif
 @endif
</div>
