<?php
namespace App\Filament\RelationManagers;
use Filament\Schemas\Schema;
use Filament\Forms\Components\{TextInput,Textarea,Select};
use Filament\Tables\Table;
use Filament\Tables\Columns\TextColumn;
use Filament\Actions\{CreateAction,EditAction};
class StandRequirementsRelationManager extends \Filament\Resources\RelationManagers\RelationManager {
 protected static string $relationship='requirements';protected static ?string $title='Besoins justifiés de cet emplacement';
 public function form(Schema $schema): Schema {return $schema->columns(2)->components([
  TextInput::make('name')->label('Appareil / besoin')->required()->maxLength(255),Select::make('kind')->label('Type')->options(['electricity'=>'Électricité','water'=>'Eau','wastewater'=>'Eaux usées','gas'=>'Gaz / bouteilles','access'=>'Accès','other'=>'Autre'])->required(),Textarea::make('justification')->label('Usage, appareil, durée et nécessité')->required()->columnSpanFull(),TextInput::make('quantity')->label('Quantité')->integer()->minValue(1),TextInput::make('unit')->label('Unité')->default('unité')->required(),TextInput::make('power_w')->label('Puissance nominale totale · W')->numeric()->minValue(0),TextInput::make('starting_power_w')->label('Puissance de démarrage · W')->numeric()->minValue(0),TextInput::make('requested_amps')->label('Intensité demandée · A')->numeric()->minValue(0),TextInput::make('line_length_m')->label('Longueur électrique réelle · m')->numeric()->minValue(0),TextInput::make('water_litres')->label('Volume d’eau prévu · L')->numeric()->minValue(0),TextInput::make('gas_kg')->label('Gaz prévu · kg')->numeric()->minValue(0),Select::make('source_id')->label('Source / réseau')->options(fn()=>\App\Models\SiteInfrastructure::where('event_project_id',$this->getOwnerRecord()->event_project_id)->pluck('name','id')),Select::make('provided_by')->label('Fourni et financé par')->options(['undecided'=>'À décider','qapas'=>'QAPAS','participant'=>'Participant','sponsor'=>'Apport partenaire'])->default('undecided')->required(),Select::make('budget_line_id')->label('Coût existant')->options(fn()=>\App\Models\BudgetLine::where('kind','cost')->whereNull('superseded_by_id')->whereHas('scenario',fn($q)=>$q->where('event_project_id',$this->getOwnerRecord()->event_project_id)->where('is_archived',false))->where(fn($q)=>$q->whereNull('stand_id')->orWhere('stand_id',$this->getOwnerRecord()->id))->pluck('name','id'))->searchable()->helperText('Rattacher la dépense une seule fois, commune ou propre au stand.'),Select::make('status')->label('État')->options(['requested'=>'Demandé','reviewed'=>'En revue','approved'=>'Validé'])->default('requested')->required(),Textarea::make('review_evidence')->label('Justificatif technique, responsable et conditions')->columnSpanFull(),
 ]);}
 public function table(Table $table): Table {return $table->columns([TextColumn::make('name')->label('Besoin'),TextColumn::make('kind')->label('Type'),TextColumn::make('power_w')->label('W'),TextColumn::make('line_length_m')->label('m de ligne'),TextColumn::make('source.name')->label('Source'),TextColumn::make('effective')->label('Vérification actuelle')->getStateUsing(fn($record)=>$record->valid()?'Validé':'À vérifier'),TextColumn::make('budgetLine.name')->label('Poste de coût')])->headerActions([CreateAction::make()])->recordActions([EditAction::make()]);}
}
