<?php
namespace App\Filament\Resources;
use Filament\Resources\Resource;
use Filament\Schemas\Components\Utilities\Get;
use Filament\Schemas\Schema;
use Filament\Tables\Table;
use Filament\Forms\Components\{TextInput,Textarea,Select,Toggle,DateTimePicker,DatePicker};
use Filament\Tables\Columns\TextColumn;
use Filament\Actions\EditAction;
class BudgetLineResource extends Resource {
 protected static ?string $model=\App\Models\BudgetLine::class;
 protected static ?string $modelLabel='Lignes budgétaires';
 protected static ?string $pluralModelLabel='Lignes budgétaires';
 protected static string|\UnitEnum|null $navigationGroup='2 · Chiffrer';

 protected static ?int $navigationSort=20;

 public static function form(Schema $schema): Schema {return $schema->columns(2)->components([Select::make('scenario_id')->label('Scénario')->relationship('scenario','name')->live()->preload()->searchable()->required()->disabledOn('edit'),TextInput::make('name')->label('Libellé')->maxLength(255)->required(),Select::make('kind')->label('Nature')->options(['revenue'=>'Recette propre QAPAS','cost'=>'Coût QAPAS','deposit'=>'Caution remboursable','earmarked'=>'Soutien affecté à une équipe','third_party'=>'Flux tiers (hors chiffre affaires)'])->required(),Select::make('scope')->label('Périmètre')->options(['common'=>'Frais communs','stand'=>'Unité stand','bar'=>'Bar QAPAS','soup'=>'Soupe QAPAS','fries'=>'Friterie QAPAS','structural'=>'Partenariat général','cups'=>'Gobelets réutilisables'])->required()->default('common')->live(),Select::make('stand_id')->label('Stand financé / fourni')->relationship('stand','name',fn($query,Get $get)=>$query->where('event_project_id',\App\Models\Scenario::find($get('scenario_id'))?->event_project_id))->live(),Select::make('stand_partner_id')->label('Parrain / relais payeur, le cas échéant')->relationship('standPartner','name',fn($query,Get $get)=>$query->where('stand_id',$get('stand_id'))),...self::financialFields()]);}
 public static function financialFields(): array {return [TextInput::make('unit')->label('Unité facturée (stand, jour, portion…)')->required()->default('unité')->maxLength(80),Select::make('expense_type')->label('Usage du coût')->options(['operating'=>'Exploitation','investment'=>'Investissement réutilisable'])->default('operating')->required(),TextInput::make('costing_key')->label('Clé de mutualisation facultative')->maxLength(120)->helperText('Ex. common-broadcast : une seule dépense commune peut servir plusieurs épreuves.'),TextInput::make('unit_gross_cents')->label('Montant TTC en centimes · vide = à chiffrer')->integer()->minValue(0)->maxValue(1000000000),TextInput::make('vat_basis_points')->label('IVA (2300 = 23 %, 0 = exonération confirmée)')->integer()->minValue(0)->maxValue(1000000000)->maxValue(10000)->helperText('Vide = à confirmer ; jamais assimilé automatiquement à zéro.'),Toggle::make('deductible')->label('IVA du coût déductible, confirmé comptablement'),TextInput::make('forecast_quantity')->label('Quantité prévue')->integer()->minValue(0)->maxValue(1000000000)->required()->default(0)->maxValue(1000000),TextInput::make('committed_quantity')->label('Quantité engagée')->integer()->minValue(0)->maxValue(1000000000)->required()->default(0)->lte('forecast_quantity'),TextInput::make('paid_quantity')->label('Quantité encaissée / réglée')->integer()->minValue(0)->maxValue(1000000000)->required()->default(0)->lte('committed_quantity'),Select::make('paid_by')->label('Qui a réglé le coût ?')->options(['qapas'=>'QAPAS','organizer'=>'Organisateur sur fonds personnels'])->default('qapas')->required(),TextInput::make('reimbursed_cents')->label('Avance déjà remboursée (centimes)')->integer()->minValue(0)->default(0),Textarea::make('receipt_reference')->label('Référence du paiement rapproché manuellement')->maxLength(3000),DateTimePicker::make('reconciled_at')->label('Date de rapprochement')->maxDate(now())->helperText('Enregistrer d’abord le montant et la quantité payée. Puis rapprocher le justificatif dans une seconde sauvegarde. Tout changement de montant annule le rapprochement.'),Textarea::make('evidence')->label('Référence devis, engagement, paiement ou justificatif')->maxLength(10000)->rows(3)->columnSpanFull(),...\App\Domain\Finance\Pricing::fields()];}
 public const SCOPES=['common'=>'Frais communs','stand'=>'Unités stands','bar'=>'Bar QAPAS','soup'=>'Soupe QAPAS','fries'=>'Ancienne friterie','structural'=>'Partenariat général','cups'=>'Gobelets réutilisables'];
 public const KINDS=['cost'=>'Coût QAPAS','revenue'=>'Recette QAPAS','deposit'=>'Caution remboursable','earmarked'=>'Soutien affecté','third_party'=>'Flux tiers'];
 public static function defaultScenario(): ?int {return \App\Models\Scenario::where('is_archived',false)->orderByRaw("CASE WHEN template_key = 'costing-rental-experts-v1' THEN 0 ELSE 1 END")->orderByDesc('id')->value('id');}
 public static function groups(): array {return [\Filament\Tables\Grouping\Group::make('scope')->label('Service / périmètre')->getTitleFromRecordUsing(fn($record)=>self::SCOPES[$record->scope]??$record->scope)->collapsible(),\Filament\Tables\Grouping\Group::make('stand.name')->label('Stand')->collapsible(),\Filament\Tables\Grouping\Group::make('kind')->label('Nature')->getTitleFromRecordUsing(fn($record)=>self::KINDS[$record->kind]??$record->kind)->collapsible(),\Filament\Tables\Grouping\Group::make('pricing_status')->label('Fiabilité')->getTitleFromRecordUsing(fn($record)=>\App\Domain\Finance\Pricing::STATUSES[$record->pricing_status]??$record->pricing_status)->collapsible()];}
 public static function table(Table $table): Table {return $table->modifyQueryUsing(fn($query)=>$query->whereNull('superseded_by_id'))->columns([
  TextColumn::make('name')->label('Poste')->searchable()->wrap(),TextColumn::make('stand.name')->label('Stand')->placeholder('Commun / service'),TextColumn::make('kind')->label('Nature')->formatStateUsing(fn($state)=>self::KINDS[$state]??$state)->badge(),TextColumn::make('forecast_quantity')->label('Qté prévue')->numeric(),TextColumn::make('unit')->label('Unité'),TextColumn::make('unit_gross_cents')->label('PU TTC')->formatStateUsing(fn($state)=>\App\Domain\Finance\Money::format((int)$state))->placeholder('À chiffrer')->summarize(array_map(fn($kind)=>\Filament\Tables\Columns\Summarizers\Summarizer::make($kind)->label($kind==='cost'?'Coûts TTC connus':'Recettes TTC connues')->using(fn(\Illuminate\Database\Query\Builder $query)=>(int)$query->where('kind',$kind)->selectRaw('COALESCE(SUM(unit_gross_cents * forecast_quantity),0) AS total')->value('total'))->formatStateUsing(fn($state)=>\App\Domain\Finance\Money::format((int)$state)),['cost','revenue'])),
  TextColumn::make('total')->label('Total prévu TTC')->getStateUsing(fn($record)=>$record->unit_gross_cents===null?'À chiffrer':\App\Domain\Finance\Money::format($record->unit_gross_cents*$record->forecast_quantity)),TextColumn::make('pricing_status')->label('Fiabilité')->formatStateUsing(fn($state)=>\App\Domain\Finance\Pricing::STATUSES[$state]??$state)->badge(),TextColumn::make('committed_quantity')->label('Engagé'),TextColumn::make('paid_quantity')->label('Payé'),TextColumn::make('scenario.name')->label('Scénario')->toggleable(isToggledHiddenByDefault:true),
  ])->groups(self::groups())->defaultGroup('scope')->filters([
   \Filament\Tables\Filters\SelectFilter::make('scenario_id')->label('Scénario · un seul à la fois')->options(fn()=>\App\Models\Scenario::orderBy('is_archived')->get()->mapWithKeys(fn($s)=>[$s->id=>($s->is_archived?'ARCHIVE · ':'').$s->name]))->default(fn()=>self::defaultScenario())->query(fn($query,array $data)=>$query->where('scenario_id',$data['value']??0)),
   \Filament\Tables\Filters\SelectFilter::make('kind')->label('Nature')->options(self::KINDS),\Filament\Tables\Filters\SelectFilter::make('scope')->label('Service')->options(self::SCOPES),\Filament\Tables\Filters\SelectFilter::make('stand_id')->label('Stand')->relationship('stand','name')->searchable(),\Filament\Tables\Filters\SelectFilter::make('pricing_status')->label('Fiabilité')->options(\App\Domain\Finance\Pricing::STATUSES),\Filament\Tables\Filters\Filter::make('unknown')->label('Prix ou IVA inconnus')->query(fn($query)=>$query->where(fn($q)=>$q->whereNull('unit_gross_cents')->orWhereNull('vat_basis_points'))),\Filament\Tables\Filters\Filter::make('planned')->label('Quantité prévue > 0')->query(fn($q)=>$q->where('forecast_quantity','>',0)),
  ])->defaultSort('id')->recordActions([CostConsultationResource::requestAction(),EditAction::make(),\Filament\Actions\Action::make('duplicate')->label('Écarter le doublon')->visible(fn($record)=>\App\Domain\Finance\BudgetIdentity::duplicates($record)->isNotEmpty())->schema([Select::make('canonical')->label('Poste conservé · même unité et même nature')->options(fn($record)=>\App\Domain\Finance\BudgetIdentity::duplicates($record)->mapWithKeys(fn($l)=>[$l->id=>'#'.$l->id.' · '.$l->name.' · '.($l->unit_gross_cents===null?'inconnu':\App\Domain\Finance\Money::format($l->unit_gross_cents)).' × '.$l->forecast_quantity]))->required()])->modalDescription('Cette ligne sera conservée dans l’historique et exclue des prévisions. Aucun montant ne sera additionné. Impossible si elle porte un engagement ou un règlement.')->action(fn($record,array $data)=>app(\App\Domain\Finance\BudgetIdentity::class)->supersede($record,(int)$data['canonical']))]);}
 public static function getPages(): array {return ['index'=>\App\Filament\Resources\BudgetLineResource\Pages\ManageRecords::route('/')];}
}
