<?php
namespace App\Filament\Resources;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Schemas\Components\Utilities\Get;
use Filament\Forms\Components\{TextInput,Textarea,Select,Toggle,DateTimePicker};
use Filament\Tables\Table;
use Filament\Tables\Columns\TextColumn;
use Filament\Actions\{EditAction,Action};
class OutreachVisitResource extends Resource {
 protected static ?string $model=\App\Models\OutreachVisit::class;protected static ?string $modelLabel='Tournées juntas et cafés';protected static ?string $pluralModelLabel='Tournées juntas et cafés';protected static string|\UnitEnum|null $navigationGroup='3 · Mobiliser';protected static ?int $navigationSort=15;
 public static function form(Schema $schema): Schema {return $schema->columns(2)->components([Select::make('event_project_id')->label('Édition')->relationship('eventProject','name')->required()->disabledOn('edit'),TextInput::make('name')->label('Junta / lieu visité')->required(),TextInput::make('freguesia')->required(),TextInput::make('tour')->label('Tournée groupée'),TextInput::make('visit_order')->label('Ordre de passage')->integer()->default(100)->required(),DateTimePicker::make('planned_at')->label('Visite prévue')->timezone('Europe/Lisbon'),DateTimePicker::make('visited_at')->label('Dépôt effectué le')->timezone('Europe/Lisbon')->maxDate(now()),TextInput::make('reception_contact')->label('Accueil : interlocuteur rencontré'),TextInput::make('president_name')->label('Président · nom'),TextInput::make('president_email')->label('Président · email professionnel')->email(),TextInput::make('president_phone')->label('Président · téléphone utile'),TextInput::make('treasurer_name')->label('Trésorier · nom'),TextInput::make('treasurer_email')->label('Trésorier · email professionnel')->email(),TextInput::make('treasurer_phone')->label('Trésorier · téléphone utile'),Textarea::make('contact_source')->label('Coordonnées communiquées par, date et modalités de suivi')->columnSpanFull(),TextInput::make('letters_delivered')->label('Courriers réellement déposés')->integer()->minValue(0)->default(0)->required(),TextInput::make('cards_delivered')->label('Cartes de visite déposées')->integer()->minValue(0)->default(0)->required(),Textarea::make('delivery_evidence')->label('Preuve / note de dépôt et aperçu montré à l’accueil'),Select::make('junta_status')->label('Réponse de la junta')->options(['to_visit'=>'À visiter','deposited'=>'Courriers déposés','following_up'=>'Relance personnelle','agreed'=>'Participation confirmée','declined'=>'Déclinée'])->default('to_visit')->required(),Textarea::make('junta_evidence')->label('Accord et interlocuteur habilité'),TextInput::make('prospective_relay')->label('Café pressenti · pas encore point-relais acquis'),DateTimePicker::make('meeting_at')->label('Réunion confirmée après accord de la junta')->timezone('Europe/Lisbon'),Textarea::make('meeting_agreement')->label('Accord du café hôte, lieu, invitation et consommations'),Textarea::make('next_action')->label('Prochaine action personnelle'),DateTimePicker::make('followup_at')->label('Relance prévue'),Textarea::make('letter_pt')->label('Courrier PT · président et trésorier')->rows(10)->columnSpanFull(),Textarea::make('teaser_pt')->label('Accroche à montrer à l’accueil / au café')->rows(4)->columnSpanFull()]);}
 public static function table(Table $table): Table {return $table->columns([TextColumn::make('tour')->label('Tournée')->sortable(),TextColumn::make('visit_order')->label('Ordre')->sortable(),TextColumn::make('name')->searchable(),TextColumn::make('freguesia')->searchable(),TextColumn::make('junta_status')->badge(),TextColumn::make('followup_at')->dateTime('d/m/Y H:i')])->defaultSort('visit_order')->groups(['tour','freguesia'])->recordActions([Action::make('letter')->label('Courriers à imprimer')->url(fn($record)=>route('outreach.letter',['visit'=>$record->public_id]))->openUrlInNewTab(),EditAction::make()->modalWidth('7xl')]);}
 public static function getPages(): array {return ['index'=>\App\Filament\Resources\OutreachVisitResource\Pages\ManageRecords::route('/')];}
}
