<?php
namespace App\Filament\Resources;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Schemas\Components\Utilities\Get;
use Filament\Forms\Components\{Select,TextInput,Textarea,Toggle,DateTimePicker,Placeholder};
use Filament\Tables\Table;
use Filament\Tables\Columns\TextColumn;
use Filament\Actions\{EditAction,Action};
class PlantingSessionResource extends Resource {
 protected static ?string $model=\App\Models\PlantingSession::class;protected static ?string $modelLabel='Plantation collective';protected static ?string $pluralModelLabel='Plantation · clôture des journées';protected static string|\UnitEnum|null $navigationGroup='4 · Préparer';protected static ?int $navigationSort=45;
 public static function form(Schema $schema): Schema {return $schema->columns(2)->components([Select::make('event_project_id')->label('Édition')->relationship('eventProject','name')->required()->live()->disabledOn('edit'),TextInput::make('name')->required(),TextInput::make('day_number')->label('Journée')->integer()->minValue(1)->maxValue(30)->required(),DateTimePicker::make('starts_at')->label('Clôture de journée · heure')->timezone('Europe/Lisbon'),Select::make('quartel_id')->label('Quartel')->options(fn(Get $get)=>\App\Models\SiteFeature::where('event_project_id',$get('event_project_id'))->where('category','quartel')->pluck('name','id')),Select::make('nursery_prospect_id')->label('Pépiniériste · différent chaque jour')->options(fn(Get $get)=>\App\Models\Prospect::where('event_project_id',$get('event_project_id'))->pluck('name','id'))->searchable(),Textarea::make('partner_agreement')->label('Achat des arbres, intervention pédagogique, partenariat et entretien'),TextInput::make('capacity')->label('Slots prévus = arbres')->integer()->minValue(0)->maxValue(1000)->required(),TextInput::make('trees_received')->label('Arbres réellement reçus')->integer()->minValue(0)->required(),Textarea::make('receipt_evidence')->label('Bon de réception, qualité et variétés'),Select::make('budget_line_id')->label('Coût complet par arbre · ligne existante')->options(fn(Get $get)=>\App\Models\BudgetLine::whereHas('scenario',fn($q)=>$q->where('event_project_id',$get('event_project_id')))->where('kind','cost')->pluck('name','id')),TextInput::make('supervisor')->label('Responsable pédagogique'),Textarea::make('instructions_fr')->label('Consignes FR'),Textarea::make('instructions_pt')->label('Consignes PT'),Textarea::make('preparation_evidence')->label('Sol, outils, encadrement, eau, accessibilité, météo et entretien prévus'),Select::make('status')->options(['draft'=>'À préparer','ready'=>'Prêt · arbres et consignes disponibles','closed'=>'Terminé / fermé'])->required(),Toggle::make('is_public')->label('Présenter au public'),Placeholder::make('readiness')->label('À préparer')->content(fn(?\App\Models\PlantingSession $record)=>$record?implode(' · ',$record->blockers()):'Enregistrer la session.')]);}
 public static function table(Table $table): Table {return $table->columns([TextColumn::make('name'),TextColumn::make('day_number')->label('Jour'),TextColumn::make('quartel.name')->label('Quartel'),TextColumn::make('nursery.name')->label('Pépiniériste'),TextColumn::make('capacity')->label('Slots'),TextColumn::make('trees_received')->label('Arbres reçus'),TextColumn::make('status')->badge()])->recordActions([EditAction::make()->modalWidth('7xl'),Action::make('generate')->label('Créer les emplacements d’arbres')->requiresConfirmation()->action(fn($record)=>app(\App\Domain\Planting\Planting::class)->generate($record)),Action::make('slots')->label('Arbres et participants')->url(fn($record)=>PlantingSlotResource::getUrl('index',['tableFilters'=>['planting_session_id'=>['value'=>$record->id]]]))]);}
 public static function getPages(): array {return ['index'=>\App\Filament\Resources\PlantingSessionResource\Pages\ManageRecords::route('/')];}
}
