<?php
namespace App\Filament\Resources;
use App\Models\Prospect;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Forms\Components\{TextInput,Textarea,Select,Toggle,DatePicker,DateTimePicker};
use Filament\Tables\Table;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\SelectFilter;
use Filament\Actions\{EditAction,Action};
class ProspectResource extends Resource {
 protected static ?string $model=Prospect::class;
 protected static ?string $modelLabel='Prospect';
 protected static ?string $pluralModelLabel='Prospects et tournées';
 protected static string|\UnitEnum|null $navigationGroup='3 · Mobiliser';
 protected static ?int $navigationSort=10;
 public static function form(Schema $schema): Schema {return $schema->columns(2)->components([Select::make('event_project_id')->label('Édition')->relationship('eventProject','name')->required()->disabledOn('edit'),TextInput::make('source_key')->label('Référence unique du site')->required(),TextInput::make('entity_key')->label('Groupe entreprise · éviter les doublons de contact')->required(),TextInput::make('name')->label('Établissement')->required(),TextInput::make('category')->label('Catégorie')->required(),TextInput::make('sector')->label('Secteur géographique')->required(),TextInput::make('tour')->label('Tournée')->required(),TextInput::make('priority')->label('Priorité 1 à 3')->integer()->minValue(1)->maxValue(3)->default(2)->required(),TextInput::make('visit_order')->label('Ordre de visite dans la tournée')->integer()->minValue(0)->default(100)->required(),Textarea::make('address')->label('Adresse · confirmer avant départ')->required(),TextInput::make('phone')->label('Téléphone professionnel'),TextInput::make('email')->label('Email professionnel')->email(),Toggle::make('address_confirmed')->label('Adresse confirmée par contact'),DateTimePicker::make('appointment_at')->label('Rendez-vous convenu')->timezone('Europe/Lisbon'),Select::make('status')->label('Suivi')->options(['new'=>'À qualifier','to_call'=>'À appeler avant trajet','appointment'=>'Rendez-vous fixé','contacted'=>'Contact établi','qualified'=>'Intérêt qualifié','declined'=>'Décliné'])->default('new')->required(),Textarea::make('opportunity')->label('Proposition adaptée')->columnSpanFull(),Textarea::make('next_action')->label('Prochaine action')->columnSpanFull(),Textarea::make('source')->label('Sources publiques et fiabilité')->required()->columnSpanFull(),DatePicker::make('checked_at')->label('Consultation des sources')->required(),Textarea::make('notes')->label('Vérifications, interlocuteur professionnel, accord de suivi')->columnSpanFull()]);}
 public static function table(Table $table): Table {return $table->columns([TextColumn::make('tour')->label('Tournée')->sortable(),TextColumn::make('visit_order')->label('Ordre')->sortable(),TextColumn::make('priority')->label('Priorité')->sortable(),TextColumn::make('name')->label('Établissement')->searchable()->wrap(),TextColumn::make('entity_key')->label('Entreprise')->searchable(),TextColumn::make('address')->label('Adresse à confirmer')->wrap(),TextColumn::make('phone')->label('Téléphone'),TextColumn::make('status')->label('Suivi')->badge()])->defaultSort('visit_order')->filters([SelectFilter::make('event_project_id')->label('Édition')->relationship('eventProject','name'),SelectFilter::make('tour')->label('Tournée')->options(fn()=>Prospect::distinct()->pluck('tour','tour')),SelectFilter::make('category')->label('Catégorie')->options(fn()=>Prospect::distinct()->pluck('category','category')),SelectFilter::make('priority')->label('Priorité')->options([1=>'1 · Première approche',2=>'2 · À compléter',3=>'3 · Sur rendez-vous']),SelectFilter::make('status')->label('Suivi')->options(['new'=>'À qualifier','to_call'=>'À appeler','appointment'=>'Rendez-vous','contacted'=>'Contact établi','qualified'=>'Qualifié','declined'=>'Décliné'])])->recordActions([Action::make('map')->label('Carte')->url(fn($record)=>'https://www.openstreetmap.org/search?query='.rawurlencode($record->address))->openUrlInNewTab(),EditAction::make()->modalWidth('7xl')]);}
 public static function getPages(): array {return ['index'=>\App\Filament\Resources\ProspectResource\Pages\ManageRecords::route('/')];}
}
