<?php
namespace App\Filament\Resources;
use Filament\Resources\Resource;
use Filament\Schemas\Schema;
use Filament\Schemas\Components\Utilities\Get;
use Filament\Forms\Components\{TextInput,Textarea,Select,Toggle,DateTimePicker};
use Filament\Tables\Table;
use Filament\Tables\Columns\TextColumn;
use Filament\Actions\{EditAction,Action};
class SiteInfrastructureResource extends Resource {
 protected static ?string $model=\App\Models\SiteInfrastructure::class;protected static ?string $modelLabel='Infrastructures et réseaux';protected static ?string $pluralModelLabel='Infrastructures et réseaux';protected static string|\UnitEnum|null $navigationGroup='4 · Préparer';protected static ?int $navigationSort=25;
 public static function form(Schema $schema): Schema {return $schema->columns(2)->components([Select::make('event_project_id')->label('Édition')->relationship('eventProject','name')->required()->live()->disabledOn('edit'),TextInput::make('name')->label('Équipement / nœud')->required(),Select::make('kind')->label('Type')->options(\App\Models\SiteInfrastructure::KINDS)->required(),Select::make('source_id')->label('Alimentation / infrastructure amont')->relationship('source','name',fn(\Illuminate\Database\Eloquent\Builder $query,Get $get)=>$query->where('event_project_id',$get('event_project_id'))),Select::make('site_feature_id')->label('Position sur le plan')->relationship('siteFeature','name',fn(\Illuminate\Database\Eloquent\Builder $query,Get $get)=>$query->where('event_project_id',$get('event_project_id'))),TextInput::make('declared_kva')->label('Puissance apparente déclarée · kVA')->numeric()->minValue(0),Select::make('phases')->label('Alimentation vérifiée')->options(['unknown'=>'À vérifier','single'=>'Monophasé','three'=>'Triphasé'])->default('unknown')->required(),TextInput::make('voltage_v')->label('Tension vérifiée · V')->integer()->minValue(1)->maxValue(1000),TextInput::make('amp_limit')->label('Limite / protection vérifiée · A')->numeric()->minValue(0),TextInput::make('cable_marking')->label('Marquage réel du câble, photo/référence'),TextInput::make('conductor_count')->label('Nombre de conducteurs')->integer()->minValue(1),TextInput::make('section_mm2')->label('Section par conducteur · mm²')->numeric()->minValue(0)->helperText('4 × 16 n’est pas une indication de protection à 16 A. Identifier neutre, terre, pose, longueur et protections.'),Toggle::make('neutral_verified')->label('Neutre identifié par le technicien'),Toggle::make('earth_verified')->label('Terre et protection vérifiées'),Select::make('status')->label('Disponibilité')->options(['declared'=>'Matériel déclaré, caractéristiques à vérifier','to_build'=>'À construire / à fournir','reviewed'=>'En revue technique','approved'=>'Disponible après validation technique'])->default('declared')->required(),Textarea::make('description')->label('Topologie, usages, contraintes et travaux')->rows(5)->columnSpanFull(),Textarea::make('review_evidence')->label('Technicien, essais, protections, capacités et périmètre validés')->columnSpanFull(),Select::make('budget_line_id')->label('Poste budgétaire existant · pas de double coût')->relationship('budgetLine','name',fn(\Illuminate\Database\Eloquent\Builder $query,Get $get)=>$query->where('kind','cost')->whereNull('superseded_by_id')->whereHas('scenario',fn($q)=>$q->where('event_project_id',$get('event_project_id'))))->searchable()]);}
 public static function table(Table $table): Table {return $table->columns([TextColumn::make('name')->label('Équipement')->searchable(),TextColumn::make('kind')->formatStateUsing(fn($state)=>\App\Models\SiteInfrastructure::KINDS[$state]??$state),TextColumn::make('source.name')->label('Amont'),TextColumn::make('status')->badge(),TextColumn::make('declared_kva')->label('kVA déclarés')])->recordActions([EditAction::make()->modalWidth('7xl')]);}
 public static function getPages(): array {return ['index'=>\App\Filament\Resources\SiteInfrastructureResource\Pages\ManageRecords::route('/')];}
}
