<?php
namespace App\Models;
use Illuminate\Validation\ValidationException;
class PlantingSlot extends Record {
 protected $hidden=['participant_name','evidence'];protected $attributes=['status'=>'available'];
 protected function casts(): array {return ['thanks_consented_at'=>'datetime','planted_at'=>'datetime','latitude'=>'float','longitude'=>'float'];}
 public function session(){return $this->belongsTo(PlantingSession::class,'planting_session_id');}
 public function ticket(){return $this->belongsTo(EventTicket::class,'event_ticket_id');}
 public function publicLocation(): bool {return $this->status==='planted'&&$this->latitude!==null&&$this->longitude!==null&&$this->session->is_public&&$this->session->eventProject->is_public&&$this->session->eventProject->geo_is_public&&$this->session->quartel?->is_public&&$this->session->contains($this->longitude,$this->latitude);}
 protected static function booted(): void {parent::booted();static::saving(function(self $s){\Illuminate\Support\Facades\Validator::make($s->getAttributes(),['status'=>'in:available,reserved,planted','tree_code'=>'required|string|max:80','public_name'=>'nullable|string|max:80','latitude'=>'nullable|numeric|between:-85,85','longitude'=>'nullable|numeric|between:-180,180'])->validate();if($s->exists&&$s->getOriginal('status')==='planted'&&$s->status!=='planted')throw ValidationException::withMessages(['status'=>'Conserver la plantation réalisée ; traiter les corrections avec preuve.']);if($s->exists&&$s->isDirty(['planting_session_id','tree_code']))throw ValidationException::withMessages(['tree_code'=>'Conserver l’identité et la session de l’arbre.']);if(($s->latitude===null)!==($s->longitude===null)||($s->latitude!==null&&!$s->session->contains($s->longitude,$s->latitude)))throw ValidationException::withMessages(['latitude'=>'Relever les deux coordonnées réelles, à l’intérieur du quartel.']);if($s->event_ticket_id&&$s->ticket?->plan?->event_project_id!==$s->session->event_project_id)throw ValidationException::withMessages(['event_ticket_id'=>'Billet d’une autre édition.']);if($s->status==='available'&&$s->event_ticket_id)throw ValidationException::withMessages(['status'=>'Un arbre réservé ne se libère que par une annulation tracée.']);if($s->status!=='available'&&$s->isDirty(['event_ticket_id','status','participant_name'])&&(!$s->ticket?->valid()||blank($s->participant_name)))throw ValidationException::withMessages(['event_ticket_id'=>'Billet payé et participant requis.']);if($s->status==='planted'&&(!$s->planted_at||$s->planted_at->isFuture()||blank($s->evidence)||blank($s->species)))throw ValidationException::withMessages(['planted_at'=>'Date réelle, espèce et preuve de plantation requises.']);if(filled($s->public_name)&&!$s->thanks_consented_at)throw ValidationException::withMessages(['public_name'=>'Consentement volontaire aux remerciements requis.']);});}
}
