<?php
namespace App\Models;
use Illuminate\Validation\ValidationException;
class PresalePlan extends Record {
 protected $attributes=['kind'=>'support','price_cents'=>1000,'parking_basis_points'=>1000,'relay_basis_points'=>1000,'junta_basis_points'=>1000,'village_basis_points'=>1000,'capacity'=>0,'is_open'=>false];
 protected function casts(): array {return ['drink_credit_cents'=>'integer','drink_cost_cents'=>'integer','unified_benefits'=>'boolean','benefits'=>'array','early_benefits'=>'array','early_until'=>'datetime','relay_changes_at'=>'datetime','is_open'=>'boolean','closes_at'=>'datetime'];}
 public function eventProject(){return $this->belongsTo(EventProject::class);}
 public function tickets(){return $this->hasMany(EventTicket::class);}
 public function blockers(): array {return app(\App\Domain\Tickets\Ticketing::class)->blockers($this);}
 public function quote(): array {return app(\App\Domain\Tickets\TicketOffer::class)->quote($this);}
 public function report(): array {return app(\App\Domain\Tickets\Ticketing::class)->report($this);}
 protected static function booted(): void {parent::booted();static::saving(function(self $p){
  $rules=['drink_credit_cents'=>'sometimes|integer|in:0,1000','drink_cost_cents'=>'nullable|integer|between:0,1000000','sales_strategy'=>'sometimes|in:fixed,presale_discount,relay_stepdown','full_price_cents'=>'nullable|integer|between:1000,1000000','late_relay_basis_points'=>'nullable|integer|between:0,10000','benefit_cost_cents'=>'nullable|integer|between:0,1000000','early_benefit_cost_cents'=>'nullable|integer|between:0,1000000','kind' =>'in:support,admission','price_cents'=>'integer|between:1000,1000000','vat_basis_points'=>'nullable|integer|between:0,10000','capacity'=>'integer|between:0,100000','terms_version'=>'required|string|max:100','bank_available_cents'=>'nullable|integer|between:0,1000000000','refund_reserve_cents'=>'nullable|integer|between:0,1000000000'];foreach(['parking','relay','junta','village'] as $k)$rules[$k.'_basis_points']='integer|between:0,10000';\Illuminate\Support\Facades\Validator::make($p->getAttributes(),$rules)->validate();
  foreach(['benefits','early_benefits'] as $field)\Illuminate\Support\Facades\Validator::make([$field=>$p->$field??[]],[$field=>'array|max:20',$field.'.*.label_fr'=>'required|string|max:500',$field.'.*.label_pt'=>'required|string|max:500',$field.'.*.quantity'=>'required|integer|between:1,100'])->validate();
  if($p->sales_strategy==='presale_discount'&&($p->relay_changes_at||$p->late_relay_basis_points!==null))throw ValidationException::withMessages(['sales_strategy'=>'Remise et baisse de commission sont alternatives : vider les champs de l’autre stratégie.']);
  if($p->sales_strategy==='relay_stepdown'&&$p->full_price_cents!==null)throw ValidationException::withMessages(['sales_strategy'=>'La baisse de commission conserve un prix fixe ; vider le prix plein alternatif.']);
  if($p->parking_basis_points+$p->relay_basis_points+$p->junta_basis_points+$p->village_basis_points>10000)throw ValidationException::withMessages(['split_evidence'=>'Répartition supérieure à 100 %.']);
  if($p->exists&&$p->isDirty('event_project_id'))throw ValidationException::withMessages(['event_project_id'=>'Conserver l’édition.']);
  if($p->exists&&$p->isDirty(['drink_credit_cents','drink_cost_cents','drink_credit_terms_fr','drink_credit_terms_pt','drink_cost_evidence','unified_benefits','sales_strategy','full_price_cents','early_until','relay_changes_at','late_relay_basis_points','pricing_evidence','benefits','early_benefits','benefit_cost_cents','early_benefit_cost_cents','benefit_evidence','kind','price_cents','terms_version','terms_fr','terms_pt','refund_fr','refund_pt','vat_basis_points','stripe_tax_rate_id','parking_basis_points','relay_basis_points','junta_basis_points','village_basis_points','split_evidence','billing_procedure','approval_evidence','closes_at'])){if($p->tickets()->exists()&&!$p->isDirty('terms_version'))throw ValidationException::withMessages(['terms_version'=>'Nouvelle version requise ; chaque billet conserve les conditions et la répartition acceptées.']);$p->is_open=false;}
  if($p->is_open&&(!$p->exists||$p->isDirty('is_open'))){if(!auth('admin')->user()?->is_active)throw ValidationException::withMessages(['is_open'=>'Administrateur actif requis.']);if($errors=$p->blockers())throw ValidationException::withMessages(['is_open'=>implode(' · ',$errors)]);}
 });}
}
