<?php
namespace App\Models;
class Stand extends Record {
 protected $attributes=['included_furniture_sets'=>0,'furniture_source'=>'rental','furniture_quantity'=>2,'furniture_confirmed'=>false];
 public function furnitureBudget(): array {$rental=$this->furniture_source==='rental';$known=$rental&&$this->furniture_unit_gross_cents!==null&&$this->furniture_delivery_cents!==null;$total=$known?$this->furniture_unit_gross_cents*$this->furniture_quantity+$this->furniture_delivery_cents:null;return ['gross_cents'=>$total,'deposit_cents'=>$this->furniture_deposit_cents,'confirmed'=>$this->furniture_confirmed&&filled($this->furniture_evidence)&&in_array($this->furniture_source,['rental','own','loan'],true)&&(!$rental||($known&&$this->furniture_deposit_cents!==null))];}
 public function budgetLines(){return $this->hasMany(BudgetLine::class);}
 protected function casts(): array {return ['furniture_confirmed'=>'boolean','direct_costs_complete'=>'boolean','hospitality_validated'=>'boolean','larger_tent_requested'=>'boolean'];}
 public function siteFeature(){return $this->belongsTo(SiteFeature::class);}
 public function partners(){return $this->hasMany(StandPartner::class);}
 protected static function booted(): void {parent::booted();static::saving(function(self $s){\Illuminate\Support\Facades\Validator::make($s->getAttributes(),['furniture_source'=>'sometimes|in:rental,own,loan,undecided','furniture_quantity'=>'sometimes|integer|between:1,1000','furniture_unit_gross_cents'=>'nullable|integer|between:0,100000000','furniture_delivery_cents'=>'nullable|integer|between:0,100000000','furniture_deposit_cents'=>'nullable|integer|between:0,100000000','shelter_target'=>'sometimes|integer|between:1,10000','sheltered_capacity'=>'nullable|integer|between:0,10000','seated_capacity'=>'nullable|integer|between:0,10000','included_furniture_sets'=>'sometimes|integer|between:0,1000','extra_furniture_sets'=>'sometimes|integer|between:0,1000','shelter_source'=>'sometimes|in:undecided,own,loan,qapas'])->validate();if($s->exists&&$s->isDirty(['shelter_target','sheltered_capacity','seated_capacity','included_furniture_sets','extra_furniture_sets','shelter_source','larger_tent_requested']))$s->hospitality_validated=false;if($s->exists&&$s->isDirty(['furniture_source','furniture_quantity','furniture_unit_gross_cents','furniture_delivery_cents','furniture_deposit_cents','furniture_evidence'])){$s->furniture_confirmed=false;$s->hospitality_validated=false;}if($s->furniture_confirmed&&!$s->furnitureBudget()['confirmed'])throw \Illuminate\Validation\ValidationException::withMessages(['furniture_confirmed'=>'Documenter la fourniture ; pour une location, renseigner prix, transport et caution (zéro explicite si aucun).']);if($s->hospitality_validated&&blank($s->hospitality_evidence))throw \Illuminate\Validation\ValidationException::withMessages(['hospitality_evidence'=>'Documenter l’abri, les assises, les espaces debout et les circulations.']);if($s->site_feature_id&&!SiteFeature::whereKey($s->site_feature_id)->where('event_project_id',$s->event_project_id)->exists())throw \Illuminate\Validation\ValidationException::withMessages(['site_feature_id'=>'Implantation hors édition.']);});}
 public function eventProject() {return $this->belongsTo(EventProject::class);}
}
