<?php
namespace App\Filament\Pages;
use App\Models\{Scenario,FinancialPlan,FinancialProfile};
use App\Domain\Finance\{FinancialSources,Money};
use Filament\Actions\Action;
use Filament\Forms\Components\{Select,TextInput,Textarea,Repeater,Toggle,DatePicker};
use Filament\Tables\{Table,Contracts\HasTable,Concerns\InteractsWithTable};
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\SelectFilter;
use Filament\Tables\Grouping\Group;
class FinancialPlanning extends \Filament\Pages\Page implements HasTable {
 use InteractsWithTable;
 protected static ?string $title='Rentabilité et trésorerie';
 protected static string|\UnitEnum|null $navigationGroup='2 · Chiffrer';
 protected static ?int $navigationSort=0;
 protected string $view='filament.pages.financial-planning';
 public ?string $scenarioId=null;
 public int $revision=0;
 public static function canAccess(): bool {return auth('admin')->user()?->is_active===true;}
 public function mount(): void {abort_unless(self::canAccess(),403);$requested=request()->query('scenario');$this->scenarioId=Scenario::where('public_id',$requested)->where('is_archived',false)->value('public_id')??Scenario::where('is_archived',false)->orderByRaw("CASE WHEN template_key = 'costing-rental-experts-v1' THEN 0 ELSE 1 END")->value('public_id');$this->synchronize();}
 public function scenarios(){abort_unless(self::canAccess(),403);return Scenario::where('is_archived',false)->with('eventProject')->get();}
 public function plan(): ?FinancialPlan {abort_unless(self::canAccess(),403);$s=Scenario::where('public_id',$this->scenarioId)->where('is_archived',false)->first();return $s?FinancialPlan::firstOrCreate(['scenario_id'=>$s->id],['phases'=>FinancialPlan::phasesFor($s)]):null;}
 public function updatedScenarioId(): void {$this->synchronize();$this->resetTable();}
 public function synchronize(): void {if($p=$this->plan())app(FinancialSources::class)->synchronize($p);$this->revision++;}
 private function schedule(string $name,string $label,?FinancialPlan $plan): Repeater {return Repeater::make($name)->label($label)->schema([Select::make('phase')->label('Phase')->options($plan?->phaseOptions()??[])->required(),TextInput::make('share_basis_points')->label('Part · 10000 = 100 %')->integer()->minValue(1)->maxValue(10000)->required()])->columns(2)->maxItems(24)->defaultItems(0)->helperText('Total exact : 10000. Le dernier terme absorbe les centimes d’arrondi.')->columnSpanFull();}
 protected function getHeaderActions(): array {return [
  Action::make('refreshSources')->label('Actualiser les postes')->action(fn()=>$this->synchronize()),
  Action::make('parameters')->label('Hypothèses et calendrier')->modalWidth('7xl')->fillForm(function(){ $p=$this->plan();if(!$p)return [];return $p->toArray()+collect($p->scenario->only(['months','event_days','organizer_full_monthly_cents','minimum_organizer_charges_cents','organizer_cost_evidence','target_surplus_cents','contingency_cents','refund_reserve_cents']))->mapWithKeys(fn($v,$k)=>['scenario_'.$k=>$v])->all();})->schema(fn()=>[
   TextInput::make('scenario_months')->label('Mois de travail du porteur')->integer()->minValue(1)->maxValue(120)->required(),TextInput::make('scenario_event_days')->label('Jours d’événement')->integer()->minValue(1)->maxValue(366),TextInput::make('scenario_organizer_full_monthly_cents')->label('Coût COMPLET mensuel du porteur · centimes')->integer()->minValue(0)->helperText('Vide = inconnu. Inclure rémunération et charges, ne pas saisir une seconde ligne de coût.'),TextInput::make('scenario_minimum_organizer_charges_cents')->label('Minimum de charges du porteur pour la période · centimes')->integer()->minValue(0),Textarea::make('scenario_organizer_cost_evidence')->label('Justificatif du coût / minimum du porteur'),TextInput::make('scenario_target_surplus_cents')->label('Objectif de surplus mensuel · centimes')->integer()->minValue(0)->required(),TextInput::make('scenario_contingency_cents')->label('Réserve imprévus de l’édition · centimes')->integer()->minValue(0),TextInput::make('scenario_refund_reserve_cents')->label('Réserve remboursements · centimes')->integer()->minValue(0),
   Select::make('vat_regime')->label('Régime IVA réel')->options(['unknown'=>'À confirmer · simulation seulement','normal'=>'Régime normal','exempt'=>'Exonération documentée'])->required(),Textarea::make('vat_evidence')->label('Enregistrement fiscal, périodicité et validation comptable')->columnSpanFull(),
   TextInput::make('opening_cash_cents')->label('Trésorerie AVANT la première phase · centimes')->integer()->required()->helperText('Pas le solde bancaire d’aujourd’hui si des flux du calendrier ont déjà eu lieu.'),TextInput::make('minimum_cash_cents')->label('Matelas supplémentaire à conserver · centimes')->integer()->minValue(0)->required(),
   TextInput::make('opening_vat_credit_cents')->label('Crédit IVA initial reportable · centimes')->integer()->minValue(0)->required(),TextInput::make('opening_vat_due_cents')->label('IVA initiale à payer en première phase · centimes')->integer()->minValue(0)->required(),
   TextInput::make('ticket_target')->label('Tickets prévus · multiplicateur des postes concernés')->integer()->minValue(0)->maxValue(1000000)->required(),TextInput::make('visitor_target')->label('Visiteurs prévus · multiplicateur des postes concernés')->integer()->minValue(0)->maxValue(1000000)->required(),
   Repeater::make('phases')->label('Phases de trésorerie, ordre chronologique')->schema([TextInput::make('key')->label('Clé stable')->required()->maxLength(40),TextInput::make('label')->label('Nom')->required()->maxLength(100),DatePicker::make('date')->label('Date repère')->required(),TextInput::make('vat_payment_phase')->label('Clé de la phase de versement IVA')->required()])->columns(2)->minItems(2)->maxItems(24)->reorderable()->helperText('Les phases peuvent être affinées pour les échéances mensuelles/trimestrielles. Une clé utilisée par un poste ne peut disparaître. Aucun remboursement TVA automatique.')->columnSpanFull(),
   $this->schedule('organizer_cash_schedule','Paiement du coût du porteur, charges incluses une seule fois',$this->plan()),Textarea::make('organizer_schedule_evidence')->label('Justification du calendrier du porteur'),
   Repeater::make('financing')->label('Financements et mouvements hors résultat')->schema([TextInput::make('name')->label('Libellé')->required(),Select::make('kind')->label('Type')->options(['capital'=>'Apport en capital','loan'=>'Emprunt reçu','repayment'=>'Remboursement de principal','owner_advance'=>'Avance de trésorerie du porteur','owner_repayment'=>'Remboursement de cette avance','restricted_in'=>'Caution / fonds affectés reçus','restricted_out'=>'Restitution de caution / fonds affectés'])->required(),TextInput::make('amount_cents')->label('Centimes TTC')->integer()->minValue(0)->required(),Select::make('phase')->label('Phase')->options($this->plan()?->phaseOptions()??[])->required()])->columns(2)->defaultItems(0)->maxItems(100)->helperText('Ni chiffre d’affaires ni bénéfice. Intérêts/frais : postes de coûts distincts. Ne pas ajouter une seconde fois une avance personnelle déjà remboursée via un poste de coût.')->columnSpanFull(),
   Textarea::make('assumptions')->label('Hypothèses du calendrier / financements')->columnSpanFull(),
  ])->action(function(array $data){$p=$this->plan();abort_unless($p,404);\Illuminate\Support\Facades\Validator::make($data,['scenario_months'=>'required|integer|between:1,120','scenario_event_days'=>'nullable|integer|between:1,366','scenario_organizer_full_monthly_cents'=>'nullable|integer|between:0,1000000000','scenario_minimum_organizer_charges_cents'=>'nullable|integer|between:0,1000000000','scenario_target_surplus_cents'=>'required|integer|between:0,1000000000','scenario_contingency_cents'=>'nullable|integer|between:0,1000000000','scenario_refund_reserve_cents'=>'nullable|integer|between:0,1000000000'])->validate();\Illuminate\Support\Facades\DB::transaction(function()use($p,$data){$attributes=[];foreach(['months','event_days','organizer_full_monthly_cents','minimum_organizer_charges_cents','organizer_cost_evidence','target_surplus_cents','contingency_cents','refund_reserve_cents'] as $key)$attributes[$key]=$data['scenario_'.$key]??(in_array($key,['minimum_organizer_charges_cents','contingency_cents','refund_reserve_cents'],true)?0:null);$p->scenario->update($attributes);$p->update(collect($data)->only(['vat_regime','vat_evidence','opening_cash_cents','minimum_cash_cents','opening_vat_credit_cents','opening_vat_due_cents','ticket_target','visitor_target','phases','organizer_cash_schedule','organizer_schedule_evidence','financing','assumptions'])->all());});$this->revision++;}),
 ];}
 public function table(Table $table): Table {
  return $table->query(fn()=>FinancialProfile::query()->where('financial_plan_id',$this->plan()?->id??0))->columns([
   TextColumn::make('name')->label('Poste source')->searchable()->wrap(),TextColumn::make('source_kind')->label('Nature')->badge(),TextColumn::make('behavior')->label('Fixe / variable')->formatStateUsing(fn($state)=>$state==='fixed'?'Fixe':'Variable'),
   TextColumn::make('unit_price')->label('Prix unitaire TTC')->state(fn(FinancialProfile $record)=>$record->source()?->unit_gross_cents===null?'À chiffrer':Money::format($record->source()->unit_gross_cents)),
   TextColumn::make('driver')->label('Quantité')->formatStateUsing(fn($state)=>FinancialProfile::DRIVERS[$state]??$state),TextColumn::make('vat_treatment')->label('IVA')->formatStateUsing(fn($state)=>FinancialProfile::VAT[$state]??$state)->wrap(),
  ])->defaultGroup('category')->groups([Group::make('category')->label('Poste du business plan')->getTitleFromRecordUsing(fn(FinancialProfile $record)=>FinancialProfile::CATEGORIES[$record->category])])->filters([
   SelectFilter::make('behavior')->label('Fixe / variable')->options(['fixed'=>'Fixe','variable'=>'Variable']),SelectFilter::make('source_kind')->label('Coûts / recettes')->options(['cost'=>'Coûts','revenue'=>'Recettes','deposit'=>'Cautions','earmarked'=>'Affecté','third_party'=>'Tiers']),SelectFilter::make('source_type')->label('Origine')->options(['budget'=>'Budget / stands','material'=>'Matériel des épreuves','site'=>'Besoins du terrain']),SelectFilter::make('vat_treatment')->label('Revue IVA')->options(FinancialProfile::VAT),
  ])->recordActions([Action::make('editProfile')->label('Prix, classification et échéancier')->modalWidth('7xl')->fillForm(function(FinancialProfile $record){$s=$record->source();return $record->toArray()+['source_unit_cents'=>$s?->unit_gross_cents,'source_vat_rate'=>$s?->vat_basis_points,'source_quantity'=>$record->source_type==='budget'?$s?->forecast_quantity:$s?->quantity,'source_price_evidence'=>$s?->price_source];})->schema(fn()=>[
   TextInput::make('source_unit_cents')->label('Prix unitaire TTC source · centimes')->integer()->minValue(0)->maxValue(1000000000),TextInput::make('source_quantity')->label('Quantité de base source')->integer()->minValue(0)->maxValue(1000000)->required(),TextInput::make('source_vat_rate')->label('IVA source · 2300 = 23 %, vide = inconnu')->integer()->minValue(0)->maxValue(10000),Textarea::make('source_price_evidence')->label('Source du prix / devis / hypothèse')->helperText('Une modification du prix réécrit la fiche source, jamais un contrat engagé. Le prix redevient une hypothèse à valider.'),
   Select::make('category')->label('Poste du business plan')->options(FinancialProfile::CATEGORIES)->required(),Select::make('behavior')->label('Comportement')->options(['fixed'=>'Fixe pour ce format','variable'=>'Variable selon les quantités / volume'])->required(),Select::make('driver')->label('Multiplicateur de quantité')->options(FinancialProfile::DRIVERS)->required()->helperText('Poste global uniquement. Une ligne liée à un stand ne doit pas être multipliée une seconde fois par tous les stands.'),
   Toggle::make('is_stock')->label('Stock avant consommation · exploitation seulement'),Select::make('invoice_phase')->label('Facture / entrée du stock / créance ou dette')->options($this->plan()?->phaseOptions()??[])->required(),Select::make('consumption_phase')->label('Consommation du stock')->options($this->plan()?->phaseOptions()??[]),
   $this->schedule('cash_schedule','Encaissements ou décaissements TTC',$this->plan()),$this->schedule('vat_schedule','Exigibilité / déductibilité IVA · distincte du paiement',$this->plan()),Textarea::make('schedule_evidence')->label('Acompte, solde, délais et dates justifiés')->columnSpanFull(),
   Select::make('vat_treatment')->label('Qualification fiscale')->options(FinancialProfile::VAT)->required(),TextInput::make('deduction_basis_points')->label('Part d’IVA déductible · 10000 = 100 %, 5000 = 50 %')->integer()->minValue(0)->maxValue(10000)->required(),Textarea::make('vat_evidence')->label('Justification fiscale / droit à déduction / facture')->columnSpanFull(),TextInput::make('depreciation_unit_cents')->label('Investissement : charge par unité affectée à cette édition, centimes')->integer()->minValue(0)->helperText('Décaissement intégral maintenu. Vide : coût complet retenu par prudence dans le résultat, avec alerte. Zéro exige une hypothèse documentée.'),
  ])->action(function(FinancialProfile $record,array $data){abort_unless($record->financial_plan_id===$this->plan()?->id,403);app(FinancialSources::class)->edit($record,$data);$this->revision++;})])->paginated([25,50,100]);
 }
}
